INSTRUMENT_DICT = {
    "Drums": {
        3: "Jungle Drum",
        5: "Congas",
        9: "Timpani",
        20: "Snare Snare Rolls",
        23: "African Log Drum",
        24: "Jazz Kick Drum",
        36: "Brushed Snare",
        60: "Bass Drum",
        64: "Timbale",
        73: "Drum Kit",
        79: "Taiko Drum",
        80: "Steel Drum",
    },
    "Other Percussion": {
        1: "Marimba",
        10: "Tubular Bells",
        11: "Tambourine",
        13: "Maracas",
        19: "Piatti Crash Cymbal",
        21: "Piatti Crash Cymbal",
        25: "Hi-Hats",
        28: "Guiro",
        30: "Celeste",
        35: "Woodpecker",
        51: "Woodblock",
        56: "Church Organ",
        77: "Bell",
    },
    "Strings": {
        2: "Strings",
        4: "Fender Thumb Bass",
        40: "Steel String Guitar",
        44: "Banjo (Instrument)",
        45: "Jaw Harp",
        48: "Fiddle",
        58: "Muted Base",
        66: "Harp",
        74: "Vibrato Strings",
    },
    "Blow Me": {
        6: "Flute",
        7: "Clarinet",
        8: "Baritone Sax",
        12: "Harmonica",
        14: "Tuba",
        17: "Trombone",
        18: "Trumpet",
        22: "Pan Flute",
        29: "Bassoon",
        49: "Kazoo",
        53: "Flute With Pitchbend",
        54: "Clarinet 2",
        63: "Shenai",
        76: "Clave",
        78: "Pan Flute 2",
    },
    "Background": {
        15: "Crickets Frogs Ow",
        16: "Birds Crickets B",
        26: "Chirp",
        27: "Village Chants (MM)",
        33: "Wind",
        34: "Creak",
        37: "Bubbles",
        38: "Rumble",
        39: "Waves",
        41: "Seagulls",
        42: "Frogs",
        43: "Bees",
        46: "Iron Clang",
        55: "Theremin",
        68: "Click Finger Snap",
        69: "Burp + Fart",
        70: "Pizzicato Strings",
        71: "RBB Ambience",
        81: "Gameboy Square 1",
        82: "Gameboy Square 2",
        83: "Gameboy Triangle",
        84: "Gameboy White Noise",
    },
    "Sound FX": {
        31: "Jungle FX",
        32: "Machine FX",
        57: "Spooky FX",
        65: "Drips",
        75: "Lab Electricity FX",
    },
    "Voices": {
        47: "Donkey",
        50: "Animals",
        52: "Banjo Guh-Huh",
        59: "Laugh",
        61: "Jinjo",
        62: "Hup Two Three Four",
        67: "Banjo Doh!",
        72: "Mumbo Vox",
        85: "Bat",
    },
}