from Enums.Item_Enums import *
from Enums.Room_Enums import *
from Enums.Move_Enums import *
from Enums.Health_Enums import *
from Enums.Other_Enums import *

############################
### SPAWNED REQUIREMENTS ###
############################
# LEGEND:
# () = At least one of these
# [] = Must have all of these
# {} = Count of item

CASUAL_SPAWNED_REQUIREMENTS_DICT = {
    # MM
    MM_JINJOS_JIGGY: [MM_BLUE_JINJO, MM_PINK_JINJO, MM_YELLOW_JINJO, MM_GREEN_JINJO, MM_ORANGE_JINJO],
    MM_CHIMPY_JIGGY: [MM_MAIN, MM_ORANGE_JINJO],
    MM_CONGA_JIGGY: [MM_MAIN, EGG_FIRING],
    MM_JUJU_JIGGY: [MM_MAIN, EGG_FIRING],
    MM_ORANGE_PADS_JIGGY: [MM_MAIN],
    MM_HUTS_JIGGY: [MM_MAIN, BEAK_BUSTER],
    # TTC
    TTC_JINJOS_JIGGY: [TTC_BLUE_JINJO, TTC_PINK_JINJO, TTC_YELLOW_JINJO, TTC_GREEN_JINJO, TTC_ORANGE_JINJO],
    TTC_BLUBBER_JIGGY: {BLUBBERS_GOLD: 2}, # DEPENDS
    TTC_LITTLE_LOCKUP_JIGGY: [TTC_MAIN, BEAK_BUSTER],
    # CC
    CC_JINJOS_JIGGY: [CC_BLUE_JINJO, CC_PINK_JINJO, CC_YELLOW_JINJO, CC_GREEN_JINJO, CC_ORANGE_JINJO],
    CC_FREE_CLANKER_JIGGY: [CC_MAIN, DIVE],
    CC_TOOTH_JIGGY: [CC_MAIN, CC_BELLY_MOUTH, EGG_FIRING],
    CC_RINGS_JIGGY: [CC_BELLY_MOUTH, DIVE],
    CC_SNIPPETS_JIGGY: [CC_MAIN, DIVE, (CLAW_SWIPE, ROLL_ATTACK, RAT_A_TAP_RAP, BEAK_BARGE, BEAK_BUSTER, EGG_FIRING)],
    # BGS
    BGS_JINJOS_JIGGY: [BGS_BLUE_JINJO, BGS_PINK_JINJO, BGS_YELLOW_JINJO, BGS_GREEN_JINJO, BGS_ORANGE_JINJO],
    BGS_CENTRAL_SWITCH_JIGGY: [BGS_MAIN, BEAK_BUSTER, TALON_TROT],
    BGS_MAZE_SWITCH_JIGGY: [BGS_MAIN, BEAK_BUSTER, (STILT_STRIDE, EIGHT_HEALTH, [WONDERWING, EIGHT_HEALTH])], # CHECK THIS
    BGS_YELLOW_FLIBBIT_JIGGY: [BGS_MAIN, (CLAW_SWIPE, ROLL_ATTACK, RAT_A_TAP_RAP, BEAK_BARGE, BEAK_BUSTER, EGG_FIRING)],
    BGS_HUTS_JIGGY: [BGS_MAIN, BEAK_BUSTER, HIGH_JUMP, SHOCK_SPRING_JUMP],
    BGS_TANKTUP_JIGGY: [BGS_MAIN, BEAK_BUSTER],
    BGS_TIPTUP_JIGGY: [BGS_TANKTUP, BEAK_BUSTER],
    BGS_MR_VILE_JIGGY: [BGS_MR_VILE, CROCODILE_BK],
    BGS_CROCTUS_JIGGY: [BGS_MAIN, EGG_FIRING, BEAK_BUSTER, HIGH_JUMP, SHOCK_SPRING_JUMP],
    BGS_EGG_JIGGY: [BEAK_BUSTER, RAT_A_TAP_RAP, BEAK_BARGE, ([HIGH_JUMP, SHOCK_SPRING_JUMP], [CLIMB, TALON_TROT])],
    # FP
    FP_JINJOS_JIGGY: [FP_BLUE_JINJO, FP_PINK_JINJO, FP_YELLOW_JINJO, FP_GREEN_JINJO, FP_ORANGE_JINJO],
    FP_SIR_SLUSH_JIGGY: [FP_MAIN, FLIGHT, BEAK_BOMB],
    FP_WOZZA_JIGGY: [FP_MAIN, WALRUS_BK],
    FP_SNOWMAN_BUTTONS_JIGGY: [FP_MAIN, FLIGHT, BEAK_BOMB],
    FP_BOGGY_1_JIGGY: [FP_MAIN, (FLIGHT, TALON_TROT)],
    FP_BOGGY_2_JIGGY: [FP_MAIN, FP_BOGGY_1_JIGGY, WALRUS_BK],
    FP_BOGGY_3_JIGGY: [FP_MAIN, FP_BOGGY_2_JIGGY, TURBO_TALON_TROT],
    FP_PRESENTS_JIGGY: [FP_IGLOO, RED_PRESENT, BLUE_PRESENT, GREEN_PRESENT],
    # FP_TWINKLIES: [FP_MAIN, BEAK_BUSTER],
    # FP_CHRISTMAS_TREE_STAR: [FP_MAIN, FP_TWINKLIES, EGG_FIRING, FLIGHT],
    # FP_CHRISTMAS_TREE_JIGGY: [FP_TREE, CLIMB, HIGH_JUMP],
    # GV
    GV_JINJOS_JIGGY: [GV_BLUE_JINJO, GV_PINK_JINJO, GV_YELLOW_JINJO, GV_GREEN_JINJO, GV_ORANGE_JINJO],
    GV_GRABBA_JIGGY: [GV_MAIN, (TURBO_TALON_TROT, [TALON_TROT, FLIGHT, BEAK_BOMB])],
    GV_MATCHING_PUZZLE_JIGGY: [GV_MATCHING_PUZZLE, BEAK_BUSTER],
    GV_ANCIENT_ONES_JIGGY: [GV_MAIN, (TALON_TROT, TURBO_TALON_TROT), FLIGHT],
    GV_GOBI_JIGGY: [GV_MAIN, (TALON_TROT, TURBO_TALON_TROT), (BEAK_BARGE, BEAK_BUSTER, BEAK_BOMB, EGG_FIRING, WONDERWING)],
    GV_TRUNKER_JIGGY: [GV_GOBI_JIGGY, BEAK_BUSTER],
    GV_GOBI_HONEYCOMB: [GV_TRUNKER_JIGGY, BEAK_BUSTER],
    GV_CACTUS_HONEYCOMB: [GV_MAIN, (TALON_TROT, TURBO_TALON_TROT), BEAK_BUSTER, FLIGHT],
    # MMM
    MMM_JINJOS_JIGGY: [MMM_BLUE_JINJO, MMM_PINK_JINJO, MMM_YELLOW_JINJO, MMM_GREEN_JINJO, MMM_ORANGE_JINJO],
    MMM_MOTZAND_JIGGY: [MMM_CHURCH, FLAP_FLIP, HIGH_JUMP, SHOCK_SPRING_JUMP, BEAK_BUSTER],
    MMM_FLOWER_POTS: [MMM_MAIN, EGG_FIRING], # DEPENDS
    # RBB
    RBB_JINJOS_JIGGY: [RBB_BLUE_JINJO, RBB_PINK_JINJO, RBB_YELLOW_JINJO, RBB_GREEN_JINJO, RBB_ORANGE_JINJO],
    RBB_WHISTLE_JIGGY: [RBB_MAIN, BEAK_BUSTER],
    # CCW
    CCW_JINJOS_JIGGY: [CCW_BLUE_JINJO, CCW_PINK_JINJO, CCW_YELLOW_JINJO, CCW_GREEN_JINJO, CCW_ORANGE_JINJO],
    CCW_GNAWTY_JIGGY: [CCW_SUMMER_MAIN, (CCW_AUTUMN_MAIN, CCW_WINTER_MAIN), DIVE, (EGG_FIRING, BEAK_BARGE, BEAK_BUSTER, WONDERWING)],
    CCW_EYRIE_JIGGY: [CCW_SPRING_MAIN, CCW_SUMMER_MAIN, CCW_AUTUMN_MAIN, CCW_WINTER_MAIN, HIGH_JUMP, SHOCK_SPRING_JUMP, BEAK_BUSTER, {CATERPILLAR: 15}],
    CCW_NABNUT_JIGGY: [CCW_AUTUMN_MAIN, {ACORN: 15}], # DEPENDS
    CCW_PLANT_JIGGY: [CCW_SPRING_MAIN, CCW_SUMMER_MAIN, CCW_AUTUMN_MAIN, EGG_FIRING, BEAK_BUSTER],
    # GL
    GL_JINJOS_JIGGY: [GL_BLUE_JINJO, GL_PINK_JINJO, GL_YELLOW_JINJO, GL_GREEN_JINJO, GL_ORANGE_JINJO],
    GL_MM_WITCH_SWITCH_JIGGY: [MM_WITCH_SWITCH, GL_MM_ENTRANCE, TERMITE_BK],
    GL_TTC_WITCH_SWITCH_JIGGY: [TTC_WITCH_SWITCH, GL_TTC_ENTRANCE, FLAP_FLIP],
    GL_CC_WITCH_SWITCH_JIGGY: [CC_WITCH_SWITCH, BEAK_BUSTER],
    GL_MMM_WITCH_SWITCH_JIGGY: [MMM_WITCH_SWITCH, GL_FP_ENTRANCE, (RAT_A_TAP_RAP, [FLIGHT, BEAK_BOMB], EGG_FIRING, WONDERWING)],
    GL_RBB_WITCH_SWITCH_JIGGY: [RBB_WITCH_SWITCH, GL_640_NOTE_DOOR, WATER_LEVEL_2],
    GL_CCW_WITCH_SWITCH_JIGGY: [CCW_WITCH_SWITCH, GL_CCW_ENTRANCE, BEE_BK],
    # OTHER STATIC PROGRESSION
    GL_SHED_GATE: [GL_MMM_ENTRANCE, (RAT_A_TAP_RAP, EGG_FIRING, BEAK_BARGE, WONDERWING)],
    WATER_LEVEL_1: [GL_SHED_GATE, PUMPKIN_BK, BEAK_BUSTER],
    WATER_LEVEL_2: [GL_RBB_ENTRANCE, WATER_LEVEL_1, BEAK_BUSTER, ([TALON_TROT], [HIGH_JUMP, FEATHERY_FLAP])], # CHECK THIS
}