###############
### GENERAL ###
###############

SHORTEN_BOTTLES_SECRET_GAME_TEXT = {
    "CF98": { # 5C9B60
        0: "GET THE SANDCASTLE JIGGY FIRST.",
        5: "TELL US NOW!",
        2: "JUST GET THE JIGGY FIRST!",
        7: "C'MON KAZOOIE, LET'S COME BACK LATER.",
    }
}

###############
### OPTIONS ###
###############

REMOVE_BOTTLES_TUTORIAL_SPEECH_DICT = {
    "CF90": { # 5C9AF8
        0: "IF YOU'RE PLAYING THIS MOD, YOU WON'T NEED A TUTORIAL, SO PRESS B.",
    },
    "CF80": { # 5C9A18
        0: "THE TUTORIAL IS DISABLED, JUST PRESS B ALREADY!",
    }
}

CHEATO_BLUE_EGGS_SPEECH_DICT = {
    "DBD8": { # 5CDA58
        0: "YOU CAN NOW CARRY MORE EGGS!",
        # 1: "THAT LOUSY CHEAT FOR EXTRA EGGS,",
        # 2: "WON'T HELP BEAR AND CHICKEN LEGS!",
    }
}

CHEATO_RED_FEATHERS_SPEECH_DICT = {
    "DBD8": { # 5CDAD0
        0: "YOU CAN NOW CARRY MORE RED FEATHERS!",
        # 1: "ALL MY FEATHERS, IT MAKES ME SICK,",
        # 2: "FLY TO ME, YOUR BUTT I'LL KICK!",
    }
}

CHEATO_GOLD_FEATHERS_SPEECH_DICT = {
    "DBD8": { # 5CDB50
        0: "YOU CAN NOW CARRY MORE GOLD FEATHERS!",
        1: "YOU NEEDED HELP, THAT'S NO DOUBT,",
        2: "BUT WITH PLENTY ATTACKS, YOU WILL RUN OUT!",
    }
}

##################
### RANDOMIZER ###
##################

RANDOMIZER_INTRO_CUTSCENE_SPEECH_DICT = {
    "D150": { # 5CA8F8
        0: "DINGPOT, DINGPOT THAT I CLAIM,",
        1: "WHO HAS THE TOUGHEST GAME?",
        2: "WHY IT'S GRUNTY'S ANY DAY,",
        3: "HER LEVELS TAKE PLAYERS' LIVES AWAY...COUGH!",
        4: "YES YOU'RE RIGHT, I'M RATHER PROUD,",
        5: "MY WORLDS STAND ME OUT FROM THE CROWD!",
    },
    "D158": { # 5CA9B0
        0: "ERR...BUT MOST HAVE BEATEN IT...",
        1: "WHAT D'YOU MEAN, THIS CANNOT BE,",
        2: "THE LAST TWO WORLDS AREN'T EASY!",
        3: "PLAYERS MEMORIZED EVERY SPOT,",
        4: "THEY MOVE QUICKLY IN TALON TROT.",
        5: "NO NO NO YOU MUST BE MAD,",
        6: "HARDER GAMEPLAY CAN'T BE HAD!",
        7: "I THINK YOU'LL COME TO KNOW,",
        8: "THERE'S A ROUTE PLAYERS LIKE TO GO.",
    },
    # "D160": { # 5CAA88
        # 0: "WELL...WE'LL SEE ABOUT THAT!",
    # },
    "D168": { # 5CAAB8
        # 0: "HI THERE TOOTY, WHAT ARE YOU GOING TO DO TODAY?",
        3: "I'M GOING TO WATCH MY BROTHER SPEEDRUN THE GAME HAHA!",
    },
    "D170": { # 5CAB30
        1: "WAKE UP, I WANT TO GET UNDER 2 HOURS!",
    },
    "D178": { # 5CAB70
        0: "IF PLAYERS THINK THEY KNOW THE GAME WELL,",
        1: "I'LL CHANGE THE GAME WITH MY ýlRANDOMIZE SPELL!",
    },
    # "D180": { # 5CABD0
        # 0: "IS THAT YOUR BROTHER?",
        # 2: "UP THERE IN THE SKY!",
        # 5: "WHERE, MR. MOLE? I CAN'T SEE HIM...",
    # },
    "D188": { # 5CAC38
        1: "OH NO... THAT'S A BAD SEED!",
    },
    "D190": { # 5CAC70
        0: "ONCE I MOVE SOME THINGS AROUND,",
        1: "NO COLLECTABLES WILL BE FOUND!",
    },
    "D198": { # 5CACC0
        1: "PUT THAT BACK, YOU UGLY OLD HAG!",
    },
    "D1A0": { # 5CACF8
        0: "I'LL PUT THIS HERE, I'LL PUT THAT THERE,",
        1: "NOW THERE ARE NEW THINGS EVERYWHERE!",
    },
    "D1A8": { # 5CAD58
        0: "I CAN'T TELL, IS THIS WORLD RECORD PACE?",
    },
    # "D1B0": { # 5CAD98
        # 1: "BANJO! WAKE UP......NOW!",
    # },
    # "D1B8": { # 5CADC8
        # 1: "YAWN...WHAT DO YOU WANT KAZOOIE?",
    # },
    # "D1C0": { # 5CAE00
        # 1: "LET'S GET OUTSIDE, THERE'S TROUBLE!",
    # }
}

RANDOMIZER_ENTER_LAIR_CUTSCENE_SPEECH_DICT = {
    "D1C8": { # 5CAE38
        0: "WITH EVERYTHING JUMBLED, I'LL HAVE MORE TIME,",
        1: "TO STEAL YOUR BEAUTY AND BE AT MY PRIME!",
        10: "MY BROTHER BEAT YOU BEFORE,",
        11: "HE WILL BEAT YOU AGAIN!",
        3: "THERE IS NO GUIDE FOR RNG,",
        4: "I DOUBT HE EVEN OPENED THE README!",
        5: "NOW HURRY KLUNGO, IT'S TIME TO START,",
        6: "I WANT TO LOOK LIKE ALL MY FAN ART!",
        7: "YESSS MISSSTRESSS GRUNTY!",
        13: "THIS IS SO NOT WAHAY...",
    }
}

RANDOMIZER_BOTTLES_FIRST_WORLD_SPEECH_DICT = {
    "DA88": { # 5CC988
        0: "THAT'S IT! THE PICTURE'S COMPLETE AND THE DOOR TO <WORLD_NAME> IS OPEN!",
        # 1: "THAT WAS SUCH AN EASY FIT,",
        # 2: "THE OTHERS MAY JUST TEST YOUR WIT!",
    },
    "DA90": { # 5CCA10
        0: "IS THIS YOUR FIRST TIME PLAYING BANJO-KAZOOIE? GO GET A JIGGY, 4HEAD!",
    },
    "DA98": { # 5CCAA8
        0: "IS IT REALLY MUMBO'S MOUNTAIN? MAYBE THE PICTURES SHOULD BE UPDATED...",
    }
}

RANDOMIZER_ENOUGH_ITEMS_FOR_NOTE_DOOR_SPEECH_DICT = {
    "DA38": { # 5CC5C8
        0: "YIPPEE! YOU'VE COLLECTED ENOUGH <ITEM> TO BREAK THE FIRST <ITEM> DOOR SPELL!",
    }
}

RANDOMIZER_BOTTLES_TUTORIAL_SPEECH_DICT = {
    "CF90": { # 5C9AF8
        0: f"YOU'LL NEED <ITEM_1_COUNT> <ITEM_1> AND <ITEM_2_COUNT> <ITEM_2> TO REACH GRUNTY. PRESS B TO MOVE ON."
    }
}

####################
### BANJO SOULIE ###
####################

BANJO_SOULIE_INTRO_BOTTLES_SPEECH_DICT = {
    "CE30": { # 5C85D8
        0: "WELCOME TO BANJO-SOULIE!",
        12: "THIS LOOKS LIKE BASE GAME, BUT WITH LESS HEALTH?",
        2: "THAT'S BECAUSE THE CREATOR SUCKS AT USING BLENDER.",
        14: "THERE ARE SO MANY TUTORIALS ON YOUTUBE, IT'S NOT EVEN HARD!",
        15: "SO WHAT IS DIFFERENT, BOTTLES?",
        4: "ENEMIES WILL DROP NOTES INSTEAD OF HEALTH, AND THERE ARE NO NOTES FLOATING AROUND.",
        17: "PFT ALL OF THE ENEMIES WERE EASY TO BEAT ANYWAY.",
        6: "THAT'S NOT ALL THAT'S DIFFERENT.",
        8: "SOME ENEMIES WILL HAVE LESS WEAKNESSES YOU'LL HAVE TO FIGURE OUT ON YOUR OWN.",
    }
}

##############
### CRINGE ###
##############

CRINGE_GAME_OVER_CUTSCENE_SPEECH_DICT = {
    "D1D0": { # 5CAF48
        0: "THE PLAYER IS NOW REGRETTING,",
        1: "TURNING ON A HARDER SETTING!",
    },
    "D1D8": { # 5CAF98
        0: "GEE GEE EASSSY, AMAZZZING CHESSST AHEAD...",
    },
    "D1E0": { # 5CAFE8
        1: "TRANSSSFORMATION ISSS SSSUCCESSSSFUL!",
        3: "ýhOH ýhNO! ýhTHERE'S ýhA ýhYUM-YUM ýhIN ýhHERE!ýl",
    },
    "D1E8": { # 5CB058
        0: "NOW THAT I AM SO MUCH HOTTER,",
        1: "I CAN SELL MY CAULDRON WATER!",
        2: "YASSS MISSSTRESSS! SSSLAY!",
    },
    "D230": { # 5CB2C8
        0: "MOMMY? SORRY, MOMMY? SORRY, MOMMY?...",
    },
    "D200": { # 5CB100
        0: "BANJO! YOUR SISTER HAS TWO WORDS FOR YOU...",
        1: "GIT GUD!",
    },
}

CRINGE_SLIPPERY_SLOPE_SPEECH_DICT = {
    "B900": { # 5C42F0
        0: "LMAO CAUGHT YOU SLIPPIN' IN 4K!",
    }
}

CRINGE_MOVES_SPEECH_DICT = {
    "D9D8": { # 5CC1B0
        0: "BEAR AND BIRD FIND MOLE AND LEARN MOVES!",
    },
    "B908": { # 5C4350
        0: "EEKUM BOKUM!",
    },
    "DA08": { # 5CC390
        0: "WHAT'S THE MATTER? DON'T LIKE BACKTRACKING? GUESS YOU WON'T LIKE TOOIE...",
    },
    "D9E0": { # 5CC210
        0: "REMEMBER CAP'N BLACKEYE? ME NEITHER!",
    },
    "AFD0": { # 5C2BC0
        0: "THE REAL LOOT BE THE SCALLYWAGS WE MADE ALONG THE WAY!",
    },
    "DA10": { # 5CC3F8
        0: "THE CAMERAS GET FUNKY WHEN YOU LEARN A MOVE NOT FROM THAT LEVEL!",
    },
    "D9E8": { # 5CC268
        0: "WHAT IS CLANKER ANYWAY? A SHARK? A WHALE?",
    },
    "C850": { # 5C7818
        0: "IS ANYONE REALLY FREE WHEN CHAINED TO SOCIETY?",
    },
    "DA18": { # 5CC450
        0: "BABY SHARK DO DO DO DO DO DO!",
    },
    "D9F0": { # 5CC2B8
        0: "WHAT ARE YEW DOIN' IN MY SWAMP?!",
    },
    "C2E8": { # 5C6358
        0: "IT SMELLS LIKE A VIDEO GAME CHAMPIONSHIP HERE...",
    },
    "DA20": { # 5CC4A8
        0: "THESE BOOTS ARE MADE FOR WALKIN, THAT'S JUST WHAT THEY'LL DO...",
    },
    "D9F8": { # 5CC300
        0: "WHAT'S THIS? DROPS OF RAIN FROZEN INTO ICE CRYSTALS? I SHALL HARNESS THEIR ENERGY AND RULE THE WORLD!",
    },
    "BFE8": { # 5C5680
        0: "HAPPY WALRUS NOISES!",
    },
    "DA28": { # 5CC508
        0: "CHRISTMAS IS OVER, TIME FOR VALENTINES DAY DECORATIONS!",
    },
    "DA00": { # 5CC350
        0: "I DON'T LIKE SAND. IT'S COARSE AND ROUGH AND IRRITATING AND IT GETS EVERYWHERE.",
    },
    "B2C8": { # 5C33E8
        0: "CHILI DOGS!"
    },
    "DA30": { # 5CC560
        0: "THERE ARE SOME REALLY COOL IMAGES ON THE WALLS IN THE MAZE!",
    },
}

CRINGE_FIRST_DEATH_SPEECH_DICT = {
    "DAA0": { # 5CCB08
        0: "TRYING TO GET THE GAME OVER SCREEN?!",
        1: "YOU ARE LIKE A PERVERTED TEEN!",
    }
}

############################
### GRUNTILDA LAIR QUIPS ###
############################

GRUNTILDA_LAIR_QUIP_LIST = [
    # Inside Jokes
    ("PROUD OF YOURSELF? THINK YOU'RE A HERO?", "YOU'RE NOTHING BUT A LEADING ZERO!"),
    ("THERE'S A FEATURE YOU WANT TO SEE?", "REQUEST IT BEFORE VERSION 3!"),
    # Shoutouts
    ("WANT TO MAKE A BK HACK?", "JOIN THE SERVER CALLED BANJO'S BACKPACK!"), # Banjo's Backpack (Approved)
    ("DON'T KNOW KURKO? THAT IS A CRIME!", "GO TRY OUT HIS JIGGIES OF TIME!"), # Kurko Mods (Approved)
    ("ONLY ONE LEVEL, BUT IT'S WORTH A BOAST!", "GO TRY OUT CUT-THROAT COAST!"), # Retro (Approved)
    ("YOU KNOW WHO DESERVES SOME RIBBONS?", "THAT ONE HACKER WE CALL MITTENZ!"), # Mittenz (Approved)
    ("NEED MORE BK? HERE'S AN EXPANSION!", "LOOK UP A MOD CALLED GRUNTY'S MANSION!"), # JacksonG13 (Approved)
    ("WANT A CHALLENGE WHERE YOU'RE SURE TO DIE?", "TRY FORT FUN BY THATCOWGUY!"), # ThatCowGuy (Approved)
    ("BELOVED BY ALL, HIS MUSIC IS DOPE!", "BIG SHOUTOUTS TO GRANT KIRKHOPE!"), # Grant Kirkhope
    ("YOU'RE OUT OF STYLE, COULDN'T BE LAMER!", "TRY WEARING A HAT, AND BEING A GAMER!"), # HatWearingGamer (Approved)
    ("YOU WANT TO SEE A MODDED TOOIE?", "THERE'S TONS OF FEATURES ON SNOOIE!"), # Wedarobi (Approved)
    ("YOU SEEM TO BE FULL OF RAGE.", "TRY CALMING DOWN LIKE MONOTONE GAGE!"), # Gage (Approved)
    ("BLAST THAT STUPID NINPALK SKIP!", "I NEED THAT CUTSCENE FOR TIME TO DIP!"), # Ninpalk (Approved)
    ("YOU HAVEN'T CLIPPED THROUGH THE FLOOR AT LEAST,", "IT SEEMS YOU'RE NO 8 BIT BEAST!"), # The8BitBeast (Approved)
    ("WANNA SEE RUNNERS AT A FAST PACE?", "CHECK OUT THE TWITCH CHANNEL BANJO RACE!"), # GarageDoorOpener (Approved)
    ("LOVEABLE STREAMER, HIS NAME IS DEDE,", "FULL OF CHARM AND HIS SOCKS ARE STINKY!"), # Dedelux (Approved)
    ("NADE, CHILE, TREP, AND MORE,", "ARE TOO AFRAID OF LOSING THEIR NOTE SCORE!"), # XBOX Players
    ("EVEN WITH ALL OF THEIR SWEARS,", "THIS SHOUTOUT IS FOR MY DROP BEARS!"), # Australian Players
    # Poking The Community
    ("WE GET IT, YOU CAN STOP, GOGO!", "THE GRUNTY'S REVENGE SCENE WILL NEVER GROW!"), # G0go (Approved)
    # References
    ("MARIO IS JUST A PLUMBER,", "BUT YOU STILL MANAGE TO BE DUMBER!"), # Mario
    ("IF KIRBY DECIDED TO SWALLOW YOU,", "THEN HE'D END UP STUPID TOO!"), # Kirby
    ("THAT'S ALL YOU HAVE, JUST YOU TWO?", "HALF THE SIZE OF THE DK CREW!"), # Donkey Kong
    ("TOO MANY ITEMS, I THINK NOT!", "YOU STILL NEED BOMBCHUS AND A HOOKSHOT!"), # Legend Of Zelda
    ("YOU LEARN NEW MOVES BUT ONLY USE FOUR,", "GET IN MY POKEBALL, I'LL TEACH YOU MORE!"), # Pokemon
    ("A BEAR AND A BIRD? NO ONE WANTS THAT!", "WE ALL WANT THE LIZARD AND BAT!"), # Yooka Laylee
    ("OVER THE FIREPLACE YOU SHALL STAY,", "WHILE I DRINK MY POTIONS ON A BAD FUR DAY!"), # Conker
    ("MY NEW TRICKS WILL MAKE YOU FOOLIES,", "JUST WAIT TIL YOU'RE GRABBED BY THE GHOULIES!"), # Grabbed By The Ghoulies
    ("WHEN I AM PRETTY, I'LL ATTRACT THE COLTS,", "WHILE YOU PLAY WITH YOUR NUTS AND BOLTS!"), # Nuts And Bolts
    ("YOU SUMMON KAZOOIE, IS THAT HER PREFERENCE?", "LOOKS A LOT LIKE A JOJO REFERENCE!"), # Jojo's Bizzare Adventure
    ("COULD YOU HAVE ANY SLOWER PACING?", "YOU SHOULD GO BACK TO DIDDY KONG RACING!"), # Diddy Kong Racing
    ("YOU LACK STYLE, BUT YOUR BACKPACK'S GOT DRIP.", "I'VE SEEN IT BEFORE IN AN AIRSHIP!"), # Among Us Reference
    ("YOU THINK YOU'RE GOOD, I THINK YOU'RE TRASH!", "LET'S SETTLE THIS IN SMASH!"), # Super Smash Bros
    ("YOU LACK WIT, YOU HAVE NO BRAIN!", "I'M SURPRISED YOU COULD FLY A PLANE!"), # Banjo Pilots
    # Community Submissions
    ("HAVE YOU EVER TRIED HOLDING Z?", "SOME WACKY DRAGON USED IT TO GET PAST ME!"), # BlackDragonMax
    ("I DON'T LIKE SAND MUCH IN MY LAIR.", "IT'S COURSE AND ROUGH AND GETS EVERYWHERE!"), # HatWearingGamer
]