# CONTANTS FOR COLLISION INDICES
COMMON = 0x2
CLAW_SWIPE = 0x4
ROLL_ATTACK = 0x6
JUMPING_ON_THEM = 0x8
RATATAP_RAP = 0xA
BEAK_BARGE = 0xC
BEAK_BUSTER = 0xE
BEAK_BOMB = 0x10
EGG_FIRING = 0x12
WONDERWING = 0x14
CROC_BITE = 0x16
OTHER_CONTACT = 0x18

# aaaa = Does BK Bounce Off Or Take Damage? And By How Much?
#   0 | 0000 Nothing
#   1 | 0001 Damage BK, Tiny Push Back
#   2 | 0010 Damage BK, Small Push Back
#   3 | 0011 Damage BK, Decent Push Back
#   4 | 0100 Damage BK, Far Push Back
#   5 | 0101 Damage BK, Very Far Push Back
#   6 | 0110 Nothing
#   7 | 0111 Bounce Off, Tiny Push Back
#   8 | 1000 Bounce Off, Small Push Back
#   9 | 1001 Bounce Off, Decent Push Back
#   A | 1010 Bounce Off, Far Push Back
#   B | 1011 Bounce Off, Very Far Push Back
#   C | 1100 Nothing
#   D | 1101 Nothing
#   E | 1110 Nothing
#   F | 1111 Nothing
# bb = State When Collision Is Triggered?
#   01 = Alternate State
#   10 = Killed
# ccc = Sound Effect When Collision Is Triggered?
# dd = How Much Damage Does BK Take?
# eee = How Many Hits To Trigger?
# ff = Number Of Honeycombs Spawned When Triggered?
# LIST_NAME =           [a, b, c, d, e, f]
# No Interact
ZEROED_LIST =           [0, 0, 0, 0, 0, 0]
# Drops
DROP_NOTES =            [0, 0, 0, 0, 0, 1]
DROP_EGGS =             [0, 0, 0, 0, 0, 2]
DROP_GOLD_FEATHERS =    [0, 0, 0, 0, 0, 3]
# Claw Swipe Kill
ONE_HIT_CLAW_KILL =     [0, 2, 2, 0, 1, 0]
THREE_HIT_CLAW_KILL =   [0, 2, 2, 0, 3, 0]
FIVE_HIT_CLAW_KILL =    [0, 2, 2, 0, 5, 0]
SEVEN_HIT_CLAW_KILL =   [0, 2, 2, 0, 7, 0]
# Rat-A-Tap Rap Kill
ONE_HIT_AIR_KILL =      [0, 2, 3, 0, 1, 0]
THREE_HIT_AIR_KILL =    [8, 2, 3, 0, 3, 0]
FIVE_HIT_AIR_KILL =     [8, 2, 3, 0, 5, 0]
SEVEN_HIT_AIR_KILL =    [8, 2, 3, 0, 7, 0]
# Heavy Kill
ONE_HIT_HEAVY_KILL =    [0, 2, 4, 0, 1, 0]
THREE_HIT_HEAVY_KILL =  [0, 2, 4, 0, 3, 0]
FIVE_HIT_HEAVY_KILL =   [0, 2, 4, 0, 5, 0]
SEVEN_HIT_HEAVY_KILL =  [0, 2, 4, 0, 7, 0]
# Alt State
ONE_HIT_ALT_STATE =     [0, 1, 2, 0, 1, 0]
THREE_HIT_ALT_STATE =   [0, 1, 2, 0, 3, 0]
FIVE_HIT_ALT_STATE =    [0, 1, 2, 0, 5, 0]
SEVEN_HIT_ALT_STATE =   [0, 1, 2, 0, 7, 0]
# Egg
EGG_NO_DAMAGE =         [0, 0, 0, 0, 1, 0]
EGG_FOUR_HIT =          [0, 2, 2, 0, 4, 0]
EGG_FIVE_HIT =          [0, 2, 2, 0, 5, 0]
EGG_SIX_HIT =           [0, 2, 2, 0, 6, 0]
EGG_SEVEN_HIT =         [0, 2, 2, 0, 7, 0]
# Wonderwing
WONDERWING_ONE_HIT =    [0, 2, 5, 0, 1, 3]
# Damage BK
ONE_DAMAGE_LOW_PUSH =   [1, 0, 0, 1, 0, 0]
TWO_DAMAGE_MED_PUSH =   [3, 0, 0, 1, 0, 0]
THREE_DAMAGE_BIG_PUSH = [5, 0, 0, 1, 0, 0]
# Bounce BK
BOUNCE_OFF_LOW =        [7, 0, 2, 0, 0, 0]
BOUNCE_OFF_MED =        [9, 0, 2, 0, 0, 0]
BOUNCE_OFF_BIG =        [11, 0, 2, 0, 0, 0]

BANJO_SOULIE_MARKERS = {
	# 0x0000: { # MARKER NAME
	# 	  COMMON:          [],
    #     CLAW_SWIPE:      [],
    #     ROLL_ATTACK:     [],
    #     JUMPING_ON_THEM: [],
    #     RATATAP_RAP:     [],
    #     BEAK_BARGE:      [],
    #     BEAK_BUSTER:     [],
    #     BEAK_BOMB:       [],
    #     EGG_FIRING:      [],
    #     WONDERWING:      [],
    #     CROC_BITE:       [],
    #     OTHER_CONTACT:   [],
	# },
	0xD598: { # Topper (Non-Tutorial)
        # Generic Common Enemy
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
	},
	0xD5B2: { # Bawl (Non-Tutorial)
        # Weak To Claw Swipe
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      ONE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
	},
    0xD5CC: { # Cauliwobble (Non-Tutorial)
        # Weak To Rat-A-Tap Rap
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     ONE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD5E6: { # Gruntling (Red)
        # Not In Soulie
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      ZEROED_LIST,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ZEROED_LIST,
        RATATAP_RAP:     ZEROED_LIST,
        BEAK_BARGE:      ZEROED_LIST,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      ZEROED_LIST,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ZEROED_LIST,
    },
    0xD600: { # Gruntling (Blue)
        # Not In Soulie
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      ZEROED_LIST,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ZEROED_LIST,
        RATATAP_RAP:     ZEROED_LIST,
        BEAK_BARGE:      ZEROED_LIST,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      ZEROED_LIST,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ZEROED_LIST,
    },
    0xD61A: { # Gruntling (Black)
        # Not In Soulie
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      ZEROED_LIST,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ZEROED_LIST,
        RATATAP_RAP:     ZEROED_LIST,
        BEAK_BARGE:      ZEROED_LIST,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      ZEROED_LIST,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ZEROED_LIST,
    },
    0xD64E: { # Grublin
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD668: { # Ticker
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD6D0: { # Snippet/Mutie Snippet
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD6EA: { # Snippet/Mutie Snippet (Upside Down)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD704: { # Black Snippet
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD71E: { # Black Snippet (Upside Down)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD738: { # Yum-Yum
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD752: { # Shrapnel
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD76C: { # Snacker
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD808:  { # Grille Chompa A
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD822:  { # Grille Chompa B
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    # 0xD856: { # Whiplash
    # },
    0xD870: { # Chump 1 (Lair vs RBB?)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD88A: { # Chump 2 (Lair vs RBB?)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD8A4: { # Red Flibbit
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD8BE: { # Yellow Flibbit
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD8D8: { # Buzzbomb
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD8F2: { # Sir Slush (Body)
    },
    0xD90C: { # Sir Slush (Hat)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD926: { # Twinklie Muncher
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD95A: { # Chinker (Large)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD974: { # Chinker (Small)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD98E: { # Slappa
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD9A8: { # Scabby
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD9C2: { # Mum-Mum
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD9DC: { # Mum-Mum Ball
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xD9F6: { # Limbo
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDA10: { # Tee-Hee (Green)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDA2A: { # Tee-Hee (Purple)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDA44: { # Ripper
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDA5E: { # Giant Ripper
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDA78: { # Nibbly
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDA92: { # Portrait Chompa A
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDAAC: { # Portrait Chompa B
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDAC6: { # Seaman Grublin
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDAE0: { # Flotsam
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDAFA: { # Boom Box
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    # 0xDB14: { # Grimlet
    # },
    0xDB2E: { # Boss Boom Box (Largest)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDB48: { # Boss Boom Box (Large)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDB62: { # Boss Boom Box (Medium)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDB7C: { # Boss Boom Box (Small)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDBFE: { # Grublin Hood
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDC18: { # Whipcrack
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDC4C: { # Clucker (Single Attack)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xDC66: { # Clucker (Multi Attack)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xE12C: { # Zubba (Attacking)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xE146: { # Beehive
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xE640: { # Snowball
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xE792: { # FB Gruntilda On Broomstick (Default/Phase 1 & 2 Vulnerable)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xE7AC: { # FB Gruntilda On Broomstick (Phase 1 Attacking)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xE7C6: { # FB Gruntilda On Broomstick (Phase 2 Moving)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xE7E0: { # FB Gruntilda On Broomstick (Phase 3 Flying)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xE7FA: { # FB Gruntilda On Broomstick (Phase 4/5)
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
    0xE814: { # FB Gruntilda's Barrier Spell
		COMMON:          ZEROED_LIST,
        CLAW_SWIPE:      THREE_HIT_CLAW_KILL,
        ROLL_ATTACK:     ZEROED_LIST,
        JUMPING_ON_THEM: ONE_DAMAGE_LOW_PUSH,
        RATATAP_RAP:     THREE_HIT_AIR_KILL,
        BEAK_BARGE:      ONE_HIT_HEAVY_KILL,
        BEAK_BUSTER:     ZEROED_LIST,
        BEAK_BOMB:       ZEROED_LIST,
        EGG_FIRING:      EGG_FOUR_HIT,
        WONDERWING:      ZEROED_LIST,
        CROC_BITE:       ZEROED_LIST,
        OTHER_CONTACT:   ONE_DAMAGE_LOW_PUSH,
    },
}