from numpy import array

CLEAR_SETUP_FILE_COMPLEX_LIST = array([
	"Bigbutt",
	"Ticker",
	"Grublin",
	"Mumbo",
	"Conga",
	"MM Hut",
	"Chump",
	"Shock Jump Pad",
	"BGS Hut",
	"Chimpy",
	"Ju-Ju",
	"Beehive",
	"Leaky",
	"Pumpkin Transformation",
	"Crocodile Transformation",
	"Walrus Transformation",
	"Bee Transformation",
	"MMM Flower Pot (Thaaaaank Youuuu)",
	"Start Climb",
	"Start Climb (Conga Tree)",
	"End Climb (Can't Go Higher)",
	"End Climb (Conga Tree)",
	"End Climb (Jump At Peak)",
	"End Climb (Jump At Peak)/CC Green Drain",
	"Orange",
	"Blubber's Gold",
	"Mumbo Token",
	"Waterfall Smoke",
	"School Of Fish",
	"Motzand",
	"Clanker's Key",
	"CC Sawblades (Witch Switch Room)",
	"Clanker's Sawblade",
	"Clanker's Bolt",
	"Jiggy",
	"Empty Honeycomb",
	"Extra Life",
	"Honeycomb",
	"Blue Egg",
	"Red Cross",
	"Shrapnel",
	"Orange Pad",
	"BGS Egg 1",
	"Yellow Jinjo",
	"Orange Jinjo",
	"Blue Jinjo",
	"Pink Jinjo",
	"Green Jinjo",
	"Snippet",
	"Yum-Yum",
	"Camera Entry 15",
	"Camera Entry 1",
	"Camera Entry 2",
	"Camera Entry 3",
	"Camera Entry 4",
	"Camera Entry 5",
	"Camera Entry 8",
	"Camera Entry 12",
	"Banjo's Curtains",
	"Chimpy's Tree Stump",
	"Where Banjo Throws Chimpys Orange",
	"Ripper",
	"Tee-Hee",
	"1881 Barrel Top",
	"Camera Controller 1",
	"Camera Controller 2",
	"Camera Controller 3",
	"Camera Controller 5",
	"Camera Controller 6",
	"Camera Controller 10",
	"Camera Controller 12",
	"Flight Pad",
	"Gloop",
	"Tanktup",
	"BGS Egg 2",
	"BGS Egg 3",
	"BGS Egg 4",
	"BGS Leaf",
	"Black Snippet",
	"Mutie Snippet",
	"BGS Big Alligator Head",
	"Honeycomb Spawn",
	"Clanker Ring 1",
	"Clanker Ring 2",
	"Clanker Ring 3",
	"Clanker Ring 4",
	"Clanker Ring 5",
	"Clanker Ring 6",
	"Clanker Ring 7",
	"Clanker Ring 8",
	"Clanker's Tooth 1",
	"Clanker's Tooth 2",
	"MMM Tumblar Shack Door",
	"MMM Mansion Door",
	"MMM Locked Gate (Lock Left)",
	"MMM Locked Gate (Lock Right 2)",
	"Salty Hippo Upper Entrance Plank",
	"Camera Entry 19",
	"Camera Entry 20",
	"MMM Church Door",
	"Blubber",
	"FP Button 1",
	"FP Button 2",
	"FP Button 3",
	"Nipper",
	"GV Jinxy Magic Carpet",
	"GV Sarcophagus",
	"Rubee",
	"Histup",
	"Rubee's Egg Pot",
	"Grabba",
	"Cactus",
	"Slappa",
	"GV Jinxy Head (Inside Jinxy)",
	"GV Main Magic Carpet",
	"Sir Slush",
	"Red Feather",
	"Bottles Mound (Start)",
	"Bottles Mound (Camera)",
	"Bottles Mound (Swim)",
	"Bottles Mound (Attack)",
	"Bottles Mound (Beak Barge)",
	"Bottles Mound (Jump)",
	"Bottles Mound (Climb)",
	"Bottles Mound (Top Of SM)",
	"Gobi 1",
	"Gobi's Rock",
	"Gobi 2",
	"Trunker",
	"Red Flibbit",
	"Buzzbomb",
	"Gobi 3",
	"Yellow Flibbit",
	"Yumblie/Grumblie",
	"Mr Vile",
	"Flotsam",
	"TTC Lighthouse Door",
	"GV Sun Switch",
	"GV Star Hatch",
	"GV Kazooie Door",
	"GV Star Switch",
	"GV Empty Honeycomb Switch",
	"GV Kazooie Target",
	"Ancient Ones 1",
	"Ancient Ones 2",
	"Ancient Ones 3",
	"Ancient Ones 4",
	"Ancient Ones 5",
	"Jiggy Spawn (Green Jiggy Switch - Central)",
	"Green Jiggy Switch (Central)",
	"Conga Hard Throw Location",
	"Lockup",
	"Christmas Tree",
	"Boggy 1 (Dying?)",
	"Boggy Race Checkpoint 1 (Right)",
	"Boggy Race Checkpoint 2 (Right)",
	"Boggy Race Checkpoint 3 (Right)",
	"Boggy Race Checkpoint 4 (Right)",
	"Boggy Race Checkpoint 5 (Right)",
	"Boggy Race Checkpoint 6 (Right)",
	"Boggy Race Checkpoint 7 (Right)",
	"Boggy Race Checkpoint 8 (Right)",
	"Boggy Race Checkpoint 9 (Right)",
	"Boggy Race Checkpoint 10 (Right)",
	"Boggy Race Checkpoint 11 (Right)",
	"Boggy Race Checkpoint 12 (Right)",
	"Boggy Race Checkpoint 13 (Right)",
	"Boggy Race Checkpoint 14 (Right)",
	"Boggy Race Checkpoint 15 (Right)",
	"Boggy Race Checkpoint 16 (Right)",
	"Boggy Race Checkpoint 17 (Right)",
	"Boggy Race Checkpoint 18 (Right)",
	"Boggy Race Checkpoint 19 (Right)",
	"Boggy Race Checkpoint 20 (Right)",
	"Boggy Race Checkpoint 21 (Right)",
	"Boggy Race Checkpoint 22 (Right)",
	"Boggy Race Checkpoint 23 (Right)",
	"Boggy Race Checkpoint 24 (Right)",
	"Boggy Race Checkpoint 25 (Right)",
	"Boggy Race Checkpoint 26 (Right)",
	"Boggy Race Checkpoint 27 (Right)",
	"Boggy Race Checkpoint 28 (Right)",
	"Boggy Race Checkpoint 29 (Right)",
	"Boggy Race Checkpoint 30 (Right)",
	"Boggy Race Checkpoint 31 (Right)",
	"Boggy Race Checkpoint 32 (Right)",
	"Boggy Race Checkpoint 33 (Right)",
	"Boggy Race Checkpoint 34 (Right)",
	"Boggy Race Checkpoint 35 (Right)",
	"Boggy Race Checkpoint 36 (Right)",
	"Boggy Race Checkpoint 37 (Right)",
	"Boggy Race Checkpoint 38 (Right)",
	"Boggy Race Checkpoint 39 (Right)",
	"Boggy Race Checkpoint 1 (Left)",
	"Boggy Race Checkpoint 2 (Left)",
	"Boggy Race Checkpoint 3 (Left)",
	"Boggy Race Checkpoint 4 (Left)",
	"Boggy Race Checkpoint 5 (Left)",
	"Boggy Race Checkpoint 6 (Left)",
	"Boggy Race Checkpoint 7 (Left)",
	"Boggy Race Checkpoint 8 (Left)",
	"Boggy Race Checkpoint 9 (Left)",
	"Boggy Race Checkpoint 10 (Left)",
	"Boggy Race Checkpoint 11 (Left)",
	"Boggy Race Checkpoint 12 (Left)",
	"Boggy Race Checkpoint 13 (Left)",
	"Boggy Race Checkpoint 14 (Left)",
	"Boggy Race Checkpoint 15 (Left)",
	"Boggy Race Checkpoint 16 (Left)",
	"Boggy Race Checkpoint 17 (Left)",
	"Boggy Race Checkpoint 18 (Left)",
	"Boggy Race Checkpoint 19 (Left)",
	"Boggy Race Checkpoint 20 (Left)",
	"Boggy Race Checkpoint 21 (Left)",
	"Boggy Race Checkpoint 22 (Left)",
	"Boggy Race Checkpoint 23 (Left)",
	"Boggy Race Checkpoint 24 (Left)",
	"Boggy Race Checkpoint 25 (Left)",
	"Boggy Race Checkpoint 26 (Left)",
	"Boggy Race Checkpoint 27 (Left)",
	"Boggy Race Checkpoint 28 (Left)",
	"Boggy Race Checkpoint 29 (Left)",
	"Boggy Race Checkpoint 30 (Left)",
	"Boggy Race Checkpoint 31 (Left)",
	"Boggy Race Checkpoint 32 (Left)",
	"Boggy Race Checkpoint 33 (Left)",
	"Boggy Race Checkpoint 34 (Left)",
	"Boggy Race Checkpoint 35 (Left)",
	"Boggy Race Checkpoint 36 (Left)",
	"Boggy Race Checkpoint 37 (Left)",
	"Boggy Race Checkpoint 38 (Left)",
	"Boggy Race Checkpoint 39 (Left)",
	"Nibbly",
	"Colliwobble (With Empty Honeycomb)",
	"CCW Winter Button",
	"CCW Winter Door",
	"CCW Autumn Door",
	"CCW Summer Button",
	"CCW Summer Door",
	"Quarrie",
	"FP Sled 1",
	"FP Sled 2",
	"Banjo Walk",
	"RBB Empty Honeycomb Switch",
	"Secret X Barrel Top",
	"Reverb",
	"Activated Shock Jump Pad",
	"CC Tooth 1",
	"CC Tooth 2",
	"RBB Button 1",
	"RBB Button 2",
	"RBB Button 3",
	"RBB Whistle 1",
	"RBB Whistle 2",
	"RBB Whistle 3",
	"Grimlet",
	"Snorkel",
	"RBB Anchor & Chain",
	"Rareware Flag Pole",
	"Grille Chompa",
	"MM Demo Start",
	"Blue Egg Refill",
	"Red Feather Refill",
	"Gold Feather Refill",
	"CCW Spring Button",
	"Snarebear",
	"CCW Spring Door",
	"Toots",
	"Moggy",
	"Soggy",
	"Groggy",
	"FP Blue Present (Collectable)",
	"FP Blue Present Deliver Location",
	"FP Green Present (Collectable)",
	"FP Green Present Deliver Location",
	"FP Red Present (Collectable)",
	"FP Red Present Deliver Location",
	"Wozza 1",
	"Empty Honeycomb Spawn (GV Cactus/RBB Boat Room)",
	"Jinxy",
	"MMM Church Door Switch",
	"Croctus 1",
	"Croctus 2",
	"Croctus 3",
	"Croctus 4",
	"Croctus 5",
	"Green Jiggy Switch (Maze)",
	"Jiggy Spawn (Green Jiggy Switch - Maze)",
	"Note Door (50)",
	"Note Door (100)",
	"Note Door (260)",
	"Note Door (350)",
	"Note Door (450)",
	"Note Door (640)",
	"Note Door (765)",
	"Note Door (810)",
	"Note Door (828)",
	"Note Door (846)",
	"Note Door (864)",
	"Note Door (882)",
	"Witch Switch (MM)",
	"Witch Switch (MMM)",
	"Witch Switch (TTC)",
	"Witch Switch (RBB)",
	"GL Breakable Brick Wall",
	"MM Entrance Door",
	"RBB Entrance Door",
	"BGS Entrance Door",
	"TTC Entrance Chest Lid",
	"CC Entrance Iron Bars",
	"GL Breakable Statue Grate",
	"GL Breakable Statue Hat",
	"RBB Door To Engine Room",
	"Water Switch 1",
	"Water Switch 2",
	"Water Switch 3",
	"GV Entrance Door",
	"GL Gruntilda Head Breakable Glass Eye",
	"FP House (With Chimney)",
	"FP House (No Chimney)",
	"FP Frozen Mumbo Hut",
	"Christmas Present Stack",
	"GL Floor Yellow Cobweb",
	"GL Wall Yellow Cobweb",
	"CCW Entrance Door",
	"FP Entrance Door (Left)",
	"FP Entrance Door (Right)",
	"Witch Switch (CCW)",
	"Witch Switch (FP)",
	"Cauldron (TTC Puzzle -> FP Entrance)",
	"Cauldron (FP Entrance -> TTC Puzzle)",
	"Cauldron (FP Entrance -> RBB Entrance)",
	"Cauldron (RBB Entrance -> FP Entrance)",
	"Cauldron (Pipe Room -> CCW Entrance)",
	"Cauldron (CCW Entrance -> Pipe Room)",
	"Cauldron (FF Start -> 810 Note Door)",
	"Cauldron (810 Note Door -> FF Start)",
	"CCW Puzzle Switch",
	"Mumbo Transformation Pad (Termite)",
	"Mumbo Transformation Pad (Walrus)",
	"Mumbo Transformation Pad (Pumpkin)",
	"Mumbo Transformation Pad (Bee)",
	"RBB Warehouse Window",
	"GV Door Blocking SNS Egg",
	"Flying Pad Switch",
	"Temporary Flying Pad",
	"Shock Jump Pad Switch",
	"Witch Switch (GV)",
	"Witch Switch (BGS)",
	"Witch Switch (CC)",
	"Sharkfood Island",
	"Ice Key",
	"Yellow SnS Egg",
	"Green SnS Egg",
	"Pink SnS Egg",
	"Cyan SnS Egg",
	"RBB Ship Window",
	"Unknown (Jombo's Favorite)",
	"Tiptup",
	"Tiptup Choir Member 1",
	"Tiptup Choir Member 2",
	"Tiptup Choir Member 3",
	"Tiptup Choir Member 4",
	"Tiptup Choir Member 5",
	"Tiptup Choir Member 6",
	"King Sandybutt Jinxy Head 1",
	"King Sandybutt Jinxy Head 2",
	"King Sandybutt Jinxy Head 3",
	"King Sandybutt Jinxy Head Activate Area",
	"Beta Vent",
	"Whiplash",
	"CC Sawblades (Wonderwing Room)",
	"RBB Bell Buoy",
	"RBB Boat Room Row Boat",
	"Zubba Hive Honey Block",
	"Zubba (Roaming)",
	"CCW Beanstalk",
	"Big Clucker",
	"Eyrie",
	"CCW Caterpillar",
	"Boom Box (Extra Life)",
	"CCW Spring Nabnut",
	"CCW Summer Nabnut",
	"CCW Autumn Nabnut",
	"CCW Acorn",
	"CCW Spring Gnawty",
	"CCW Summer Gnawty",
	"Gnawty's Boulder",
	"Dingpot",
	"Gnawty's Den",
	"Lighthouse",
	"World Entrance Sign (MM)",
	"World Entrance Sign (TTC)",
	"World Entrance Sign (CC)",
	"World Entrance Sign (BGS)",
	"World Entrance Sign (FP)",
	"World Entrance Sign (GV)",
	"World Entrance Sign (MMM)",
	"World Entrance Sign (RBB)",
	"World Entrance Sign (CCW)",
	"MM Start Pad",
	"TTC Start Pad",
	"CC Start Pad",
	"BGS Start Pad",
	"GV Start Pad",
	"MMM Start Pad",
	"RBB Start Pad",
	"CCW Start Pad",
	"Door Of Grunty",
	"CCW Door To Whipcrack Room",
	"MMM Window (Small)",
	"MMM Window (Wide)",
	"MMM Window (Tall)",
	"Roysten",
	"Cuckoo Clock",
	"Boom Box",
	"Whipcrack",
	"CCW Winter Nabnut's Girlfriend",
	"CCW Winter Nabnut's Sheets",
	"CCW Winter Nabnut (Top Half)",
	"CCW Autumn/Winter Gnawty",
	"King Sandybutt's Tomb",
	"Blue Present (Delivered)",
	"Green Present (Delivered)",
	"Red Present (Delivered)",
	"Boggy 3 (Igloo?)",
	"Wozza 2",
	"FP Glass Tree Case",
	"Brentilda (GL 2)",
	"Brentilda (GL 3)",
	"Brentilda (GL BGS)",
	"Brentilda (GL 6)",
	"Brentilda (GL Lava)",
	"Brentilda (GL 5)",
	"Brentilda (GL 4)",
	"Brentilda (GL CCW)",
	"Brentilda (GL MMM)",
	"Brentilda (GL CC)",
	"Bee Swarm",
	"Limbo",
	"Mum-Mum",
	"Seaman Grublin",
	"Water Droplet Spawner",
	"FP Purple Ice Crystals",
	"FP Green Ice Crystals",
	"FP Blue Ice",
	"Boggy Race Start (Right Pole)",
	"Boggy Race Start Flag",
	"Boggy Race Finish Flag",
	"Boggy Race Rostrum",
	"Red Gruntling",
	"Boggy Race Start (Left Pole)",
	"Boggy Race Finish (Left Pole)",
	"Mumbo Sign 5",
	"Mumbo Sign 20",
	"Mumbo Sign 15",
	"Mumbo Sign 10",
	"Mumbo Sign 25",
	"Colliwobble",
	"Bawl",
	"Topper",
	"Gold Feather",
	"Banjo Placement When Learning Move",
	"Grublin Hood",
	"Bottles Mound (Beak Bomb)",
	"Bottles Mound (Eggs)",
	"Bottles Mound (Beak Buster)",
	"Bottles Mound (Talon Trot)",
	"Bottles Mound (Shock Spring Jump)",
	"Bottles Mound (Flight)",
	"Bottles Mound (Wonderwing)",
	"Bottles Mound (Stilt Stride)",
	"Bottles Mound (Turbo Talon Trot)",
	"Bottles Mound (Note Door)",
	"Boggy Race Finish (Right Pole)",
	"Chinker",
	"Dead Snarebear",
	"Loggo",
	"Scabby",
	"Portrait Chompa",
	"Fire Pain Object",
	"Portrait (Tree)",
	"Jigsaw Podium (MM)",
	"Jigsaw Podium (CC)",
	"Jigsaw Podium (BGS)",
	"Jigsaw Podium (FP)",
	"Jigsaw Podium (GV)",
	"Jigsaw Podium (MMM)",
	"Jigsaw Podium (RBB)",
	"Jigsaw Podium (CCW)",
	"Jigsaw Podium (Door Of Grunty)",
	"Jigsaw Podium (TTC)",
	"Blue Gruntling",
	"Black Gruntling",
	"Purple Tee-Hee",
	"Running Shoes",
	"Wading Boots",
	"Warp",
	"Camera Path/Release",
	"Enemy Boundary",
	"Camera Trigger",
	"Flag",
	"Magic Barrier Warning",
	"Magic Barrier Trigger",
	"Warp - MM Entering Mumbo's Hut",
	"Warp - MM Leaving Mumbo's Hut",
	"Warp - MM Entering Ticker's Tower (Bottom)",
	"Warp - MM Leaving Ticker's Tower (Bottom)",
	"Warp - MM Entering Ticker's Tower (Top)",
	"Warp - MM Leaving Ticker's Tower (Top)",
	"Warp - TTC Leaving Nipper",
	"Warp - TTC Entering Nipper",
	"Warp - TTC Entering Sandcastle",
	"Warp - TTC To Alcove Under Arch",
	"Warp - TTC To Top Of Mountain",
	"Warp - TTC Entering Salty Hippo (Top)",
	"Warp - TTC Entering Salty Hippo (Side)",
	"Warp - TTC To Lighthouse (Bottom)",
	"Warp - TTC To Lighthouse (Top)",
	"Warp - TTC Leaving Sandcastle",
	"Warp - TTC Leaving Salty Hippo (Top)",
	"Warp - TTC Leaving Salty Hippo (Side)",
	"Warp - CC Leaving Left Gill",
	"Warp - CC Leaving Right Gill",
	"Warp - CC Leaving Left Tooth",
	"Warp - CC Leaving Right Tooth",
	"Warp - CC Entering Belly From Gold Feather Room Entrance",
	"Warp - CC Entering Gold Feather Room",
	"Warp - CC Entering Mouth From Blowhole Room",
	"Warp - CC Entering Belly From Blowhole Room",
	"Warp - BGS Entering Mumbo's Skull",
	"Warp - BGS Leaving Mumbo's Skull",
	"Warp - BGS Entering Tanktup",
	"Warp - BGS Leaving Croc Right Nostril",
	"Warp - BGS Leaving Croc Left Nostril",
	"Warp - BGS Leaving Tanktup",
	"Warp - BGS Entering Croc Right Nostril",
	"Warp - BGS Entering Croc Left Nostril",
	"Warp - FP Entering Mumbo's Skull",
	"Warp - FP Entering Boggy's Igloo",
	"Warp - FP Entering Christmas Tree",
	"Warp - FP Leaving Mumbo's Skull",
	"Warp - FP Leaving Boggy's Igloo",
	"Warp - FP Leaving Christmas Tree",
	"Warp - FP Leaving Wozza's Cave",
	"Warp - FP Entering Wozza's Cave",
	"Warp - GV Entering Jinxy",
	"Warp - GV Leaving Jinxy",
	"Warp - GV Entering Matching Pyramid",
	"Warp - GV Entering King Sandybutt's Pyramid (Front)",
	"Warp - GV Entering Water Pyramid (Top)",
	"Warp - GV Entering Water Pyramid (Bottom)",
	"Warp - GV Entering Rupee's Pyramid",
	"Warp - GV Leaving Matching Pyramid",
	"Warp - GV Leaving King Sandybutt's Pyramid (Front)",
	"Warp - GV Leaving Water Pyramid (Bottom)",
	"Warp - GV Leaving Rupee's Pyramid",
	"Warp - GV Leaving King Sandybutt's Pyramid (Back)",
	"Warp - MMM Entering Dining Room (Bottom)",
	"Warp - MMM Entering Dining Room (Top)",
	"Warp - MMM Entering Well (Top)",
	"Warp - MMM Entering Tumblar's Shed",
	"Warp - MMM Entering Church",
	"Warp - MMM Entering Secret Church Room",
	"Warp - MMM Entering Gutter (Lower)",
	"Warp - MMM Entering Cellar",
	"Warp - MMM Entering Red Feather Room",
	"Warp - MMM Entering Blue Egg Room",
	"Warp - MMM Entering Note Room",
	"Warp - MMM Entering Empty Honeycomb Room",
	"Warp - MMM Entering Bedroom",
	"Warp - MMM Entering Bathroom",
	"Warp - MMM Leaving Dining Room (Bottom)",
	"Warp - MMM Leaving Well (Top)",
	"Warp - MMM Leaving Tumblar's Shed",
	"Warp - MMM Leaving Church",
	"Warp - MMM Leaving Secret Church Room",
	"Warp - MMM Leaving Gutter (Lower)",
	"Warp - MMM Leaving Cellar",
	"Warp - MMM Leaving Red Feather Room",
	"Warp - MMM Leaving Blue Egg Room",
	"Warp - MMM Leaving Empty Honeycomb Room",
	"Warp - MMM Leaving Bathroom",
	"Warp - MMM Leaving Bedroom",
	"Warp - MMM Leaving Note Room",
	"Warp - MMM Church Tower Upper",
	"Warp - MMM Church Tower Lower",
	"Warp - MMM Leaving Mumbo's Skull",
	"Warp - MMM Entering Mumbo's Skull",
	"Warp - MMM Leaving Well (Lower)",
	"Warp - MMM Entering Well (Lower)",
	"Warp - MMM Leaving Loggo",
	"Warp - RBB Entering Captain's Room",
	"Warp - RBB Entering Cabins",
	"Warp - RBB Entering Engin Room (Button)",
	"Warp - RBB Entering Kitchen",
	"Warp - RBB Entering Navigation Room",
	"Warp - RBB Entering Middle Pipe",
	"Warp - RBB Entering Engine Room (Main)",
	"Warp - RBB Entering Warehouse (Top)",
	"Warp - RBB Entering Boat Room",
	"Warp - RBB Entering Left Blue Container",
	"Warp - RBB Entering Middle Blue Container",
	"Warp - RBB Entering Right Blue Container",
	"Warp - RBB Leaving Captain's Room",
	"Warp - RBB Leaving Cabins",
	"Warp - RBB Leaving Engine Room (Button)",
	"Warp - RBB Leaving Kitchen",
	"Warp - RBB Leaving Navigation Room",
	"Warp - RBB Leaving Middle Pipe",
	"Warp - RBB Leaving Engine Room (Main)",
	"Warp - RBB Leaving Boat Room",
	"Warp - RBB Leaving Left Blue Container",
	"Warp - RBB Leaving Middle Blue Container",
	"Warp - RBB Leaving Right Blue Container",
	"Warp - RBB Leaving Boss Kaboom Box",
	"Warp - RBB Entering Boss Kaboom Box",
	"Warp - RBB Leaving Warehouse (Side)",
	"Warp - RBB Leaving Anchor Room",
	"Warp - RBB Entering Anchor Room",
	"Warp - CCW Spring Leaving Mumbo's Skull",
	"Warp - CCW Spring Entering Mumbo's Skull",
	"Warp - CCW Spring Leaving Nabnut's Door",
	"Warp - CCW Spring Entering Nabnut's Door",
	"Warp - CCW Spring Leaving Nabnut's Window",
	"Warp - CCW Spring Entering Nabnut's Window",
	"Warp - CCW Spring Leaving Whipcrack Room",
	"Warp - CCW Spring Entering Whipcrack Room",
	"Warp - CCW Spring Leaving Zubba Hive",
	"Warp - CCW Spring Entering Zubba Hive",
	"Warp - CCW Summer Leaving Mumbo's Skull",
	"Warp - CCW Summer Entering Mumbo's Skull",
	"Warp - CCW Summer Leaving Zubba Hive",
	"Warp - CCW Summer Entering Zubba Hive",
	"Warp - CCW Summer Leaving Nabnut's Door",
	"Warp - CCW Summer Entering Nabnut's Door",
	"Warp - CCW Summer Leaving Nabnut's Window",
	"Warp - CCW Summer Entering Nabnut's Window",
	"Warp - CCW Summer Leaving Whipcrack Room",
	"Warp - CCW Summer Entering Whipcrack Room",
	"Warp - CCW Autumn Leaving Mumbo's Skull",
	"Warp - CCW Autumn Entering Mumbo's Skull",
	"Warp - CCW Autumn Leaving Zubba's Hive",
	"Warp - CCW Autumn Entering Zubba's Hive",
	"Warp - CCW Autumn Leaving Nabnut's Door",
	"Warp - CCW Autumn Entering Nabnut's Door",
	"Warp - CCW Autumn Leaving Nabnut's Window",
	"Warp - CCW Autumn Entering Nabnut's Window",
	"Warp - CCW Autumn Leaving Nabnut's Attic 1",
	"Warp - CCW Autumn Entering Nabnut's Attic 1",
	"Warp - CCW Autumn Leaving Whipcrack Room",
	"Warp - CCW Autumn Entering Whipcrack Room",
	"Warp - CCW Winter Leaving Mumbo's Skull",
	"Warp - CCW Winter Entering Mumbo's Skull",
	"Warp - CCW Winter Leaving Nabnut's Window",
	"Warp - CCW Winter Entering Nabnut's Window",
	"Warp - CCW Winter Leaving Nabnut's Attic 1",
	"Warp - CCW Winter Entering Nabnut's Attic 1",
	"Warp - CCW Winter Leaving Nabnut's Attic 2",
	"Warp - CCW Winter Entering Nabnut's Attic 2",
	"Warp - CCW Winter Leaving Whipcrack Room",
	"Warp - CCW Winter Entering Whipcrack Room",
	"Warp - SM Leaving Banjo's House",
	"Warp - SM Entering Banjo's House",
	"Warp - SM Entering Gruntilda's Lair (No Cutscene)",
	"Warp - SM Entering Gruntilda's Lair (Cutscene)",
	"Ju-Ju: Egg Target",
	"Orange Pad 1: Splat Target",
	"Orange Pad 2: Splat Target",
	"Orange Pad 3: Splat Target",
	"Jiggy Flag - MM Atop Ticker's Tower",
	"Jiggy Flag - MM Mumbo's Hut Eye",
	"Jiggy Flag - MM Stonehenge",
	"Jiggy Flag - MM Slippery Slope",
	"Token Flag - MM Near Conga",
	"Token Flag - MM Stonehenge",
	"Token Flag - MM Under Mumbo's Hut Bridge",
	"Camera Path Trigger 1",
	"Camera Path Trigger 2",
	"Camera Path Trigger 3",
	"Camera Path Trigger 4",
	"Camera Path Trigger 5",
	"Camera Path Trigger 6",
	"Camera Path Trigger 7",
	"Camera Path Trigger 8",
	"Camera Path Trigger 9",
	"Camera Path Trigger 10",
	"Camera Release",
	"Path",
	"Entry Point 1",
	"Entry Point 2",
	"Entry Point 3",
	"Entry Point 18",
	"Crate On Water Script",
	"Entry Point 14",
	"Entry Point 17",
	"Entry Point 4",
	"Entry Point 5",
	"Entry Point 6",
	"Entry Point 7",
	"Entry Point 8",
	"Entry Point 9",
	"Entry Point 10",
	"Entry Point 11",
	"Entry Point 12",
	"Entry Point 13",
	"Entry Point 19",
	"Entry Point",
	"Where Banjo Throws Blubbers Gold Point 1",
	"Where Banjo Throws Blubbers Gold Point 2",
	"SM Beak Barge Tutorial Quarrie Counter Script",
	"SM To Lair 01B0",
	"SM Bridge Script",
	"SM Bridge Bottles 0349",
	"Bottles Leaving MM Entrance Without All Moves Script",
	"Bottles Leaving TTC Entrance Without All Moves Script",
	"Bottles Leaving CC Entrance Without All Moves Script",
	"Bottles Leaving BGS Entrance Without All Moves Script",
	"Bottles Leaving FP Entrance Without All Moves Script",
	"Bottles Leaving GV Entrance Without All Moves Script",
	"Mini Game Script",
	"SM Camera Tutorial Bottles 0379",
	"SM Attack Tutorial Bottles 0379",
	"TTC Water 0379",
	"Triggered Dialog",
	"SM Jump Tutorial Bottles Script",
	"SM Bridge Bottles Invisible Wall Script",
	"SM Bridge Bottles 03BD",
	"SM Bridge Bottles 03BE",
	"Cartoony Falling Noise Script",
])

CLEAR_SETUP_FILE_SIMPLE_LIST = array([
	"Red Feather",
	"MM Blue Flower",
	"MM Orange Yellow Flower",
	"MM Red Flower",
	"Icicle Stalactite",
	"Orange (2D)",
	"Seashell",
	"SM Yellow Flower",
	"SM Purple Flower",
	"SM Yellow/Blue Flower",
	"SM Blue Flower",
	"Fire Torch (2D)",
	"Gold Feather",
	"Seashell/Seaweed?",
	"Note",
	"Blue Egg",
	"Fire (2D)",
	"Conga's Tree",
	"TTC Tree",
	"RBB Toxic Barrel",
	"Shock Jump Pad (Always Active)",
	"TTC Crate",
	"RBB Pipe",
	"Flight Pad (Always Active)",
	"Dustbin",
	"Tumblar",
	"CCW Spring Leaf",
	"MMM RIP Tombstone",
	"GL Leaf Platform",
	"MMM Grave Plot 1",
	"MMM Grave Plot 2",
	"MMM Grave Plot 3",
	"SM Tree",
	"MM Tree",
	"CC Rings",
	"Banjos Kitchen Clothes",
	"BGS Mossy Log 1",
	"BGS Mossy Log 2",
	"GV Tree",
	"Cattail",
	"Banjos Kitchen",
	"Cattail (Small)",
	"Machine Room Booth",
	"Machine Room Console",
	"GV Wading Boots Platform",
	"Machine Room Door",
	"Banjos Bed",
])