MAP_SETUP_POINTER_DICT = {
    # Spiral Mountain
    "9780": "SM - Spiral Mountain",
    "9BD8": "SM - Banjo's House",
    # Mumbo's Mountain
    "9788": "MM - Mumbo's Mountain",
    "97D8": "MM - Termite Hill",
    "97E8": "MM - Mumbo's Skull",
    # Treasure Trove Cove
    "97B0": "TTC - Treasure Trove Cove",
    "97A0": "TTC - Blubber's Ship",
    "97A8": "TTC - Nipper's Shell",
    "97C8": "TTC - Sandcastle",
    "9BF0": "TTC - Sharkfood Island",
    # Clanker's Cavern
    "97D0": "CC - Clanker's Cavern",
    "9880": "CC - Inside Clanker - Witch Switch",
    "9888": "CC - Inside Clanker",
    "9890": "CC - Inside Clanker - Gold Feathers",
    # Bubblegloop Swamp
    "97E0": "BGS - Bubblegloop Swamp",
    "97F8": "BGS - Mr. Vile",
    "9800": "BGS - Tit Tup Chior",
    "99B0": "BGS - Mumbo's Skull",
    # Freezeezy Peak
    "98B0": "FP - Freezeezy Peak",
    "9980": "FP - Boggy's Igloo",
    "99B8": "FP - Mumbo's Skull",
    "9A10": "FP - Christmas Tree",
    "9B70": "FP - Wozza's Cave",
    # Gobi's Valley
    "9808": "GV - Gobi's Valley",
    "9810": "GV - Puzzle Room",
    "9818": "GV - King Sandybutt's Tomb",
    "9820": "GV - Water Room",
    "9828": "GV - Rupee",
    "9848": "GV - Jinxy",
    "9C08": "GV - Secret Blue Egg",
    # Mad Monster Mansion
    "9850": "MMM - Mad Monster Mansion",
    "9858": "MMM - Church",
    "9860": "MMM - Cellar",
    "9898": "MMM - Tumbler's Shed",
    "98A0": "MMM - Well",
    "98A8": "MMM - Dining Room",
    "98B8": "MMM - Egg Room",
    "98C0": "MMM - Note Room",
    "98C8": "MMM - Feather Room",
    "98D0": "MMM - Secret Church Room",
    "98D8": "MMM - Bathroom",
    "98E0": "MMM - Bedroom",
    "98E8": "MMM - Gold Feather Room",
    "98F0": "MMM - Drainpipe",
    "98F8": "MMM - Mumbo's Hut",
    "9BE0": "MMM - Septic Tank",
    # Rusty Bucket Bay
    "9900": "RBB - Rusty Bucket Bay",
    "9918": "RBB - Machine Room",
    "9920": "RBB - Big Fish Warehouse",
    "9928": "RBB - Boat Room",
    "9930": "RBB - First Blue Container",
    "9938": "RBB - Third Blue Container",
    "9940": "RBB - Sea-Grublin's Cabin",
    "9948": "RBB - Kaboom's Room",
    "9950": "RBB - Mini Kaboom's Room",
    "9958": "RBB - Kitchen",
    "9960": "RBB - Navigation Room",
    "9968": "RBB - Second Blue Container",
    "9970": "RBB - Captain's Room",
    "9BD0": "RBB - Anchor Room",
    # Click Clock Wood
    "9978": "CCW - Click Clock Wood",
    "9990": "Click Clock Woods - Spring",
    "9998": "Click Clock Woods - Summmer",
    "99A0": "Click Clock Woods - Fall",
    "99A8": "Click Clock Woods - Winter",
    "99C8": "CCW - Mumbo - Spring",
    "99D0": "CCW - Mumbo - Summer",
    "99D8": "CCW - Mumbo - Fall",
    "99E0": "CCW - Mumbo - Winter",
    "9A48": "CCW - Beehive - Summer",
    "9A50": "CCW - Beehive - Spring",
    "9A58": "CCW - Beehive - Fall",
    "9A68": "CCW - Nabnuts House - Spring",
    "9A70": "CCW - Nabnuts House - Summer",
    "9A78": "CCW - Nabnuts House - Fall",
    "9A80": "CCW - Nabnuts House - Winter",
    "9A88": "CCW - Nabnut's Attic - Winter",
    "9A90": "CCW - Nabnut's Attic - Fall",
    "9A98": "CCW - Nabnut's Attic 2 - Winter",
    "9AA0": "CCW - Slashing Weed Room - Spring",
    "9AA8": "CCW - Slashing Weed Room - Summer",
    "9AB0": "CCW - Slashing Weed Room - Fall",
    "9AB8": "CCW - Slashing Weed Room - Winter",
    # Gruntilda's Lair
    "9AC0": "GL - Floor 1",
    "9AC8": "GL - Floor 2",
    "9AD0": "GL - Floor 3",
    "9AD8": "GL - Pipe Room",
    "9AE0": "GL - TTC Entrance",
    "9AE8": "GL - Floor 5",
    "9AF0": "GL - Floor 6",
    "9AF8": "GL - CC Entrance",
    "9B00": "GL - Floor 4",
    "9B08": "GL - BGS Entrance",
    "9B18": "GL - Lava Room",
    "9B20": "GL - MMM Entrance",
    "9B28": "GL - Floor 6",
    "9B30": "GL - RBB Entrance",
    "9B38": "GL - MMM Puzzle",
    "9B40": "GL - Floor 7",
    "9B48": "GL - Coffin Room",
    "9B78": "GL - Path to Quiz show",
    "9BE8": "GL - Board Game",
    "9BF8": "GL - Boss", # This isn't a lair area, but whatever
    "9C10": "GL - Floor 8",
}

LAIR_SETUP_POINTER_DICT = {
    "9AC0": "GL - Floor 1",
    "9AC8": "GL - Floor 2",
    "9AD0": "GL - Floor 3",
    "9AD8": "GL - Pipe Room",
    "9AE0": "GL - TTC Entrance",
    "9AE8": "GL - Floor 5",
    "9AF0": "GL - Floor 6",
    "9AF8": "GL - CC Entrance",
    # "9B00": "GL - Floor 4", # I had this commented out for some reason, not sure why
    "9B08": "GL - BGS Entrance",
    "9B18": "GL - Lava Room",
    "9B20": "GL - MMM Entrance",
    "9B28": "GL - Floor 6",
    "9B30": "GL - RBB Entrance",
    "9B38": "GL - MMM Puzzle",
    "9B40": "GL - Floor 7",
    "9B48": "GL - Coffin Room",
    "9B78": "GL - Path to Quiz show",
    "9BE8": "GL - Board Game",
    "9BF8": "GL - Boss", # This isn't a lair area, but whatever
    "9C10": "GL - Floor 8",
    }

EXTRA_MAP_SETUP_POINTER_DICT = {
    # Cutscene
    "4D7910": "CS - Intro",
    "4D86A0": "CS - N Cube",
    "4D8A38": "CS - Beach Ending without 100 jiggies",
    "4F5060": "CS - Going through Grunty's hallway, then to door!",
    "4F5770": "CS - Banjo Sleeping",
    "4F5AD0": "CS - Tooty Running to Bottles",
    "4F6050": "CS - Unknown",
    "4F6860": "CS - Grunty running out door",
    "4F6F40": "CS - Tooty and Grunty in machines",
    "4F7540": "CS - You lose",
    "4F7DC0": "CS - Unknown",
    "4F7F40": "CS - Outside tower, thunder",
    "4F8218": "CS - Grunty rides outside her lair",
    "4F8BD8": "CS - Witch falling twords ground",
    "4F8E50": "CS - Grunty hits ground",
    "4F9368": "CS - Tooty's being captured",
    "4FBA28": "CS - Game Select",
    "4FC8E0": "CS - Mumbo's Barbaque",
    "4FD270": "CS - Beach Ending - Have 100 Jiggies",
    "4FDA00": "CS - Beach, about to show cast list",
    "4FE0D8": "CS - Beach, - after Pictures",
    "4FE3D0": "CS - Klungo Cant move Boulder without 100 Jiggies",
    "4FE638": "CS - Klungo Cant Move Boulder with 100 Jiggies",
    # Unknown
    "4F1FE8": "Unknown",
    "4F9970": "Test house",
}