MAP_SETUP_DICT = {
    # Spiral Mountain
    "4C4680": "SM - Spiral Mountain",
    "4F9DE0": "SM - Banjo's House",
    # Mumbo's Mountain
    "4C5A30": "MM - Mumbo's Mountain",
    "4CCD40": "MM - Termite Hill",
    "4CF158": "MM - Mumbo's Skull",
    # Treasure Trove Cove
    "4C7FD8": "TTC - Treasure Trove Cove",
    "4C7918": "TTC - Blubber's Ship",
    "4C7C38": "TTC - Nipper's Shell",
    "4CAD60": "TTC - Sandcastle",
    "4FAD70": "TTC - Sharkfood Island",
    # Clanker's Cavern
    "4CB028": "CC - Clanker's Cavern",
    "4D91C8": "CC - Inside Clanker - Witch Switch",
    "4D95E0": "CC - Inside Clanker",
    "4DA1B8": "CC - Inside Clanker - Gold Feathers",
    # Bubblegloop Swamp
    "4CD1E8": "BGS - Bubblegloop Swamp",
    "4CF410": "BGS - Mr. Vile",
    "4CF990": "BGS - Tit Tup Chior",
    "4E9F00": "BGS - Mumbo's Skull",
    # Freezeezy Peak
    "4DB118": "Freezeezy Peak - Main",
    "4DB118": "FP - Freezeezy Peak",
    "4E4820": "FP - Boggy's Igloo",
    "4EA168": "FP - Mumbo's Skull",
    "4EACA8": "FP - Christmas Tree",
    "4F6088": "FP - Wozza's Cave",
    # Gobi's Valley
    "4CFDF0": "GV - Gobi's Valley",
    "4D2450": "GV - Puzzle Room",
    "4D2778": "GV - King Sandybutt's Tomb",
    "4D3630": "GV - Water Room",
    "4D3A40": "GV - Rupee",
    "4D3F38": "GV - Jinxy",
    "4FBC70": "GV - Secret Blue Egg",
    # Mad Monster Mansion
    "4D44D8": "MMM - Mad Monster Mansion",
    "4D6988": "MMM - Church",
    "4D7358": "MMM - Cellar",
    "4DA480": "MMM - Tumbler's Shed",
    "4DA8E0": "MMM - Well",
    "4DAC80": "MMM - Dining Room",
    "4DE0E8": "MMM - Egg Room",
    "4DE300": "MMM - Note Room",
    "4DE4F0": "MMM - Feather Room",
    "4DE790": "MMM - Secret Church Room",
    "4DEA80": "MMM - Bathroom",
    "4DED00": "MMM - Bedroom",
    "4DF0C0": "MMM - Gold Feather Room",
    "4DF290": "MMM - Drainpipe",
    "4DF3E0": "MMM - Mumbo's Hut",
    "4FA110": "MMM - Septic Tank",
    # Rusty Bucket Bay
    "4DF660": "RBB - Rusty Bucket Bay",
    "4E13D8": "RBB - Machine Room",
    "4E1F50": "RBB - Big Fish Warehouse",
    "4E2440": "RBB - Boat Room",
    "4E26D8": "RBB - First Blue Container",
    "4E29C8": "RBB - Third Blue Container",
    "4E2C48": "RBB - Sea-Grublin's Cabin",
    "4E2ED8": "RBB - Kaboom's Room",
    "4E3238": "RBB - Mini Kaboom's Room",
    "4E35D0": "RBB - Kitchen",
    "4E3948": "RBB - Navigation Room",
    "4E3D30": "RBB - Second Blue Container",
    "4E4060": "RBB - Captain's Room",
    "4F9A08": "RBB - Anchor Room",
    # Click Clock Wood
    "4E4290": "CCW - Click Clock Wood",
    "4E4AA8": "Click Clock Woods - Spring",
    "4E5B98": "Click Clock Woods - Summmer",
    "4E73B0": "Click Clock Woods - Fall",
    "4E8C88": "Click Clock Woods - Winter",
    "4EA3A8": "CCW - Mumbo - Spring",
    "4EA5E8": "CCW - Mumbo - Summer",
    "4EA7D8": "CCW - Mumbo - Fall",
    "4EAA18": "CCW - Mumbo - Winter",
    "4EB258": "CCW - Beehive - Summer",
    "4EB538": "CCW - Beehive - Spring",
    "4EB880": "CCW - Beehive - Fall",
    "4EBB50": "CCW - Nabnuts House - Spring",
    "4EBD18": "CCW - Nabnuts House - Summer",
    "4EBEF0": "CCW - Nabnuts House - Fall",
    "4EC0A8": "CCW - Nabnuts House - Winter",
    "4EC278": "CCW - Nabnut's Attic - Winter",
    "4EC480": "CCW - Nabnut's Attic - Fall",
    "4EC5A8": "CCW - Nabnut's Attic 2 - Winter",
    "4EC748": "CCW - Slashing Weed Room - Spring",
    "4EC9D8": "CCW - Slashing Weed Room - Summer",
    "4ECC50": "CCW - Slashing Weed Room - Fall",
    "4ECEA0": "CCW - Slashing Weed Room - Winter",
    # Gruntilda's Lair
    "4ED0E8": "GL - Floor 1",
    "4ED9F8": "GL - Floor 2",
    "4EDFD8": "GL - Floor 3",
    "4EE738": "GL - Pipe Room",
    "4EEAA8": "GL - TTC Entrance",
    "4EF088": "GL - Floor 5",
    "4EF998": "GL - Floor 6",
    "4F0758": "GL - CC Entrance",
    #"4F0EC8": "GL - Floor 4",
    "4F15A0": "GL - BGS Entrance",
    "4F2180": "GL - Lava Room",
    "4F26A0": "GL - MMM Entrance",
    "4F2CE8": "GL - Floor 6",
    "4F32B0": "GL - RBB Entrance",
    "4F3B10": "GL - MMM Puzzle",
    "4F4348": "GL - Floor 7",
    "4F4D00": "GL - Coffin Room",
    "4F6700": "GL - Path to Quiz show",
    "4FA390": "GL - Board Game",
    "4FB1C0": "GL - Boss", # This isn't a lair area, but whatever
    "4FBEB0": "GL - Floor 8",
    # Cutscene
    "4D7910": "CS - Intro",
    "4D86A0": "CS - N Cube",
    "4D8A38": "CS - Beach Ending without 100 jiggies",
    "4F5060": "CS - Going through Grunty's hallway, then to door!",
    "4F5770": "CS - Banjo Sleeping",
    "4F5AD0": "CS - Tooty Running to Bottles",
    "4F6050": "CS - Unknown",
    "4F6860": "CS - Grunty running out door",
    "4F6F40": "CS - Tooty and Grunty in machines",
    "4F7540": "CS - You lose",
    "4F7DC0": "CS - Unknown",
    "4F7F40": "CS - Outside tower, thunder",
    "4F8218": "CS - Grunty rides outside her lair",
    "4F8BD8": "CS - Witch falling twords ground",
    "4F8E50": "CS - Grunty hits ground",
    "4F9368": "CS - Tooty's being captured",
    "4FBA28": "CS - Game Select",
    "4FC8E0": "CS - Mumbo's Barbaque",
    "4FD270": "CS - Beach Ending - Have 100 Jiggies",
    "4FDA00": "CS - Beach, about to show cast list",
    "4FE0D8": "CS - Beach, - after Pictures",
    "4FE3D0": "CS - Klungo Cant move Boulder without 100 Jiggies",
    "4FE638": "CS - Klungo Cant Move Boulder with 100 Jiggies",
    # Unknown
    "4F1FE8": "Unknown",
    "4F9970": "Test house",
}