################
### INCREASE ###
################

CHEATO_MORE_BLUE_EGGS_SPEECH_DICT = {
    "DBD8": { # 5CDA58
        0: "YOU CAN NOW CARRY MORE EGGS!",
        # 1: "THAT LOUSY CHEAT FOR EXTRA EGGS,",
        # 2: "WON'T HELP BEAR AND CHICKEN LEGS!",
    }
}

CHEATO_MORE_RED_FEATHERS_SPEECH_DICT = {
    "DBD8": { # 5CDAD0
        0: "YOU CAN NOW CARRY MORE RED FEATHERS!",
        # 1: "ALL MY FEATHERS, IT MAKES ME SICK,",
        # 2: "FLY TO ME, YOUR BUTT I'LL KICK!",
    }
}

CHEATO_MORE_GOLD_FEATHERS_SPEECH_DICT = {
    "DBD8": { # 5CDB50
        0: "YOU CAN NOW CARRY MORE GOLD FEATHERS!",
        1: "YOU NEEDED HELP, THAT'S NO DOUBT,",
        2: "BUT WITH PLENTY ATTACKS, YOU WILL RUN OUT!",
    }
}

###################
### NO INCREASE ###
###################

CHEATO_NO_INCREASE_BLUE_EGGS_SPEECH_DICT = {
    "DBD8": { # 5CDA58
        0: "YOU ALREADY HAD THE MAX EGGS. SORRY TO WASTE YOUR TIME.",
        # 1: "THAT LOUSY CHEAT FOR EXTRA EGGS,",
        # 2: "WON'T HELP BEAR AND CHICKEN LEGS!",
    }
}

CHEATO_NO_INCREASE_RED_FEATHERS_SPEECH_DICT = {
    "DBD8": { # 5CDAD0
        0: "YOU ALREADY HAD MAX RED FEATHERS. SORRY TO WASTE YOUR TIME.",
        # 1: "ALL MY FEATHERS, IT MAKES ME SICK,",
        # 2: "FLY TO ME, YOUR BUTT I'LL KICK!",
    }
}

CHEATO_NO_INCREASE_GOLD_FEATHERS_SPEECH_DICT = {
    "DBD8": { # 5CDB50
        0: "YOU ALREADY HAD MAX GOLD FEATHERS. SORRY TO WASTE YOUR TIME.",
        1: "YOU NEEDED HELP, THAT'S NO DOUBT,",
        2: "BUT WITH PLENTY ATTACKS, YOU WILL RUN OUT!",
    }
}