###############
### GENERAL ###
###############

SHORTEN_BOTTLES_SECRET_GAME_SPEECH_DICT = {
    "CF98": { # 5C9B60
        0: "GET THE SANDCASTLE JIGGY FIRST.",
        5: "TELL US NOW!",
        2: "JUST GET THE JIGGY FIRST!",
        7: "C'MON KAZOOIE, LET'S COME BACK LATER.",
    }
}

RANDOMIZER_INTRO_CUTSCENE_SPEECH_DICT = {
    "D150": { # 5CA8F8
        0: "DINGPOT, DINGPOT THAT I CLAIM,",
        1: "WHO HAS THE TOUGHEST GAME?",
        2: "WHY IT'S GRUNTY'S ANY DAY,",
        3: "HER LEVELS TAKE PLAYERS' LIVES AWAY...COUGH!",
        4: "YES YOU'RE RIGHT, I'M RATHER PROUD,",
        5: "MY WORLDS STAND ME OUT FROM THE CROWD!",
    },
    "D158": { # 5CA9B0
        0: "ERR...BUT MOST HAVE BEATEN IT...",
        1: "WHAT D'YOU MEAN, THIS CANNOT BE,",
        2: "THE LAST TWO WORLDS AREN'T EASY!",
        3: "PLAYERS MEMORIZED EVERY SPOT,",
        4: "THEY MOVE QUICKLY IN TALON TROT.",
        5: "NO NO NO YOU MUST BE MAD,",
        6: "HARDER GAMEPLAY CAN'T BE HAD!",
        7: "I THINK YOU'LL COME TO KNOW,",
        8: "THERE'S A ROUTE PLAYERS LIKE TO GO.",
    },
    # "D160": { # 5CAA88
        # 0: "WELL...WE'LL SEE ABOUT THAT!",
    # },
    "D168": { # 5CAAB8
        # 0: "HI THERE TOOTY, WHAT ARE YOU GOING TO DO TODAY?",
        3: "I'M GOING TO WATCH MY BROTHER SPEEDRUN THE GAME HAHA!",
    },
    "D170": { # 5CAB30
        1: "WAKE UP, I WANT TO GET UNDER 2 HOURS!",
    },
    "D178": { # 5CAB70
        0: "IF PLAYERS THINK THEY KNOW THE GAME WELL,",
        1: "I'LL CHANGE THE GAME WITH MY ýlRANDOMIZE SPELL!",
    },
    # "D180": { # 5CABD0
        # 0: "IS THAT YOUR BROTHER?",
        # 2: "UP THERE IN THE SKY!",
        # 5: "WHERE, MR. MOLE? I CAN'T SEE HIM...",
    # },
    "D188": { # 5CAC38
        1: "OH NO... THAT'S A BAD SEED!",
    },
    "D190": { # 5CAC70
        0: "ONCE I MOVE SOME THINGS AROUND,",
        1: "NO COLLECTABLES WILL BE FOUND!",
    },
    "D198": { # 5CACC0
        1: "PUT THAT BACK, YOU UGLY OLD HAG!",
    },
    "D1A0": { # 5CACF8
        0: "I'LL PUT THIS HERE, I'LL PUT THAT THERE,",
        1: "NOW THERE ARE NEW THINGS EVERYWHERE!",
    },
    "D1A8": { # 5CAD58
        0: "I CAN'T TELL, IS THIS WORLD RECORD PACE?",
    },
    # "D1B0": { # 5CAD98
        # 1: "BANJO! WAKE UP......NOW!",
    # },
    # "D1B8": { # 5CADC8
        # 1: "YAWN...WHAT DO YOU WANT KAZOOIE?",
    # },
    # "D1C0": { # 5CAE00
        # 1: "LET'S GET OUTSIDE, THERE'S TROUBLE!",
    # }
}

RANDOMIZER_ENTER_LAIR_CUTSCENE_SPEECH_DICT = {
    "D1C8": { # 5CAE38
        0: "WITH EVERYTHING JUMBLED, I'LL HAVE MORE TIME,",
        1: "TO STEAL YOUR BEAUTY AND BE AT MY PRIME!",
        10: "MY BROTHER BEAT YOU BEFORE,",
        11: "HE WILL BEAT YOU AGAIN!",
        3: "THERE IS NO GUIDE FOR RNG,",
        4: "I DOUBT HE EVEN OPENED THE README!",
        5: "NOW HURRY KLUNGO, IT'S TIME TO START,",
        6: "I WANT TO LOOK LIKE ALL MY FAN ART!",
        7: "YESSS MISSSTRESSS GRUNTY!",
        13: "THIS IS SO NOT WAHAY...",
    }
}

RANDOMIZER_BOTTLES_FIRST_WORLD_SPEECH_DICT = {
    "DA88": { # 5CC988
        0: "THAT'S IT! THE PICTURE'S COMPLETE AND THE DOOR TO <WORLD_NAME> IS OPEN!",
        # 1: "THAT WAS SUCH AN EASY FIT,",
        # 2: "THE OTHERS MAY JUST TEST YOUR WIT!",
    },
    "DA90": { # 5CCA10
        0: "IS THIS YOUR FIRST TIME PLAYING BANJO-KAZOOIE? GO GET A JIGGY, 4HEAD!",
    },
    "DA98": { # 5CCAA8
        0: "IS IT REALLY MUMBO'S MOUNTAIN? MAYBE THE PICTURES SHOULD BE UPDATED...",
    }
}

RANDOMIZER_ENOUGH_ITEMS_FOR_NOTE_DOOR_SPEECH_DICT = {
    "DA38": { # 5CC5C8
        0: "YIPPEE! YOU'VE COLLECTED ENOUGH <ITEM> TO BREAK THE FIRST <ITEM> DOOR SPELL!",
    }
}

RANDOMIZER_BOTTLES_TUTORIAL_SPEECH_DICT = {
    "CF90": { # 5C9AF8
        0: f"YOU'LL NEED <ITEM_1_COUNT> <ITEM_1> AND <ITEM_2_COUNT> <ITEM_2> TO REACH GRUNTY. PRESS B TO MOVE ON."
    }
}

###############
### OPTIONS ###
###############

GENERAL_REMOVE_BOTTLES_TUTORIAL_SPEECH_DICT = {
    "CF90": { # 5C9AF8
        0: "IF YOU'RE PLAYING THIS MOD, YOU WON'T NEED A TUTORIAL, SO PRESS B.",
    },
    "CF80": { # 5C9A18
        0: "THE TUTORIAL IS DISABLED, JUST PRESS B ALREADY!",
    }
}

#####################
### MISCELLANEOUS ###
#####################

GENERAL_FIRST_DEATH_SPEECH_DICT = {
    "DAA0": { # 5CCB08
        0: "TRYING TO GET THE GAME OVER SCREEN?!",
        1: "YOU ARE LIKE A PERVERTED TEEN!",
    }
}

BANJO_SOULIE_FIRST_DEATH_SPEECH_DICT = {
    "DAA0": { # 5CCB08
        0: "MOST OF MY QUIPS ARE RATHER SNIDE,",
        1: "BUT NOTHIN'S MORE HURTFUL THAN SIMPLY 'YOU DIED'!",
    }
}