INSIDE_JOKES = [
    ("PROUD OF YOURSELF? THINK YOU'RE A HERO?", "YOU'RE NOTHING BUT A LEADING ZERO!"),
    ("THERE'S A FEATURE YOU WANT TO SEE?", "REQUEST IT BEFORE VERSION 3!"),
]

SHOUTOUTS = [
    ("WANT TO MAKE A BK HACK?", "JOIN THE SERVER CALLED BANJO'S BACKPACK!"), # Banjo's Backpack (Approved)
    ("DON'T KNOW KURKO? THAT IS A CRIME!", "GO TRY OUT HIS JIGGIES OF TIME!"), # Kurko Mods (Approved)
    ("ONLY ONE LEVEL, BUT IT'S WORTH A BOAST!", "GO TRY OUT CUT-THROAT COAST!"), # Retro (Approved)
    ("YOU KNOW WHO DESERVES SOME RIBBONS?", "THAT ONE HACKER WE CALL MITTENZ!"), # Mittenz (Approved)
    ("NEED MORE BK? HERE'S AN EXPANSION!", "LOOK UP A MOD CALLED GRUNTY'S MANSION!"), # JacksonG13 (Approved)
    ("WANT A CHALLENGE WHERE YOU'RE SURE TO DIE?", "TRY FORT FUN BY THATCOWGUY!"), # ThatCowGuy (Approved)
    ("BELOVED BY ALL, HIS MUSIC IS DOPE!", "BIG SHOUTOUTS TO GRANT KIRKHOPE!"), # Grant Kirkhope
    ("YOU'RE OUT OF STYLE, COULDN'T BE LAMER!", "TRY WEARING A HAT, AND BEING A GAMER!"), # HatWearingGamer (Approved)
    ("YOU WANT TO SEE A MODDED TOOIE?", "THERE'S TONS OF FEATURES ON SNOOIE!"), # Wedarobi (Approved)
    ("YOU SEEM TO BE FULL OF RAGE.", "TRY CALMING DOWN LIKE MONOTONE GAGE!"), # Gage (Approved)
    ("BLAST THAT STUPID NINPALK SKIP!", "I NEED THAT CUTSCENE FOR TIME TO DIP!"), # Ninpalk (Approved)
    ("YOU HAVEN'T CLIPPED THROUGH THE FLOOR AT LEAST,", "IT SEEMS YOU'RE NO 8 BIT BEAST!"), # The8BitBeast (Approved)
    ("WANNA SEE RUNNERS AT A FAST PACE?", "CHECK OUT THE TWITCH CHANNEL BANJO RACE!"), # GarageDoorOpener (Approved)
    ("LOVEABLE STREAMER, HIS NAME IS DEDE,", "FULL OF CHARM AND HIS SOCKS ARE STINKY!"), # Dedelux (Approved)
    ("NADE, CHILE, TREP, AND MORE,", "ARE TOO AFRAID OF LOSING THEIR NOTE SCORE!"), # XBOX Players (3 Approved)
    ("EVEN WITH ALL OF THEIR SWEARS,", "THIS SHOUTOUT IS FOR MY DROP BEARS!"), # Australian Players
    ("GANON'S RANDO IS MADE TO A T,", "IT'S SOMETHING THIS RANDO ASPIRES TO BE!"), # OoT (2 Approved)
    ("K. ROOL'S RANDO, I WANT TO OUTDO!", "I MIGHT EVEN STEAL A FEATURE OR TWO..."), # DK64 (2 Approved)
    ("BOWSERS'S RANDO HAS ITEMS EVERYWHERE,", "MIGHT BE TOO DIFFICULT FOR A STUPID BEAR!"), # SM64
    ("WE GET IT, YOU CAN STOP, GOGO!", "THE GRUNTY'S REVENGE SCENE WILL NEVER GROW!"), # G0go (Approved)
    ("STOP FINDING GLITCHES IN MY GAME, GEEZ!", "TOO MANY HAVE BEEN FOUND BY CRONIKEYS!"), # Cronikeys
]

REFERENCES = [
    ("MARIO IS JUST A PLUMBER,", "BUT YOU STILL MANAGE TO BE DUMBER!"), # Mario
    ("IF KIRBY DECIDED TO SWALLOW YOU,", "THEN HE'D END UP STUPID TOO!"), # Kirby
    ("THAT'S ALL YOU HAVE, JUST YOU TWO?", "HALF THE SIZE OF THE DK CREW!"), # Donkey Kong
    ("TOO MANY ITEMS, I THINK NOT!", "YOU STILL NEED BOMBCHUS AND A HOOKSHOT!"), # Legend Of Zelda
    ("YOU LEARN NEW MOVES BUT ONLY USE FOUR,", "GET IN MY POKEBALL, I'LL TEACH YOU MORE!"), # Pokemon
    ("A BEAR AND A BIRD? NO ONE WANTS THAT!", "WE ALL WANT THE LIZARD AND BAT!"), # Yooka Laylee
    ("OVER THE FIREPLACE YOU SHALL STAY,", "WHILE I DRINK MY POTIONS ON A BAD FUR DAY!"), # Conker
    ("MY NEW TRICKS WILL MAKE YOU FOOLIES,", "JUST WAIT TIL YOU'RE GRABBED BY THE GHOULIES!"), # Grabbed By The Ghoulies
    ("WHEN I AM PRETTY, I'LL ATTRACT THE COLTS,", "WHILE YOU PLAY WITH YOUR NUTS AND BOLTS!"), # Nuts And Bolts
    ("YOU SUMMON KAZOOIE, IS THAT HER PREFERENCE?", "LOOKS A LOT LIKE A JOJO REFERENCE!"), # Jojo's Bizzare Adventure
    ("COULD YOU HAVE ANY SLOWER PACING?", "YOU SHOULD GO BACK TO DIDDY KONG RACING!"), # Diddy Kong Racing
    ("YOU LACK STYLE, BUT YOUR BACKPACK'S GOT DRIP.", "I'VE SEEN IT BEFORE IN AN AIRSHIP!"), # Among Us Reference
    ("YOU THINK YOU'RE GOOD, I THINK YOU'RE TRASH!", "LET'S SETTLE THIS IN SMASH!"), # Super Smash Bros
    ("YOU LACK WIT, YOU HAVE NO BRAIN!", "I'M SURPRISED YOU COULD FLY A PLANE!"), # Banjo Pilots
]

COMMUNITY_SUBMISSIONS = [
    ("HAVE YOU EVER TRIED HOLDING Z?", "SOME WACKY DRAGON USED IT TO GET PAST ME!"), # BlackDragonMax
    ("I DON'T LIKE SAND MUCH IN MY LAIR.", "IT'S COURSE AND ROUGH AND GETS EVERYWHERE!"), # HatWearingGamer
]

BANJO_SOULIE = [
    ("STRETCH OUT AN ARM, AND THEN THE OTHER ONE", "RAISE THEM TO THE SKY, AND PRAISE THE SUN!"), # Praise The Sun
    ("BEEN FEELING LONELY, I CAVED AND GOT TINDER,", "MATCHED WITH A CUTIE, THE LORD OF CINDER!"), # Gwyn, Lord Of Cinder
    ("TO REACH ME, YOU MUST GO HIGHER,", "WHY NOT JUST RELAX DOWN AT YOUR BONFIRE?"), # Bonfire
    ("BEATING ME IS AN IMPOSSIBLE TASK,", "YOU'RE GOING TO NEED MORE THAN ONE ESTUS FLASK!"), # Bonfire
]