BANJO_SOULIE_INTRO_BOTTLES_SPEECH_DICT = {
    "CE30": { # 5C85D8
        0: "WELCOME TO BANJO-SOULIE!",
        12: "THIS LOOKS LIKE BASE GAME, BUT WITH LESS HEALTH?",
        2: "THAT'S BECAUSE THE CREATOR SUCKS AT USING BLENDER.",
        14: "THERE ARE SO MANY TUTORIALS ON YOUTUBE, IT'S NOT EVEN HARD!",
        15: "SO WHAT IS DIFFERENT, BOTTLES?",
        4: "ENEMIES WILL DROP NOTES INSTEAD OF HEALTH, AND THERE ARE NO NOTES FLOATING AROUND.",
        17: "PFT ALL OF THE ENEMIES WERE EASY TO BEAT ANYWAY.",
        6: "THAT'S NOT ALL THAT'S DIFFERENT.",
        8: "SOME ENEMIES WILL HAVE LESS WEAKNESSES YOU'LL HAVE TO FIGURE OUT ON YOUR OWN.",
    }
}