ENTER_WORLD_WITH_MOVES = {
    "D9D8": { # 5CC1B0
        0: "BEAR AND BIRD FIND MOLE AND LEARN MOVES!",
    },
    "D9E0": { # 5CC210
        0: "REMEMBER CAP'N BLACKEYE? ME NEITHER!",
    },
    "D9E8": { # 5CC268
        0: "WHAT IS CLANKER ANYWAY? A SHARK? A WHALE?",
    },
    "D9F0": { # 5CC2B8
        0: "WHAT ARE YEW DOIN' IN MY SWAMP?!",
    },
    "D9F8": { # 5CC300
        0: "WHAT'S THIS? DROPS OF RAIN FROZEN INTO ICE CRYSTALS? I SHALL HARNESS THEIR ENERGY AND RULE THE WORLD!",
    },
    "DA00": { # 5CC350
        0: "I DON'T LIKE SAND. IT'S COARSE AND ROUGH AND IRRITATING AND IT GETS EVERYWHERE.",
    },
}

LEARN_ALL_WORLDS_MOVES = {
    "B908": { # 5C4350
        0: "EEKUM BOKUM!",
    },
    "AFD0": { # 5C2BC0
        0: "THE REAL LOOT BE THE SCALLYWAGS WE MADE ALONG THE WAY!",
    },
    "C850": { # 5C7818
        0: "IS ANYONE REALLY FREE WHEN CHAINED TO SOCIETY?",
    },
    "C2E8": { # 5C6358
        0: "IT SMELLS LIKE A VIDEO GAME CHAMPIONSHIP HERE...",
    },
    "BFE8": { # 5C5680
        0: "HAPPY WALRUS NOISES!",
    },
    "B2C8": { # 5C33E8
        0: "CHILI DOGS!"
    },
}

DIDNT_LEARN_WORLD_MOVES = {
    "DA08": { # 5CC390
        0: "WHAT'S THE MATTER? DON'T LIKE BACKTRACKING? GUESS YOU WON'T LIKE TOOIE...",
    },
    "DA10": { # 5CC3F8
        0: "THE CAMERAS GET FUNKY WHEN YOU LEARN A MOVE NOT FROM THAT LEVEL!",
    },
    "DA18": { # 5CC450
        0: "BABY SHARK DO DO DO DO DO DO!",
    },
    "DA20": { # 5CC4A8
        0: "THESE BOOTS ARE MADE FOR WALKIN, THAT'S JUST WHAT THEY'LL DO...",
    },
    "DA28": { # 5CC508
        0: "CHRISTMAS IS OVER, TIME FOR VALENTINES DAY DECORATIONS!",
    },
    "DA30": { # 5CC560
        0: "THERE ARE SOME REALLY COOL IMAGES ON THE WALLS IN THE MAZE!",
    },
}

MISC_MOVE_SPEECHES = {
    "B900": { # 5C42F0
        0: "LMAO CAUGHT YOU SLIPPIN' IN 4K!",
    },
}