import sys
sys.path.append(".")

from Data_Files.Enums.Logic_Enums import LOGIC_ENUMS

############################
### SPAWNED REQUIREMENTS ###
############################
# LEGEND:
# () = At least one of these
# [] = Must have all of these
# {} = Count of item

DEFAULT_SPAWNED_REQUIREMENTS_DICT = {
    # MM
    LOGIC_ENUMS.MM_JINJOS_JIGGY: [LOGIC_ENUMS.MM_BLUE_JINJO, LOGIC_ENUMS.MM_MAGENTA_JINJO, LOGIC_ENUMS.MM_YELLOW_JINJO, LOGIC_ENUMS.MM_GREEN_JINJO, LOGIC_ENUMS.MM_ORANGE_JINJO],
    LOGIC_ENUMS.MM_CHIMPY_JIGGY: [{LOGIC_ENUMS.ORANGE: 1}],
    LOGIC_ENUMS.MM_CONGA_JIGGY: [LOGIC_ENUMS.EGG_FIRING],
    LOGIC_ENUMS.MM_JUJU_JIGGY: [LOGIC_ENUMS.EGG_FIRING],
    LOGIC_ENUMS.MM_ORANGE_PADS_JIGGY: [],
    LOGIC_ENUMS.MM_HUTS_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER],
    # TTC
    LOGIC_ENUMS.TTC_JINJOS_JIGGY: [LOGIC_ENUMS.TTC_BLUE_JINJO, LOGIC_ENUMS.TTC_MAGENTA_JINJO, LOGIC_ENUMS.TTC_YELLOW_JINJO, LOGIC_ENUMS.TTC_GREEN_JINJO, LOGIC_ENUMS.TTC_ORANGE_JINJO],
    LOGIC_ENUMS.TTC_BLUBBER_JIGGY: {LOGIC_ENUMS.BLUBBERS_GOLD: 2},
    LOGIC_ENUMS.TTC_LITTLE_LOCKUP_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER],
    # CC
    LOGIC_ENUMS.CC_JINJOS_JIGGY: [LOGIC_ENUMS.CC_BLUE_JINJO, LOGIC_ENUMS.CC_MAGENTA_JINJO, LOGIC_ENUMS.CC_YELLOW_JINJO, LOGIC_ENUMS.CC_GREEN_JINJO, LOGIC_ENUMS.CC_ORANGE_JINJO],
    LOGIC_ENUMS.CC_FREE_CLANKER_JIGGY: [LOGIC_ENUMS.DIVE],
    LOGIC_ENUMS.CC_TOOTH_JIGGY: [LOGIC_ENUMS.EGG_FIRING],
    LOGIC_ENUMS.CC_RINGS_JIGGY: [LOGIC_ENUMS.DIVE],
    LOGIC_ENUMS.CC_SNIPPETS_JIGGY: [LOGIC_ENUMS.DIVE, (LOGIC_ENUMS.CLAW_SWIPE, LOGIC_ENUMS.ROLL_ATTACK, LOGIC_ENUMS.RAT_A_TAP_RAP, LOGIC_ENUMS.BEAK_BARGE, LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.EGG_FIRING)],
    # BGS
    LOGIC_ENUMS.BGS_JINJOS_JIGGY: [LOGIC_ENUMS.BGS_BLUE_JINJO, LOGIC_ENUMS.BGS_MAGENTA_JINJO, LOGIC_ENUMS.BGS_YELLOW_JINJO, LOGIC_ENUMS.BGS_GREEN_JINJO, LOGIC_ENUMS.BGS_ORANGE_JINJO],
    LOGIC_ENUMS.BGS_CENTRAL_SWITCH_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.TALON_TROT],
    LOGIC_ENUMS.BGS_MAZE_SWITCH_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.STILT_STRIDE],
    LOGIC_ENUMS.BGS_YELLOW_FLIBBIT_JIGGY: [(LOGIC_ENUMS.CLAW_SWIPE, LOGIC_ENUMS.ROLL_ATTACK, LOGIC_ENUMS.RAT_A_TAP_RAP, LOGIC_ENUMS.BEAK_BARGE, LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.EGG_FIRING)],
    LOGIC_ENUMS.BGS_HUTS_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.HIGH_JUMP, LOGIC_ENUMS.SHOCK_SPRING_JUMP],
    LOGIC_ENUMS.BGS_TANKTUP_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER],
    LOGIC_ENUMS.BGS_TIPTUP_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER],
    LOGIC_ENUMS.BGS_MR_VILE_JIGGY: [LOGIC_ENUMS.CROCODILE_BK],
    LOGIC_ENUMS.BGS_CROCTUS_JIGGY: [LOGIC_ENUMS.EGG_FIRING, LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.HIGH_JUMP, LOGIC_ENUMS.SHOCK_SPRING_JUMP],
    LOGIC_ENUMS.BGS_EGG_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.RAT_A_TAP_RAP, LOGIC_ENUMS.BEAK_BARGE, ([LOGIC_ENUMS.HIGH_JUMP, LOGIC_ENUMS.SHOCK_SPRING_JUMP], [LOGIC_ENUMS.CLIMB, LOGIC_ENUMS.TALON_TROT])],
    # FP
    LOGIC_ENUMS.FP_JINJOS_JIGGY: [LOGIC_ENUMS.FP_BLUE_JINJO, LOGIC_ENUMS.FP_MAGENTA_JINJO, LOGIC_ENUMS.FP_YELLOW_JINJO, LOGIC_ENUMS.FP_GREEN_JINJO, LOGIC_ENUMS.FP_ORANGE_JINJO],
    LOGIC_ENUMS.FP_SIR_SLUSH_JIGGY: [LOGIC_ENUMS.FLIGHT, LOGIC_ENUMS.BEAK_BOMB],
    LOGIC_ENUMS.FP_WOZZA_JIGGY: [LOGIC_ENUMS.WALRUS_BK],
    LOGIC_ENUMS.FP_SNOWMAN_BUTTONS_JIGGY: [LOGIC_ENUMS.FLIGHT, LOGIC_ENUMS.BEAK_BOMB],
    LOGIC_ENUMS.FP_BOGGY_1_JIGGY: [(LOGIC_ENUMS.FLIGHT, LOGIC_ENUMS.TALON_TROT)],
    LOGIC_ENUMS.FP_BOGGY_2_JIGGY: [LOGIC_ENUMS.FP_BOGGY_1_JIGGY, LOGIC_ENUMS.WALRUS_BK],
    LOGIC_ENUMS.FP_BOGGY_3_JIGGY: [LOGIC_ENUMS.FP_BOGGY_2_JIGGY, LOGIC_ENUMS.TURBO_TALON_TROT],
    LOGIC_ENUMS.FP_PRESENTS_JIGGY: [LOGIC_ENUMS.RED_PRESENT, LOGIC_ENUMS.BLUE_PRESENT, LOGIC_ENUMS.GREEN_PRESENT],
    LOGIC_ENUMS.FP_CHRISTMAS_TREE_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.CLIMB, LOGIC_ENUMS.FLAP_FLIP, LOGIC_ENUMS.FLIGHT, LOGIC_ENUMS.FEATHERY_FLAP],
    # GV
    LOGIC_ENUMS.GV_JINJOS_JIGGY: [LOGIC_ENUMS.GV_BLUE_JINJO, LOGIC_ENUMS.GV_MAGENTA_JINJO, LOGIC_ENUMS.GV_YELLOW_JINJO, LOGIC_ENUMS.GV_GREEN_JINJO, LOGIC_ENUMS.GV_ORANGE_JINJO],
    LOGIC_ENUMS.GV_GRABBA_JIGGY: [(LOGIC_ENUMS.TURBO_TALON_TROT, [LOGIC_ENUMS.TALON_TROT, LOGIC_ENUMS.FLIGHT, LOGIC_ENUMS.BEAK_BOMB])],
    LOGIC_ENUMS.GV_MATCHING_PUZZLE_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER],
    LOGIC_ENUMS.GV_ANCIENT_ONES_JIGGY: [(LOGIC_ENUMS.TALON_TROT, LOGIC_ENUMS.TURBO_TALON_TROT), LOGIC_ENUMS.FLIGHT],
    LOGIC_ENUMS.GV_GOBI_JIGGY: [(LOGIC_ENUMS.TALON_TROT, LOGIC_ENUMS.TURBO_TALON_TROT), (LOGIC_ENUMS.BEAK_BARGE, LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.BEAK_BOMB, LOGIC_ENUMS.EGG_FIRING, LOGIC_ENUMS.WONDERWING)],
    LOGIC_ENUMS.GV_TRUNKER_JIGGY: [LOGIC_ENUMS.GV_GOBI_JIGGY, LOGIC_ENUMS.BEAK_BUSTER],
    LOGIC_ENUMS.GV_GOBI_HONEYCOMB: [LOGIC_ENUMS.GV_TRUNKER_JIGGY, LOGIC_ENUMS.BEAK_BUSTER],
    LOGIC_ENUMS.GV_CACTUS_HONEYCOMB: [(LOGIC_ENUMS.TALON_TROT, LOGIC_ENUMS.TURBO_TALON_TROT), LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.FLIGHT],
    # MMM
    LOGIC_ENUMS.MMM_JINJOS_JIGGY: [LOGIC_ENUMS.MMM_BLUE_JINJO, LOGIC_ENUMS.MMM_MAGENTA_JINJO, LOGIC_ENUMS.MMM_YELLOW_JINJO, LOGIC_ENUMS.MMM_GREEN_JINJO, LOGIC_ENUMS.MMM_ORANGE_JINJO],
    LOGIC_ENUMS.MMM_MOTZAND_JIGGY: [LOGIC_ENUMS.FLAP_FLIP, LOGIC_ENUMS.HIGH_JUMP, LOGIC_ENUMS.SHOCK_SPRING_JUMP, LOGIC_ENUMS.BEAK_BUSTER],
    LOGIC_ENUMS.MMM_FLOWER_POTS: [LOGIC_ENUMS.EGG_FIRING],
    # RBB
    LOGIC_ENUMS.RBB_JINJOS_JIGGY: [LOGIC_ENUMS.RBB_BLUE_JINJO, LOGIC_ENUMS.RBB_MAGENTA_JINJO, LOGIC_ENUMS.RBB_YELLOW_JINJO, LOGIC_ENUMS.RBB_GREEN_JINJO, LOGIC_ENUMS.RBB_ORANGE_JINJO],
    LOGIC_ENUMS.RBB_WHISTLE_JIGGY: [LOGIC_ENUMS.BEAK_BUSTER],
    # CCW
    LOGIC_ENUMS.CCW_JINJOS_JIGGY: [LOGIC_ENUMS.CCW_BLUE_JINJO, LOGIC_ENUMS.CCW_MAGENTA_JINJO, LOGIC_ENUMS.CCW_YELLOW_JINJO, LOGIC_ENUMS.CCW_GREEN_JINJO, LOGIC_ENUMS.CCW_ORANGE_JINJO],
    LOGIC_ENUMS.CCW_GNAWTY_JIGGY: [LOGIC_ENUMS.DIVE, (LOGIC_ENUMS.EGG_FIRING, LOGIC_ENUMS.BEAK_BARGE, LOGIC_ENUMS.BEAK_BUSTER, LOGIC_ENUMS.WONDERWING)],
    LOGIC_ENUMS.CCW_EYRIE_JIGGY: [LOGIC_ENUMS.HIGH_JUMP, LOGIC_ENUMS.SHOCK_SPRING_JUMP, LOGIC_ENUMS.BEAK_BUSTER, {LOGIC_ENUMS.CATERPILLAR: 15}],
    LOGIC_ENUMS.CCW_NABNUT_JIGGY: [{LOGIC_ENUMS.ACORN: 15}],
    LOGIC_ENUMS.CCW_PLANT_JIGGY: [LOGIC_ENUMS.EGG_FIRING, LOGIC_ENUMS.BEAK_BUSTER],
    # GL
    LOGIC_ENUMS.GL_MM_WITCH_SWITCH_JIGGY: [LOGIC_ENUMS.MM_WITCH_SWITCH, LOGIC_ENUMS.TERMITE_BK],
    LOGIC_ENUMS.GL_TTC_WITCH_SWITCH_JIGGY: [LOGIC_ENUMS.TTC_WITCH_SWITCH, LOGIC_ENUMS.FLAP_FLIP],
    LOGIC_ENUMS.GL_CC_WITCH_SWITCH_JIGGY: [LOGIC_ENUMS.CC_WITCH_SWITCH, LOGIC_ENUMS.BEAK_BUSTER],
    LOGIC_ENUMS.GL_MMM_WITCH_SWITCH_JIGGY: [LOGIC_ENUMS.MMM_WITCH_SWITCH, (LOGIC_ENUMS.RAT_A_TAP_RAP, [LOGIC_ENUMS.FLIGHT, LOGIC_ENUMS.BEAK_BOMB], LOGIC_ENUMS.EGG_FIRING, LOGIC_ENUMS.WONDERWING)],
    LOGIC_ENUMS.GL_RBB_WITCH_SWITCH_JIGGY: [LOGIC_ENUMS.RBB_WITCH_SWITCH, LOGIC_ENUMS.WATER_LEVEL_2],
    LOGIC_ENUMS.GL_CCW_WITCH_SWITCH_JIGGY: [LOGIC_ENUMS.CCW_WITCH_SWITCH, LOGIC_ENUMS.BEE_BK],
    # OTHER STATIC PROGRESSION
    LOGIC_ENUMS.GL_SHED_GATE: [(LOGIC_ENUMS.RAT_A_TAP_RAP, LOGIC_ENUMS.EGG_FIRING, LOGIC_ENUMS.BEAK_BARGE, LOGIC_ENUMS.WONDERWING)],
    LOGIC_ENUMS.WATER_LEVEL_1: [LOGIC_ENUMS.GL_SHED_GATE, LOGIC_ENUMS.PUMPKIN_BK, LOGIC_ENUMS.BEAK_BUSTER],
    LOGIC_ENUMS.WATER_LEVEL_2: [LOGIC_ENUMS.WATER_LEVEL_1, LOGIC_ENUMS.BEAK_BUSTER, ([LOGIC_ENUMS.TALON_TROT], [LOGIC_ENUMS.HIGH_JUMP, LOGIC_ENUMS.FEATHERY_FLAP])],
}