# This Needs Verification :/
LOOPING_LEVEL_MUSIC_DICT = {
    0x01: "Final Battle Theme",
    0x02: "MM Main Theme",
    0x03: "FP Twinklies",
    0x05: "TTC Main Theme",
    0x06: "BGS Inside Tanktup/Vile",
    0x07: "CC Mutie Snippets",
    0x0D: "BGS Main Theme",
    0x0E: "MMM Background Wind",
    0x0F: "MMM Main Theme",
    0x10: "SM Main Theme",
    0x11: "TTC Seagulls",
    0x13: "TTC Inside Nipper",
    0x1B: "MM Tickers Tower",
    0x1C: "CC Main Theme",
    0x1E: "GL MM Theme",
    0x1F: "CC Inside Clanker",
    0x20: "GV Main Theme",
    0x21: "MMM Inside Mansion",
    0x22: "MMM Graveyard",
    0x23: "MMM Inside Church",
    0x24: "GV Inside Pyramid",
    0x28: "TTC Inside Sandcastle",
    0x29: "CCW Summer Main Theme",
    0x2A: "CCW Winter Main Theme",
    0x2E: "CCW Fall Main Theme",
    0x2F: "CCW Hub Room",
    0x33: "RBB Main Theme",
    0x35: "RBB Engine Room",
    0x41: "Mumbos Hut",
    0x44: "CCW Nabnuts Bedroom",
    0x45: "CCW Nabnuts Attic A",
    0x46: "CCW Whipcrack Room",
    0x4A: "RBB Inside Container",
    0x4C: "RBB Crewmate Cabin",
    0x50: "GL TTC Theme",
    0x51: "GL CCW Theme",
    0x52: "GL CC Theme",
    0x53: "GL BGS Theme",
    0x54: "GL GV Theme",
    0x56: "SM Bridge",
    0x59: "GL FP Theme",
    0x5A: "FP Igloo Sad",
    0x5B: "FP Igloo Happy",
    0x5D: "GL Lava Room",
    0x5E: "GL RBB Theme",
    0x5F: "CCW Spring Main Theme",
    0x60: "CCW Nabnut Attic B",
    0x63: "GL FF Theme",
    0x66: "FP Inside Wozzas Cave",
    0x6A: "MMM Tumblars Shed",
    0x6B: "FP Main Theme",
    0x6C: "CS Intro Tower",
    0x6D: "CCW Gnawtys House",
    0x6E: "Game Select",
    0x70: "MMM Inside Loggo",
    0x71: "Furnace Fun",
    0x74: "GL Door Of Grunty",
    0x80: "CS Game Over",
    0x83: "GV SNS Theme",
    0x84: "TTC Sharkfood Island",
    0x85: "FP SNS Theme",
    0x86: "MMM Cellar SNS",
    0x87: "MMM Loggo SNS",
    0x91: "CS Grunty Falling",
    0xA8: "Klungo By Fallen Gruntilda",
    0xAA: "CS Beach",
    }