from enum import IntEnum

class AREA_ENUM(IntEnum):

    #######################
    ### SPIRAL MOUNTAIN ###
    #######################

    ### SM MAIN 0x01

    SM_MAIN = 0x0101
    SM_HOUSE_ROOF = 0x0102
    SM_STUMP_UP_LEFT = 0x0103
    SM_STUMP_UP_MIDDLE = 0x0104
    SM_STUMP_UP_RIGHT = 0x0105
    SM_STUMP_DOWN_LEFT = 0x0106
    SM_STUMP_DOWN_MIDDLE = 0x0107
    SM_STUMP_DOWN_RIGHT = 0x0108
    SM_TREE_NEAR_HOUSE = 0x0109
    SM_TREE_NEAR_SWIM = 0x010A
    SM_TREE_NEAR_CLIMB = 0x010B
    SM_TREE_UNDER_BRIDGE = 0x010C
    SM_WATERFALL_LEDGE_1 = 0x010D
    SM_WATERFALL_LEDGE_2 = 0x010E
    SM_WATERFALL_LEDGE_3 = 0x010F
    SM_WATERFALL_ALCOVE = 0x0110
    SM_WATERFALL_POND = 0x0111
    SM_SPIRAL_MOAT = 0x0112

    ### SM BANJOS HOUSE 0x8C

    SM_BH_MAIN = 0x8C01

    #######################
    ### MUMBOS MOUNTAIN ###
    #######################

    ### MM MAIN 0x02

    MM_MAIN = 0x0201
    MM_PINK_JINJO = 0x0202
    MM_TREE_NEAR_PINK_JINJO = 0x0203
    MM_TREE_NEAR_BLUE_JINJO = 0x0204
    MM_BEEHIVE_HEXAGON = 0x0205
    MM_STONEHENGE_JIGGY = 0x0206
    MM_ATOP_STONEHENGE = 0x0207
    MM_CHIMPY_STUMP = 0x0208
    MM_EGG_FIRING = 0x0209
    MM_STUMP_TO_WITCH_SWITCH_1 = 0x020A
    MM_STUMP_TO_WITCH_SWITCH_2 = 0x020B
    MM_STUMP_TO_WITCH_SWITCH_3 = 0x020C
    MM_STUMP_WITH_WITCH_SWITCH = 0x020D
    MM_EMPTY_HONEYCOMB_ALCOVE = 0x020E
    MM_ATOP_HUTS = 0x020F
    MM_JUJU_PLATFORM = 0x0210
    MM_MUMBOS_SKULL_EYE = 0x0211
    MM_ATOP_MUMBOS_SKULL = 0x0212
    MM_ATOP_TICKERS_TOWER = 0x0213
    MM_BLUE_JINJO = 0x0214
    MM_UNDERWATER = 0x0215

    ### MM TICKERS TOWER 0x0C

    MM_TT_FLOOR_1 = 0x0C01
    MM_TT_SLOPE_LEDGE_1 = 0x0C02
    MM_TT_UPPER_FLOORS = 0x0C03

    ### MM INSIDE MUMBOS SKULL 0x0E

    MM_MS_MAIN = 0x0E01
    MM_MS_SHELF = 0x0E02

    ###########################
    ### TREASURE TROVE COVE ###
    ###########################

    # TTC MAIN 0x07

    TTC_MAIN = 0x0701
    TTC_UNDERWATER = 0x0702
    TTC_TREE_NEAR_ENTRANCE_LEFT = 0x0703
    TTC_TREE_NEAR_ENTRANCE_RIGHT = 0x0704
    TTC_SANDCASTLE_WATER_AREA = 0x0705
    TTC_TREE_NEAR_SANDCASTLE_1 = 0x0706
    TTC_TREE_NEAR_SANDCASTLE_2 = 0x0707
    TTC_TREE_NEAR_SANDCASTLE_3 = 0x0708
    TTC_TREE_NEAR_SANDCASTLE_4 = 0x0709
    TTC_TREE_NEAR_SANDCASTLE_5 = 0x070A
    TTC_TREE_NEAR_SANDCASTLE_6 = 0x070B
    TTC_SHOCK_JUMP_PAD_PLATFORM_1 = 0x070C
    TTC_SHOCK_JUMP_PAD_PLATFORM_2 = 0x070D
    TTC_SHOCK_JUMP_PAD_PLATFORM_3 = 0x070E
    TTC_SHOCK_JUMP_PAD_PLATFORM_4 = 0x070F
    TTC_SHOCK_JUMP_PAD_PLATFORM_5 = 0x0710
    TTC_SHOCK_JUMP_PAD_PLATFORM_6 = 0x0711
    TTC_SHOCK_JUMP_LEDGE_1 = 0x0712
    TTC_SHOCK_JUMP_LEDGE_2 = 0x0713
    TTC_SHOCK_JUMP_JIGGY_LEDGE = 0x0714
    TTC_TREE_NEAR_LOCKUPS_1 = 0x0715
    TTC_TREE_NEAR_LOCKUPS_2 = 0x0716
    TTC_TREE_NEAR_LOCKUPS_3 = 0x0717
    TTC_QUESTION_MARK_AREA = 0x0718
    TTC_PLATFORM_TO_FIRST_X_1 = 0x0719
    TTC_PLATFORM_TO_FIRST_X_2 = 0x071A
    TTC_FIRST_X_PLATFORM = 0x071B
    TTC_POOL_WITH_JIGGY = 0x071C
    TTC_POOL_WITH_TOKEN = 0x071D
    TTC_EXTRA_LIFE_POOL = 0x071E
    TTC_BLUBBERS_SHIP_DECK = 0x071F
    TTC_BLUBBERS_SHIP_CROWS_NEST = 0x0720
    TTC_LOCKUP_JIGGY_ALCOVE = 0x0721
    TTC_STAIRS_ALCOVE = 0x0722
    TTC_ATOP_MOUNTAIN_MAIN = 0x0723
    TTC_ATOP_MOUNTAIN_TREE_1 = 0x0724
    TTC_ATOP_MOUNTAIN_TREE_2 = 0x0725
    TTC_ATOP_MOUNTAIN_TREE_3 = 0x0726
    TTC_ATOP_MOUNTAIN_TREE_4 = 0x0727
    TTC_YELLOW_JINJO_TREE = 0x0728
    TTC_ATOP_MOUNTAIN_LEDGE_1 = 0x0729
    TTC_ATOP_MOUNTAIN_LEDGE_2 = 0x072A
    TTC_ATOP_MOUNTAIN_LEDGE_3 = 0x072B
    TTC_ATOP_MOUNTAIN_LEDGE_4 = 0x072C
    TTC_ATOP_MOUNTAIN_LEDGE_5 = 0x072D
    TTC_ATOP_MOUNTAIN_LEDGE_6 = 0x072E
    TTC_ATOP_MOUNTAIN_SHOCK_JUMP_LEDGE = 0x072F
    TTC_ATOP_MOUNTAIN_FROM_SHOCK_JUMP_LEDGE = 0x0730
    TTC_ATOP_MOUNTAIN_LIGHTHOUSE_BASE = 0x0731
    TTC_LIGHTHOUSE_UPPER = 0x0732
    TTC_ATOP_LIGHTHOUSE = 0x0733

    ### BLUBBERS SHIP 0x05

    TTC_BS_SIDE_UNDERWATER = 0x0501
    TTC_BS_SIDE_ABOVE_WATER = 0x0502
    TTC_BS_TOP_UNDERWATER = 0x0503
    TTC_BS_TOP_ABOVE_WATER = 0x0504

    ### NIPPERS 0x06

    TTC_INSIDE_NIPPERS_SHELL = 0x0601

    ### SANDCASTLE

    TTC_INSIDE_SANDCASTLE = ""

    ### SHARKFOOD ISLAND

    TTC_SI_MAIN = ""
    TTC_SI_ALCOVE_1 = ""
    TTC_SI_ALCOVE_2 = ""
    TTC_SI_ALCOVE_3 = ""
    TTC_SI_ALCOVE_4 = ""
    TTC_SI_ALCOVE_5 = ""
    TTC_SI_ALCOVE_6 = ""
    TTC_SI_ALCOVE_7 = ""
    TTC_SI_ALCOVE_8 = ""
    TTC_SI_ALCOVE_9 = ""
    TTC_SI_ALCOVE_10 = ""
    TTC_SI_ALCOVE_11 = ""
    TTC_SI_ALCOVE_12 = ""
    TTC_SI_ALCOVE_13 = ""
    TTC_SI_ALCOVE_14 = ""
    TTC_SI_ALCOVE_15 = ""
    TTC_SI_ALCOVE_16 = ""
    TTC_SI_LEDGE = ""
    TTC_SI_TOP = ""

    #######################
    ### CLANKERS CAVERN ###
    #######################

    CC_ENTRANCE_INSIDE_PIPE = ""
    CC_ENTRANCE_ATOP_PIPE = ""
    CC_ENTRANCE_LEFT_GOLD_FEATHER_PIPE = ""
    CC_ENTRANCE_RIGHT_GOLD_FEATHER_PIPE = ""
    CC_ENTRANCE_LEFT_CHOMPA_PIPE = ""
    CC_ENTRANCE_RIGHT_CHOMPA_PIPE_1 = ""
    CC_ENTRANCE_RIGHT_CHOMPA_PIPE_2 = ""
    CC_ENTRANCE_LADDER_PLATFORM = ""
    CC_YELLOW_JINJO = ""
    CC_ENTRANCE_UNREACHABLE_PIPE = ""
    CC_WATER_BELOW_ENTRANCE = ""
    CC_WATER_MAIN = ""
    CC_MUTIE_SNIPPETS = ""
    CC_GOLD_FEATHER_PLATFORM = ""
    CC_BEEHIVE_PLATFORM = ""
    CC_ALTERNATING_COLLECTABLES_ALCOVE_1 = ""
    CC_ALTERNATING_COLLECTABLES_ALCOVE_2 = ""
    CC_ALTERNATING_COLLECTABLES_ALCOVE_3 = ""
    CC_ALTERNATING_COLLECTABLES_ALCOVE_REST = ""
    CC_BLUE_EGGS_PLATFORM = ""
    CC_EXTRA_LIFE_PLATFORM = ""
    CC_HONEYCOMB_PIPE = ""
    CC_CLIMBABLE_PIPE_WITH_NOTES = ""
    CC_CLIMBABLE_PIPE_ALCOVE_1 = ""
    CC_CLIMBABLE_PIPE_ALCOVE_2 = ""
    CC_CLIMBABLE_PIPE_WITHOUT_NOTES = ""
    CC_ATOP_SLIDING_PIPE = ""
    CC_INSIDE_SLIDING_PIPE = ""
    CC_ATOP_HONEYCOMB_GRATE = ""
    CC_INSIDE_HONEYCOMB_GRATE = ""
    CC_UNDER_HONEYCOMB_GRATE_PLATFORM = ""
    CC_LEFT_TOOTH_PLATFORM = ""
    CC_RIGHT_TOOTH_PLATFORM = ""
    CC_CLANKERS_LEFT_FIN = ""
    CC_CLANKERS_RIGHT_FIN = ""
    CC_ATOP_CLANKER = ""
    CC_ABOVE_CLANKERS_HEAD_WALKWAY = ""
    CC_ABOVE_CLANKERS_HEAD_GRATE = ""
    CC_BEHIND_CLANKERS_TAIL_PLATFORM = ""
    CC_BEHIND_CLANKERS_TAIL_GRATE = ""
    CC_BEHIND_CLANKERS_TAIL_BETWEEN_GRATE_AND_PLATFORM = ""
    CC_BEHIND_CLANKERS_TAIL_LONG_PIPE = ""