#######################
### SPIRAL MOUNTAIN ###
#######################

### SM MAIN

SM_MAIN = ""
SM_HOUSE_ROOF = ""
SM_STUMP_UP_LEFT = ""
SM_STUMP_UP_MIDDLE = ""
SM_STUMP_UP_RIGHT = ""
SM_STUMP_DOWN_LEFT = ""
SM_STUMP_DOWN_MIDDLE = ""
SM_STUMP_DOWN_RIGHT = ""
SM_TREE_NEAR_HOUSE = ""
SM_TREE_NEAR_SWIM = ""
SM_TREE_NEAR_CLIMB = ""
SM_TREE_UNDER_BRIDGE = ""
SM_WATERFALL_LEDGE_1 = ""
SM_WATERFALL_LEDGE_2 = ""
SM_WATERFALL_LEDGE_3 = ""
SM_WATERFALL_ALCOVE = ""
SM_WATERFALL_POND = ""
SM_SPIRAL_MOAT = ""

### SM BANJOS HOUSE

SM_BH_MAIN = ""

#######################
### MUMBOS MOUNTAIN ###
#######################

### MM MAIN

MM_MAIN = ""
MM_PINK_JINJO = ""
MM_TREE_NEAR_PINK_JINJO = ""
MM_TREE_NEAR_BLUE_JINJO = ""
MM_BEEHIVE_HEXAGON = ""
MM_STONEHENGE_JIGGY = ""
MM_ATOP_STONEHENGE = ""
MM_CHIMPY_STUMP = ""
MM_EGG_FIRING = ""
MM_STUMP_TO_WITCH_SWITCH_1 = ""
MM_STUMP_TO_WITCH_SWITCH_2 = ""
MM_STUMP_TO_WITCH_SWITCH_3 = ""
MM_STUMP_WITH_WITCH_SWITCH = ""
MM_EMPTY_HONEYCOMB_ALCOVE = ""
MM_ATOP_HUTS = ""
MM_JUJU_PLATFORM = ""
MM_MUMBOS_SKULL_EYE = ""
MM_ATOP_MUMBOS_SKULL = ""
MM_ATOP_TICKERS_TOWER = ""
MM_BLUE_JINJO = ""
MM_UNDERWATER = ""

### MM TICKERS TOWER

MM_TT_FLOOR_1 = ""
MM_TT_SLOPE_LEDGE_1 = ""
MM_TT_UPPER_FLOORS = ""

### MM INSIDE MUMBOS SKULL

MM_MS_MAIN = ""
MM_MS_SHELF = ""

###########################
### TREASURE TROVE COVE ###
###########################

TTC_MAIN = ""
TTC_UNDERWATER = ""
TTC_TREE_NEAR_ENTRANCE_LEFT = ""
TTC_TREE_NEAR_ENTRANCE_RIGHT = ""
TTC_SANDCASTLE_WATER_AREA = ""
TTC_TREE_NEAR_SANDCASTLE_1 = ""
TTC_TREE_NEAR_SANDCASTLE_2 = ""
TTC_TREE_NEAR_SANDCASTLE_3 = ""
TTC_TREE_NEAR_SANDCASTLE_4 = ""
TTC_TREE_NEAR_SANDCASTLE_5 = ""
TTC_TREE_NEAR_SANDCASTLE_6 = ""
TTC_SHOCK_JUMP_PAD_PLATFORM_1 = ""
TTC_SHOCK_JUMP_PAD_PLATFORM_2 = ""
TTC_SHOCK_JUMP_PAD_PLATFORM_3 = ""
TTC_SHOCK_JUMP_PAD_PLATFORM_4 = ""
TTC_SHOCK_JUMP_PAD_PLATFORM_5 = ""
TTC_SHOCK_JUMP_PAD_PLATFORM_6 = ""
TTC_SHOCK_JUMP_LEDGE_1 = ""
TTC_SHOCK_JUMP_LEDGE_2 = ""
TTC_SHOCK_JUMP_JIGGY_LEDGE = ""
TTC_TREE_NEAR_LOCKUPS_1 = ""
TTC_TREE_NEAR_LOCKUPS_2 = ""
TTC_TREE_NEAR_LOCKUPS_3 = ""
TTC_QUESTION_MARK_AREA = ""
TTC_PLATFORM_TO_FIRST_X_1 = ""
TTC_PLATFORM_TO_FIRST_X_2 = ""
TTC_FIRST_X_PLATFORM = ""
TTC_POOL_WITH_JIGGY = ""
TTC_POOL_WITH_TOKEN = ""
TTC_EXTRA_LIFE_POOL = ""
TTC_BLUBBERS_SHIP_DECK = ""
TTC_BLUBBERS_SHIP_CROWS_NEST = ""
TTC_LOCKUP_JIGGY_ALCOVE = ""
TTC_STAIRS_ALCOVE = ""
TTC_ATOP_MOUNTAIN_MAIN = ""
TTC_ATOP_MOUNTAIN_TREE_1 = ""
TTC_ATOP_MOUNTAIN_TREE_2 = ""
TTC_ATOP_MOUNTAIN_TREE_3 = ""
TTC_ATOP_MOUNTAIN_TREE_4 = ""
TTC_YELLOW_JINJO_TREE = ""
TTC_ATOP_MOUNTAIN_LEDGE_1 = ""
TTC_ATOP_MOUNTAIN_LEDGE_2 = ""
TTC_ATOP_MOUNTAIN_LEDGE_3 = ""
TTC_ATOP_MOUNTAIN_LEDGE_4 = ""
TTC_ATOP_MOUNTAIN_LEDGE_5 = ""
TTC_ATOP_MOUNTAIN_LEDGE_6 = ""
TTC_ATOP_MOUNTAIN_SHOCK_JUMP_LEDGE = ""
TTC_ATOP_MOUNTAIN_FROM_SHOCK_JUMP_LEDGE = ""
TTC_ATOP_MOUNTAIN_LIGHTHOUSE_BASE = ""
TTC_LIGHTHOUSE_UPPER = ""
TTC_ATOP_LIGHTHOUSE = ""

### BLUBBERS SHIP

TTC_BS_SIDE_UNDERWATER = ""
TTC_BS_SIDE_ABOVE_WATER = ""
TTC_BS_TOP_UNDERWATER = ""
TTC_BS_TOP_ABOVE_WATER = ""

### NIPPERS

TTC_INSIDE_NIPPERS_SHELL = ""

### SANDCASTLE

TTC_INSIDE_SANDCASTLE = ""

### SHARKFOOD ISLAND

TTC_SI_MAIN = ""
TTC_SI_ALCOVE_1 = ""
TTC_SI_ALCOVE_2 = ""
TTC_SI_ALCOVE_3 = ""
TTC_SI_ALCOVE_4 = ""
TTC_SI_ALCOVE_5 = ""
TTC_SI_ALCOVE_6 = ""
TTC_SI_ALCOVE_7 = ""
TTC_SI_ALCOVE_8 = ""
TTC_SI_ALCOVE_9 = ""
TTC_SI_ALCOVE_10 = ""
TTC_SI_ALCOVE_11 = ""
TTC_SI_ALCOVE_12 = ""
TTC_SI_ALCOVE_13 = ""
TTC_SI_ALCOVE_14 = ""
TTC_SI_ALCOVE_15 = ""
TTC_SI_ALCOVE_16 = ""
TTC_SI_LEDGE = ""
TTC_SI_TOP = ""

#######################
### CLANKERS CAVERN ###
#######################

CC_ENTRANCE_INSIDE_PIPE = ""
CC_ENTRANCE_ATOP_PIPE = ""
CC_ENTRANCE_LEFT_GOLD_FEATHER_PIPE = ""
CC_ENTRANCE_RIGHT_GOLD_FEATHER_PIPE = ""
CC_ENTRANCE_LEFT_CHOMPA_PIPE = ""
CC_ENTRANCE_RIGHT_CHOMPA_PIPE_1 = ""
CC_ENTRANCE_RIGHT_CHOMPA_PIPE_2 = ""
CC_ENTRANCE_LADDER_PLATFORM = ""
CC_YELLOW_JINJO = ""
CC_ENTRANCE_UNREACHABLE_PIPE = ""
CC_WATER_BELOW_ENTRANCE = ""
CC_WATER_MAIN = ""
CC_MUTIE_SNIPPETS = ""
CC_GOLD_FEATHER_PLATFORM = ""
CC_BEEHIVE_PLATFORM = ""
CC_ALTERNATING_COLLECTABLES_ALCOVE_1 = ""
CC_ALTERNATING_COLLECTABLES_ALCOVE_2 = ""
CC_ALTERNATING_COLLECTABLES_ALCOVE_3 = ""
CC_ALTERNATING_COLLECTABLES_ALCOVE_REST = ""
CC_BLUE_EGGS_PLATFORM = ""
CC_EXTRA_LIFE_PLATFORM = ""
CC_HONEYCOMB_PIPE = ""
CC_CLIMBABLE_PIPE_WITH_NOTES = ""
CC_CLIMBABLE_PIPE_ALCOVE_1 = ""
CC_CLIMBABLE_PIPE_ALCOVE_2 = ""
CC_CLIMBABLE_PIPE_WITHOUT_NOTES = ""
CC_ATOP_SLIDING_PIPE = ""
CC_INSIDE_SLIDING_PIPE = ""
CC_ATOP_HONEYCOMB_GRATE = ""
CC_INSIDE_HONEYCOMB_GRATE = ""
CC_UNDER_HONEYCOMB_GRATE_PLATFORM = ""
CC_LEFT_TOOTH_PLATFORM = ""
CC_RIGHT_TOOTH_PLATFORM = ""
CC_CLANKERS_LEFT_FIN = ""
CC_CLANKERS_RIGHT_FIN = ""
CC_ATOP_CLANKER = ""
CC_ABOVE_CLANKERS_HEAD_WALKWAY = ""
CC_ABOVE_CLANKERS_HEAD_GRATE = ""
CC_BEHIND_CLANKERS_TAIL_PLATFORM = ""
CC_BEHIND_CLANKERS_TAIL_GRATE = ""
CC_BEHIND_CLANKERS_TAIL_BETWEEN_GRATE_AND_PLATFORM = ""
CC_BEHIND_CLANKERS_TAIL_LONG_PIPE = ""