from enum import IntEnum, auto

class BK_INSTRUMENT_ENUMS(IntEnum):
    
    @classmethod
    def get_debug_name(self, instrument):
        return instrument.name

    @classmethod
    def get_instrument_enum(self, instrument):
        return instrument.value

    MARIMBA = 1
    STRINGS = auto()
    JUNGLE_DRUM = auto()
    FENDER_THUMB_BASS = auto()
    CONGAS = auto()
    FLUTE = auto()
    CLARINET = auto()
    BARITONE_SAX = auto()
    TIMPANI = auto()
    TUBULAR_BELLS = auto()
    TAMBOURINE = auto()
    HARMONICA = auto()
    MARACAS = auto()
    TUBA = auto()
    CRICKETS_FROG = auto()
    BIRDS_CRICKETS = auto()
    TROMBONE = auto()
    TRUMPET = auto()
    PIATTI_CRASH_CYMBAL = auto()
    SNARE_SNARE_ROLLS = auto()
    FRENCH_HORNS = auto()
    PAN_FLUTE = auto()
    AFRICAN_LOG_DRUM = auto()
    JAZZ_KICK_DRUM = auto()
    HI_HATS = auto()
    CHIRP = auto()
    VILLAGE_CHANTS_MM = auto()
    GUIRO = auto()
    BASSOON = auto()
    CELESTE = auto()
    JUNGLE_FX = auto()
    MACHINE_FX = auto()
    WIND = auto()
    CREAK = auto()
    WOODPECKER = auto()
    BRUSHED_SNARE = auto()
    BUBBLES = auto()
    RUMBLE = auto()
    WAVES = auto()
    STEEL_STRING_GUITAR = auto()
    SEAGULLS = auto()
    FROGS = auto()
    BEES = auto()
    BANJO_INSTRUMENT = auto()
    JAW_HARP = auto()
    IRON_CLANG = auto()
    DONKEY = auto()
    FIDDLE = auto()
    KAZOO = auto()
    ANIMALS = auto()
    WOODBLOCK = auto()
    BANJO_GUH_HUH = auto()
    FLUTE_WITH_PITCHBEND = auto()
    CLARINET_2 = auto()
    THEREMIN = auto()
    CHURCH_ORGAN = auto()
    SPOOKY_FX = auto()
    MUTED_BASE = auto()
    LAUGH = auto()
    BASS_DRUM = auto()
    JINJO = auto()
    HUP_TWO_THREE_FOUR = auto()
    SHENAI = auto()
    TIMBALE = auto()
    DRIPS = auto()
    HARP = auto()
    BANJO_DOH = auto()
    CLICK_FINGER_SNAP = auto()
    BURP_FART = auto()
    PIZZICATO_STRINGS = auto()
    RBB_AMBIENCE = auto()
    MUMBO_VOX = auto()
    DRUM_KIT = auto()
    VIBRATO_STRINGS = auto()
    LAB_ELECTRICITY_FX = auto()
    CLAVE = auto()
    BELL = auto()
    PAN_FLUTE_2 = auto()
    TAIKO_DRUM = auto()
    STEEL_DRUM = auto()
    GAMEBOY_SQUARE_1 = auto()
    GAMEBOY_SQUARE_2 = auto()
    GAMEBOY_TRIANGLE = auto()
    GAMEBOY_WHITE_NOISE = auto()
    BAT = auto()

if __name__ == '__main__':
    for bk_instrument in BK_INSTRUMENT_ENUMS:
        print(BK_INSTRUMENT_ENUMS.get_debug_name(bk_instrument), BK_INSTRUMENT_ENUMS.get_instrument_enum(bk_instrument))