from enum import StrEnums, auto

class ITEM_DEBUG_STRINGS(StrEnums):
    # Items
    JIGGY = auto()
    EMPTY_HONEYCOMB = auto()
    MUMBO_TOKEN = auto()

    ORANGE = auto()
    BLUBBERS_GOLD = auto()
    RED_PRESENT = auto()
    BLUE_PRESENT = auto()
    GREEN_PRESENT = auto()
    ACORN = auto()
    CATERPILLAR = auto()

    # Jinjos
    GL_BLUE_JINJO = auto()
    GL_PINK_JINJO = auto()
    GL_YELLOW_JINJO = auto()
    GL_GREEN_JINJO = auto()
    GL_ORANGE_JINJO = auto()

    MM_BLUE_JINJO = auto()
    MM_PINK_JINJO = auto()
    MM_YELLOW_JINJO = auto()
    MM_GREEN_JINJO = auto()
    MM_ORANGE_JINJO = auto()

    TTC_BLUE_JINJO = auto()
    TTC_PINK_JINJO = auto()
    TTC_YELLOW_JINJO = auto()
    TTC_GREEN_JINJO = auto()
    TTC_ORANGE_JINJO = auto()

    CC_BLUE_JINJO = auto()
    CC_PINK_JINJO = auto()
    CC_YELLOW_JINJO = auto()
    CC_GREEN_JINJO = auto()
    CC_ORANGE_JINJO = auto()

    BGS_BLUE_JINJO = auto()
    BGS_PINK_JINJO = auto()
    BGS_YELLOW_JINJO = auto()
    BGS_GREEN_JINJO = auto()
    BGS_ORANGE_JINJO = auto()

    FP_BLUE_JINJO = auto()
    FP_PINK_JINJO = auto()
    FP_YELLOW_JINJO = auto()
    FP_GREEN_JINJO = auto()
    FP_ORANGE_JINJO = auto()

    GV_BLUE_JINJO = auto()
    GV_PINK_JINJO = auto()
    GV_YELLOW_JINJO = auto()
    GV_GREEN_JINJO = auto()
    GV_ORANGE_JINJO = auto()

    MMM_BLUE_JINJO = auto()
    MMM_PINK_JINJO = auto()
    MMM_YELLOW_JINJO = auto()
    MMM_GREEN_JINJO = auto()
    MMM_ORANGE_JINJO = auto()

    RBB_BLUE_JINJO = auto()
    RBB_PINK_JINJO = auto()
    RBB_YELLOW_JINJO = auto()
    RBB_GREEN_JINJO = auto()
    RBB_ORANGE_JINJO = auto()

    CCW_BLUE_JINJO = auto()
    CCW_PINK_JINJO = auto()
    CCW_YELLOW_JINJO = auto()
    CCW_GREEN_JINJO = auto()
    CCW_ORANGE_JINJO = auto()

    # Spawned Items
    MM_JINJOS_JIGGY = auto()
    MM_CHIMPY_JIGGY = auto()
    MM_CONGA_JIGGY = auto()
    MM_JUJU_JIGGY = auto()
    MM_ORANGE_PADS_JIGGY = auto()
    MM_HUTS_JIGGY = auto()

    TTC_JINJOS_JIGGY = auto()
    TTC_BLUBBER_JIGGY = auto()
    TTC_LITTLE_LOCKUP_JIGGY = auto()

    CC_JINJOS_JIGGY = auto()
    CC_FREE_CLANKER_JIGGY = auto()
    CC_TOOTH_JIGGY = auto()
    CC_RINGS_JIGGY = auto()
    CC_SNIPPETS_JIGGY = auto()

    BGS_JINJOS_JIGGY = auto()
    BGS_CENTRAL_SWITCH_JIGGY = auto()
    BGS_MAZE_SWITCH_JIGGY = auto()
    BGS_YELLOW_FLIBBIT_JIGGY = auto()
    BGS_HUTS_JIGGY = auto()
    BGS_TANKTUP_JIGGY = auto()
    BGS_TIPTUP_JIGGY = auto()
    BGS_MR_VILE_JIGGY = auto()
    BGS_CROCTUS_JIGGY = auto()
    BGS_EGG_JIGGY = auto()

    FP_JINJOS_JIGGY = auto()
    FP_SIR_SLUSH_JIGGY = auto()
    FP_WOZZA_JIGGY = auto()
    FP_SNOWMAN_BUTTONS_JIGGY = auto()
    FP_BOGGY_1_JIGGY = auto()
    FP_BOGGY_2_JIGGY = auto()
    FP_BOGGY_3_JIGGY = auto()
    FP_PRESENTS_JIGGY = auto()
    FP_TWINKLIES = auto()
    FP_CHRISTMAS_TREE_STAR = auto()
    FP_CHRISTMAS_TREE_JIGGY = auto()

    GV_JINJOS_JIGGY = auto()
    GV_GRABBA_JIGGY = auto()
    GV_MATCHING_PUZZLE_JIGGY = auto()
    GV_ANCIENT_ONES_JIGGY = auto()
    GV_GOBI_JIGGY = auto()
    GV_TRUNKER_JIGGY = auto()
    GV_GOBI_HONEYCOMB = auto()
    GV_CACTUS_HONEYCOMB = auto()

    MMM_JINJOS_JIGGY = auto()
    MMM_MOTZAND_JIGGY = auto()
    MMM_FLOWER_POTS = auto()

    RBB_JINJOS_JIGGY = auto()
    RBB_WHISTLE_JIGGY = auto()

    CCW_JINJOS_JIGGY = auto()
    CCW_GNAWTY_JIGGY = auto()
    CCW_EYRIE_JIGGY = auto()
    CCW_NABNUT_JIGGY = auto()
    CCW_PLANT_JIGGY = auto()

    GL_JINJOS_JIGGY = auto()
    GL_MM_WITCH_SWITCH_JIGGY = auto()
    GL_TTC_WITCH_SWITCH_JIGGY = auto()
    GL_CC_WITCH_SWITCH_JIGGY = auto()
    GL_MMM_WITCH_SWITCH_JIGGY = auto()
    GL_RBB_WITCH_SWITCH_JIGGY = auto()
    GL_CCW_WITCH_SWITCH_JIGGY = auto()