from enum import IntEnum, unique

@unique
class FILE_PROGRESSION_ENUMS(IntEnum):
    # WITCH SWITCH
    MM_WITCH_SWITCH = 0x18
    MMM_WITCH_SWITCH = 0x19
    TTC_WITCH_SWITCH = 0x1A
    RBB_WITCH_SWITCH = 0x1C
    CCW_WITCH_SWITCH = 0x46
    FP_WITCH_SWITCH = 0x47
    CC_WITCH_SWITCH = 0x9A
    BGS_WITCH_SWITCH = 0x9F
    GV_WITCH_SWITCH = 0xA0

    # WATER LEVELS
    WATER_LEVEL_1 = 0x22
    WATER_LEVEL_2 = 0x24
    WATER_LEVEL_3 = 0x26

    # CHEATO
    BLUE_EGGS_CODE_UNLOCKED = 0xAD
    RED_FEATHER_CODE_UNLOCKED = 0xAE
    GOLD_FEAHTER_CODE_UNLOCKED = 0xAF
    BLUE_EGG_CODE_USED = 0xBE
    RED_FEATHER_CODE_USED = 0xBF
    GOLD_FEATHER_CODE_USED = 0xC0

    # OBSTACLES
    GL_CRYPT_GATE = 0x85
    GL_GRATE_TO_RBB_PUZZLE = 0xC2
    GL_ICE_BALL_TO_CHEATO = 0xC3
    GL_STATUE_EYE = 0xC4
    GL_RAREWARE_BOX = 0xC5
    GL_JUMP_PAD_BUTTON = 0xC6
    GL_BRICKWALL_TO_BOOTS = 0xC8
    GL_BRICKWALL_TO_PAD_BUTTON = 0xC9
    GL_PINK_CAULDRON_WEB = 0xCA
    GL_FLIGHT_PAD_WEB = 0xCB
    GL_TEAL_CAULDRON_WEB = 0xCC
    GL_WATER_SWITCH_3_GRATE = 0xCD
    GL_MMM_RBB_PUZZLE_GRATE = 0xCE

    # CAULDRONS
    PINK_CAULDRON_1_ACTIVE = 0x49
    PINK_CAULDRON_2_ACTIVE = 0x4A
    TEAL_CAULDRON_1_ACTIVE = 0x4B
    TEAL_CAULDRON_2_ACTIVE = 0x4C
    RED_CAULDRON_1_ACTIVE = 0x4D
    RED_CAULDRON_2_ACTIVE = 0x4E
    UNUSED_CAULDRON_1_ACTIVE = 0x4F
    UNUSED_CAULDRON_2_ACTIVE = 0x50
    YELLOW_CAULDRON_1_ACTIVE = 0x51
    YELLOW_CAULDRON_2_ACTIVE = 0x52