from enum import IntEnum, unique

@unique
class MAP_ENUMS(IntEnum):
    
    @classmethod
    def get_debug_name(self, curr_map):
        return curr_map.name

    @classmethod
    def get_map_enum(self, curr_map):
        return curr_map.value[0]

    SM_MAIN = 0x01
    MM_MAIN = 0x02
    TTC_SALTY_HIPPO = 0x05
    TTC_NIPPER = 0x06
    TTC_MAIN = 0x07
    TTC_SANDCASTLE = 0x0A
    CC_MAIN = 0x0B
    MM_TICKERS = 0x0C
    BGS_MAIN = 0x0D
    MM_MUMBOS_SKULL = 0x0E
    BGS_VILE = 0x10
    BGS_TANKTUP = 0x11
    GV_MAIN = 0x12
    GV_MATCHING_PYRAMID = 0x13
    KING_SANDYBUTT = 0x14
    GV_WATER_PYRAMID = 0x15
    GV_RUBEE = 0x16
    GV_JINXY = 0x1A
    MMM_MAIN = 0x1B
    MMM_CHURCH = 0x1C
    MMM_CELLAR = 0x1D
    CC_CLANKER_BLOWHOLE = 0x21
    CC_CLANKER_MOUTH_BELLY = 0x22
    CC_CLANKER_WONDERWING = 0x23
    MMM_TUMBLAR = 0x24
    MMM_WELL = 0x25
    MMM_NAPPER = 0x26
    FP_MAIN = 0x27
    MMM_EGG_ROOM = 0x28
    MMM_NOTE_ROOM = 0x29
    MMM_RED_FEATHER_ROOM = 0x2A
    MMM_SECRET_ROOM = 0x2B
    MMM_LOGGO_ROOM = 0x2C
    MMM_BEDROOM = 0x2D
    MMM_HONEYCOMB_ROOM = 0x2E
    MMM_GUTTER = 0x2F
    MMM_MUMBOS_SKULL = 0x30
    RBB_MAIN = 0x31
    RBB_ENGINE_ROOM = 0x34
    RBB_BIG_FISH_WAREHOUSE = 0x35
    RBB_BOAT_ROOM = 0x36
    RBB_CHOMPA_CONTAINER = 0x37
    RBB_MINI_KABOOM_CONTAINER = 0x38
    RBB_CABIN_WINDOW = 0x39
    RBB_BOSS_KABOOM_BOSS = 0x3A
    RBB_MINI_KABOOM_PIPE = 0x3B
    RBB_KITCHEN_PIPE = 0x3C
    RBB_CONTROL_ROOM_WINDOW = 0x3D
    RBB_SEAMAN_GRUBLIN_CONTAINER = 0x3E
    RBB_CAPTAINS_ROOM_WINDOW = 0x3F
    CCW_MAIN = 0x40
    FP_IGLOO = 0x41
    CCW_SPRING_MAIN = 0x43
    CCW_SUMMER_MAIN = 0x44
    CCW_AUTUMN_MAIN = 0x45
    CCW_WINTER_MAIN = 0x46
    BGS_MUMBOS_SKULL = 0x47
    FP_MUMBOS_SKULL = 0x48
    CCW_SPRING_MUMBOS_SKULL = 0x4A
    CCW_SUMMER_MUMBOS_SKULL = 0x4B
    CCW_AUTUMN_MUMBOS_SKULL = 0x4C
    CCW_WINTER_MUMBOS_SKULL = 0x4D
    FP_TREE = 0x53
    CCW_SUMMER_ZUBBA = 0x5A
    CCW_SPRING_ZUBBA = 0x5B
    CCW_AUTUMN_ZUBBA = 0x5C
    CCW_SPRING_NABNUT = 0x5E
    CCW_SUMMER_NABNUT = 0x5F
    CCW_AUTUMN_NABNUT = 0x60
    CCW_WINTER_NABNUT = 0x61
    CCW_WINTER_ACORN_STORAGE = 0x62
    CCW_AUTUMN_FLOODED_ATTIC = 0x63
    CCW_WINTER_FLOODED_ATTIC = 0x64
    CCW_SPRING_WHIPCRACKS = 0x65
    CCW_SUMMER_WHIPCRACKS = 0x66
    CCW_AUTUMN_WHIPCRACKS = 0x67
    CCW_WINTER_WHIPCRACKS = 0x68
    GL_MM_ENTRANCE = 0x69
    GL_TTC_CC_PUZZLES = 0x6A
    GL_CCW_PUZZLE = 0x6B
    GL_PIPE_ROOM = 0x6C
    GL_TTC_ENTRANCE = 0x6D
    GL_GV_ENTRANCE = 0x6E
    GL_FP_ENTRANCE = 0x6F
    GL_CC_ENTRANCE = 0x70
    GL_GRUNTY_STATUE = 0x71
    GL_BGS_ENTRANCE = 0x72
    GL_GV_PUZZLE = 0x74
    GL_MMM_ENTRANCE = 0x75
    GL_WATER_THREE_SWITCH = 0x76
    GL_RBB_ENTRANCE = 0x77
    GL_MMM_RBB_PUZZLE = 0x78
    GL_CCW_ENTRANCE = 0x79
    GL_CRYPT = 0x7A
    FP_WOZZAS_CAVE = 0x7F
    GL_PATH_TO_FF = 0x80
    RBB_ANCHOR = 0x8B
    SM_BANJOS_HOUSE = 0x8C
    MMM_INSIDE_LOGGO = 0x8D
    GL_FF = 0x8E
    TTC_SHARKFOOD_ISLAND = 0x8F
    FINAL_BATTLE = 0x90
    GV_SNS_ROOM = 0x92
    GL_DOOR_OF_GRUNTY = 0x93