# WITCH SWITCH
MM_WITCH_SWITCH = "MM_WITCH_SWITCH"
TTC_WITCH_SWITCH = "TTC_WITCH_SWITCH"
CC_WITCH_SWITCH = "CC_WITCH_SWITCH"
BGS_WITCH_SWITCH = "BGS_WITCH_SWITCH"
FP_WITCH_SWITCH = "FP_WITCH_SWITCH"
GV_WITCH_SWITCH = "GV_WITCH_SWITCH"
MMM_WITCH_SWITCH = "MMM_WITCH_SWITCH"
RBB_WITCH_SWITCH = "RBB_WITCH_SWITCH"
CCW_WITCH_SWITCH = "CCW_WITCH_SWITCH"

# OTHER PROGRESSION
WATER_LEVEL_1 = "WATER_LEVEL_1"
WATER_LEVEL_2 = "WATER_LEVEL_2"
WATER_LEVEL_3 = "WATER_LEVEL_3"
GL_SHED_GATE = "GL_SHED_GATE"