from enum import IntEnum

class ROOM_ENUMS(IntEnum):
    SM_MAIN = 0x01
    SM_BANJOS_HOUSE = 0x8C

    GL_MM_ENTRANCE = 0x69
    GL_TTC_CC_PUZZLES = 0x6A
    GL_CCW_PUZZLE = 0x6B
    GL_TTC_ENTRANCE = 0x6D
    GL_CC_ENTRANCE = 0x70
    GL_CAULDRON_PIPE = 0x6C
    GL_FULL_GRUNTY_STATUE = 0x71
    GL_BGS_ENTRANCE = 0x72
    GL_GV_ENTRANCE = 0x6E
    GL_FP_ENTRANCE = 0x6F
    GL_GV_PUZZLE = 0x74
    GL_MMM_ENTRANCE = 0x75
    GL_MMM_SHED = 0x7A
    GL_640_NOTE_DOOR = 0x76
    GL_RBB_ENTRANCE = 0x77
    GL_MMM_PUZZLE = 0x78
    GL_CCW_ENTRANCE = 0x79
    GL_PATH_TO_FF = 0x80
    GL_FURNACE_FUN = 0x8E
    GL_FINAL_ROOM = 0x93

    MM_MAIN = 0x02
    MM_INSIDE_TICKERS_TOWER = 0x0C
    MM_MUMBOS_SKULL = 0x0E

    TTC_MAIN = 0x07
    TTC_NIPPERS = 0x06
    TTC_BLUBBERS = 0x05
    TTC_SANDCATLE = 0x0A
    TTC_SHARKFOOD_ISLAND = 0x8F

    CC_MAIN = 0x0B
    CC_BLOWHOLE = 0x23
    CC_BELLY_MOUTH = 0x22
    CC_GOLD_FEATHER = 0x23

    BGS_MAIN = 0x0D
    BGS_MR_VILE = 0x10
    BGS_TANKTUP = 0x11
    BGS_MUMBOS_SKULL = 0x47

    FP_MAIN = 0x27
    FP_IGLOO = 0x41
    FP_WOZZAS = 0x7F
    FP_TREE = 0x53
    FP_MUMBOS_SKULL = 0x48

    GV_MAIN = 0x12
    GV_MATCHING_PUZZLE = 0x13
    GV_WATER_PYRAMID = 0x15
    GV_RUBEE = 0x16
    GV_KING_SANDYBUTT = 0x14
    GV_JINXY = 0x1A
    GV_SNS = 0x92

    MMM_MAIN = 0x1B
    MMM_DINING_ROOM = 0x26
    MMM_FLOOR_1_ROOM_1_RED_FEATHERS = 0x2A
    MMM_FLOOR_1_ROOM_2_BLUE_EGGS = 0x28
    MMM_FLOOR_2_ROOM_1_HONEYCOMB = 0x2E
    MMM_FLOOR_2_ROOM_2_LOGGO = 0x2C
    MMM_FLOOR_3_ROOM_1_NOTES = 0x29
    MMM_FLOOR_3_ROOM_2_BEDROOM = 0x2D
    MMM_TUMBLAR = 0x24
    MMM_CHURCH = 0x1C
    MMM_SECRET_ROOM = 0x2B
    MMM_BASEMENT = 0x1D
    MMM_INSIDE_LOGGO = 0x8D
    MMM_INSIDE_GUTTER = 0x2F
    MMM_WELL = 0x25
    MMM_MUMBOS_SKULL = 0x30

    RBB_MAIN = 0x31
    RBB_CHUMP_WAREHOUSE = 0x0 # HALP
    RBB_ANCHOR = 0x8B
    RBB_BOAT = 0x0 # HALP
    RBB_BLUE_CONTAINER_1_CHOMPA = 0x35
    RBB_BLUE_CONTAINER_2_SEAMAN_GRUBLIN = 0x3B
    RBB_BLUE_CONTAINER_3_KABOOM_BOX = 0x38
    RBB_BOSS_KABOOM_BOSS = 0x3A
    RBB_ENGINE_ROOM = 0x34
    RBB_NAVIGATION = 0x0 # HALP
    RBB_CABINS = 0x39
    RBB_CAPTAIN_ROOM = 0x3F
    RBB_KITCHEN = 0x0 # HALP
    RBB_MIDDLE_PIPE = 0x0 # HALP
    RBB_BIG_FISH_WAREHOUSE = 0x0 # HALP
    RBB_BOAT_ROOM = 0x0 # HALP

    CCW_LOBBY = 0x40

    CCW_SPRING_MAIN = 0x43
    CCW_SPRING_NABNUT = 0x5E
    CCW_SPRING_ZUBBA = 0x5A
    CCW_SPRING_MUMBOS_SKULL = 0x4A
    CCW_SPRING_WHIPCRACKS = 0x65

    CCW_SUMMER_MAIN = 0x44
    CCW_SUMMER_NABNUT = 0x5F
    CCW_SUMMER_ZUBBA = 0x5B
    CCW_SUMMER_MUMBOS_SKULL = 0x4B
    CCW_SUMMER_WHIPCRACKS = 0x66

    CCW_AUTUMN_MAIN = 0x45
    CCW_AUTUMN_NABNUT = 0x60
    CCW_AUTUMN_ZUBBA = 0x5C
    CCW_AUTUMN_MUMBOS_SKULL = 0x4C
    CCW_AUTUMN_WHIPCRACKS = 0x67
    CCW_AUTUMN_FLOODED_ATTIC = 0x63

    CCW_WINTER_MAIN = 0x46
    CCW_WINTER_NABNUT = 0x61
    CCW_WINTER_MUMBOS_SKULL = 0x4D
    CCW_WINTER_WHIPCRACKS = 0x68
    CCW_WINTER_FLOODED_ATTIC = 0x64
    CCW_WINTER_ACORN_STORAGE = 0x62

    FINAL_BATTLE_ARENA = 0x90