from enum import IntEnum

class WARP_IDS(IntEnum):
    # SM_MAIN
    SM_MAIN_TO_SM_BANJOS_HOUSE = 0x118
    SM_MAIN_TO_GL_MM_ENTRANCE = 0x12D
    # SM_BANJOS_HOUSE
    SM_BANJOS_HOUSE_TO_SM_MAIN = 0x119

    # GL_MM_ENTRANCE
    GL_MM_ENTRANCE_TO_SM_MAIN = 0x11B
    GL_MM_ENTRANCE_TO_MM_MAIN = 0x09F
    GL_MM_ENTRANCE_TO_GL_TTC_CC_PUZZLES = 0x03F
    # GL_TTC_CC_PUZZLES
    GL_TTC_CC_PUZZLES_TO_GL_MM_ENTRANCE = 0x056
    GL_TTC_CC_PUZZLES_TO_GL_CCW_PUZZLE = 0x03D
    # GL_CCW_PUZZLE
    GL_CCW_PUZZLE_TO_GL_TTC_CC_PUZZLES = 0x03C
    GL_CCW_PUZZLE_TO_GL_TTC_ENTRANCE = 0x028
    GL_CCW_PUZZLE_TO_GL_PIPE_ROOM = 0x03B
    GL_CCW_PUZZLE_TO_GL_CC_ENTRANCE = 0x025
    GL_CCW_PUZZLE_TO_GL_GRUNTY_STATUE = 0x023
    # GL_PIPE_ROOM
    GL_PIPE_ROOM_TO_GL_CCW_PUZZLE = 0x03A
    # GL_TTC_ENTRANCE
    GL_TTC_ENTRANCE_TO_GL_CCW_PUZZLE = 0x027
    GL_TTC_ENTRANCE_TO_TTC_MAIN = 0x00C
    # GL_CC_ENTRANCE
    GL_CC_ENTRANCE_TO_GL_CCW_PUZZLE = 0x026
    GL_CC_ENTRANCE_TO_CC_MAIN = 0x00D
    # GL_GRUNTY_STATUE
    GL_GRUNTY_STATUE_TO_GL_CCW_PUZZLE = 0x022
    GL_GRUNTY_STATUE_TO_GL_BGS_ENTRANCE = 0x101
    GL_GRUNTY_STATUE_TO_GL_GV_ENTRANCE = 0x057
    # GL_BGS_ENTRANCE
    GL_BGS_ENTRANCE_TO_BGS_MAIN = 0x100
    # GL_GV_ENTRANCE
    GL_GV_ENTRANCE_TO_GL_GRUNTY_STATUE_NOTE_DOOR = 0x03E
    GL_GV_ENTRANCE_TO_GL_GRUNTY_STATUE_WITCH_SWITCH = 0x115
    GL_GV_ENTRANCE_TO_GL_FP_ENTRANCE = 0x055
    GL_GV_ENTRANCE_TO_GV_MAIN = 0x00F
    # GL_FP_ENTRANCE
    GL_FP_ENTRANCE_TO_FP_MAIN = 0x073
    GL_FP_ENTRANCE_TO_GL_GV_ENTRANCE = 0x054
    GL_FP_ENTRANCE_TO_GL_GV_PUZZLE = 0x103
    GL_FP_ENTRANCE_TO_GL_WATER_THREE_SWITCH = 0x105
    # GL_GV_PUZZLE
    GL_GV_PUZZLE_TO_GL_FP_ENTRANCE = 0x104
    GL_GV_PUZZLE_TO_GL_MMM_ENTRANCE = 0102
    # GL_MMM_ENTRANCE
    GL_MMM_ENTRANCE_TO_GL_GV_PUZZLE = 0x0F1
    GL_MMM_ENTRANCE_TO_GL_SHED = 0x0FE
    GL_MMM_ENTRANCE_TO_MMM_MAIN = 0x010
    # GL_SHED
    GL_SHED_TO_GL_MMM_ENTRANCE = 0x0FF
    # GL_WATER_THREE_SWITCH
    GL_WATER_THREE_SWITCH_TO_GL_FP_ENTRANCE = 0x10C
    GL_WATER_THREE_SWITCH_TO_GL_RBB_ENTRANCE = 0x109
    GL_WATER_THREE_SWITCH_TO_GL_CCW_ENTRANCE_NOTE_DOOR = 0x10A
    GL_WATER_THREE_SWITCH_TO_GL_CCW_ENTRANCE_TOKEN = 0x10B
    # GL_RBB_ENTRANCE
    GL_RBB_ENTRANCE_TO_GL_WATER_THREE_SWITCH = 0x108
    GL_RBB_ENTRANCE_TO_GL_MMM_PUZZLE = 0x113
    GL_RBB_ENTRANCE_TO_GL_RBB_PUZZLE = 0x114
    GL_RBB_ENTRANCE_TO_RBB_MAIN = 0x011
    # GL_MMM_PUZZLE
    GL_MMM_PUZZLE_TO_GL_RBB_ENTRANCE = 0x039
    # GL_RBB_PUZZLE
    GL_RBB_PUZZLE_TO_GL_RBB_ENTRANCE = 0x038
    # GL_CCW_ENTRANCE
    GL_CCW_ENTRANCE_TO_GL_WATER_THREE_SWITCH_NOTE_DOOR = 0x107
    GL_CCW_ENTRANCE_TO_GL_WATER_THREE_SWITCH_TOKEN = 0x106
    GL_CCW_ENTRANCE_TO_GL_PATH_TO_FF = 0x117
    GL_CCW_ENTRANCE_TO_CCW_MAIN = 0x122
    # GL_PATH_TO_FF
    GL_PATH_TO_FF_TO_GL_CCW_ENTRANCE = 0x116
    # GL_FF
    GL_FF_TO_GL_DOOR_OF_GRUNTY = 0x077
    # GL_DOOR_OF_GRUNTY
    GL_DOOR_OF_GRUNTY_TO_GL_FF = 0x078
    GL_DOOR_OF_GRUNTY_TO_FINAL_BATTLE = 0x074

    # MM_MAIN
    # MM_MAIN_TO_GL_MM_ENTRANCE = 0x0
    MM_MAIN_TO_MM_MUMBOS_SKULL = 0x016
    MM_MAIN_TO_MM_LOWER_TICKERS = 0x018
    MM_MAIN_TO_MM_UPPER_TICKERS = 0x01A
    MM_MUMBOS_SKULL_TO_MM_MAIN = 0x017
    MM_LOWER_TICKERS_TO_MM_MAIN = 0x019
    MM_UPPER_TICKERS_TO_MM_MAIN = 0x01B

    # TTC_MAIN
    # TTC_MAIN_TO_GL_TTC_ENTRANCE = 0x0
    TTC_MAIN_TO_TTC_SANDCASTLE = 0x06B
    TTC_MAIN_TO_TTC_NIPPER = 0x047
    TTC_MAIN_TO_TTC_SALTY_HIPPO_SIDE = 0x06F
    TTC_MAIN_TO_TTC_SALTY_HIPPO_TOP = 0x06E
    # TTC_MAIN_TO_TTC_SHARKFOOD_ISLAND = 0x0
    TTC_ALCOVE_LOWER_TO_TTC_ALCOVE_UPPER = 0x06D
    TTC_ALCOVE_UPPER_TO_TTC_ALCOVE_LOWER = 0x06C
    TTC_LIGHTHOUSE_LOWER_TO_TTC_LIGHTHOUSE_UPPER = 0x071
    TTC_LIGHTHOUSE_UPPER_TO_TTC_LIGHTHOUSE_LOWER = 0x070
    TTC_SANDCASTLE_TO_TTC_MAIN = 0x072
    TTC_NIPPER_TO_TTC_MAIN = 0x00B
    TTC_SALTY_HIPPO_SIDE_TO_TTC_MAIN = 0x076
    TTC_SALTY_HIPPO_TOP_TO_TTC_MAIN = 0x075
    # TTC_SHARKFOOD_ISLAND_TO_TTC_MAIN = 0x0F9

    # CC_MAIN
    # CC_MAIN_TO_GL_CC_ENTRANCE = 0x0
    CC_MAIN_TO_CC_CLANKER_BLOWHOLE = 0x0
    CC_MAIN_TO_CC_CLANKER_LEFT_TOOTH = 0x0
    CC_MAIN_TO_CC_CLANKER_RIGHT_TOOTH = 0x0
    CC_MAIN_TO_CC_CLANKER_LEFT_GILL = 0x0
    CC_MAIN_TO_CC_CLANKER_RIGHT_GILL = 0x0
    CC_CLANKER_BLOWHOLE_TO_CC_CLANKER_MOUTH = 0x09D
    CC_CLANKER_BLOWHOLE_TO_CC_CLANKER_BELLY = 0x09C
    CC_CLANKER_BELLY_TO_CC_CLANKER_WONDERWING = 0x09E
    CC_CLANKER_LEFT_TOOTH_TO_CC_MAIN = 0x031
    CC_CLANKER_RIGHT_TOOTH_TO_CC_MAIN = 0x032
    CC_CLANKER_LEFT_GILL_TO_CC_MAIN = 0x02F
    CC_CLANKER_RIGHT_GILL_TO_CC_MAIN = 0x030
    CC_CLANKER_WONDERWING_TO_CC_CLANKER_BELLY = 0x09B

    BGS_MAIN_TO_GL_BGS_ENTRANCE = 0x0
    BGS_MAIN_TO_BGS_MUMBOS_SKULL = 0x0
    BGS_MAIN_TO_BGS_TANKTUP = 0x0
    BGS_MUMBOS_SKULL_TO_BGS_MAIN = 0x0
    BGS_TANKTUP_TO_BGS_MAIN = 0x0
    BGS_MAIN_TO_BGS_VILE_LEFT = 0x0
    BGS_MAIN_TO_BGS_VILE_RIGHT = 0x0
    BGS_VILE_LEFT_TO_BGS_MAIN = 0x0
    BGS_VILE_RIGHT_TO_BGS_MAIN = 0x0

    FP_MAIN_TO_GL_FP_ENTRANCE = 0x0
    FP_MAIN_TO_FP_IGLOO = 0x0
    FP_MAIN_TO_FP_TREE = 0x0
    FP_MAIN_TO_FP_MUMBOS_SKULL = 0x0
    FP_MAIN_TO_FP_WOZZAS_CAVE = 0x0
    FP_IGLOO_TO_FP_MAIN = 0x0
    FP_TREE_TO_FP_MAIN = 0x0
    FP_MUMBOS_SKULL_TO_FP_MAIN = 0x0
    FP_WOZZAS_CAVE_TO_FP_MAIN = 0x0

    GV_MAIN_TO_GL_GV_ENTRANCE = 0x0
    GV_MAIN_TO_GV_JINXY = 0x0
    GV_MAIN_TO_GV_RUBEE = 0x0
    GV_MAIN_TO_GV_WATER_PYRAMID = 0x0
    GV_MAIN_TO_GV_MATCHING_PYRAMID = 0x0
    GV_MAIN_TO_GV_SNS_ROOM = 0x0
    GV_JINXY_TO_GV_MAIN = 0x0
    GV_RUBEE_TO_GV_MAIN = 0x0
    GV_WATER_PYRAMID_TO_GV_MAIN = 0x0
    GV_MATCHING_PYRAMID_TO_GV_MAIN = 0x0
    GV_SNS_ROOM_TO_GV_MAIN = 0x0

    MMM_MAIN_TO_GL_MMM_ENTRANCE = 0x0
    MMM_MAIN_TO_MMM_NAPPER_FRONT = 0x0
    MMM_MAIN_TO_MMM_NAPPER_CHIMNEY = 0x0
    MMM_MAIN_TO_MMM_EGG_ROOM = 0x0
    MMM_MAIN_TO_MMM_RED_FEATHER_ROOM = 0x0
    MMM_MAIN_TO_MMM_HONEYCOMB_ROOM = 0x0
    MMM_MAIN_TO_MMM_LOGGO_ROOM = 0x0
    MMM_MAIN_TO_MMM_BEDROOM = 0x0
    MMM_MAIN_TO_MMM_NOTE_ROOM = 0x0
    MMM_MAIN_TO_MMM_CHURCH = 0x0
    MMM_MAIN_TO_MMM_SECRET_ROOM = 0x0
    MMM_MAIN_TO_MMM_CELLAR = 0x0
    MMM_MAIN_TO_MMM_WELL_TOP = 0x0
    MMM_MAIN_TO_MMM_MUMBOS_SKULL = 0x0
    MMM_MAIN_TO_MMM_TUMBLAR = 0x0
    MMM_CHURCH_LOWER_TO_MMM_CHURCH_UPPER = 0x0
    MMM_CHURCH_UPPER_TO_MMM_CHURCH_LOWER = 0x0
    MMM_NAPPER_FRONT_TO_MMM_MAIN = 0x0
    MMM_EGG_ROOM_TO_MMM_MAIN = 0x0
    MMM_RED_FEATHER_ROOM_TO_MMM_MAIN = 0x0
    MMM_HONEYCOMB_ROOM_TO_MMM_MAIN = 0x0
    MMM_LOGGO_ROOM_TO_MMM_MAIN = 0x0
    MMM_BEDROOM_TO_MMM_MAIN = 0x0
    MMM_NOTE_ROOM_TO_MMM_MAIN = 0x0
    MMM_CHURCH_TO_MMM_MAIN = 0x0
    MMM_SECRET_ROOM_TO_MMM_MAIN = 0x0
    MMM_CELLAR_TO_MMM_MAIN = 0x0
    MMM_WELL_TOP_TO_MMM_MAIN = 0x0
    MMM_MUMBOS_SKULL_TO_MMM_MAIN = 0x0
    MMM_TUMBLAR_TO_MMM_MAIN = 0x0
    MMM_MAIN_TO_MMM_GUTTER_TOP = 0x0
    MMM_MAIN_TO_MMM_GUTTER_BOTTOM = 0x0
    MMM_MAIN_TO_MMM_WELL_BOTTOM = 0x0
    MMM_LOGGO_ROOM_TO_MMM_INSIDE_LOGGO = 0x0
    MMM_GUTTER_BOTTOM_TO_MMM_MAIN = 0x0
    MMM_WELL_BOTTOM_TO_MMM_MAIN = 0x0
    MMM_INSIDE_LOGGO_TO_MMM_LOGGO_ROOM = 0x0

    RBB_MAIN_TO_GL_RBB_ENTRANCE = 0x0
    RBB_MAIN_TO_RBB_BIG_FISH_WAREHOUSE_TOP = 0x0
    RBB_MAIN_TO_RBB_BIG_FISH_WAREHOUSE_BOTTOM = 0x0
    RBB_MAIN_TO_RBB_BOAT_ROOM = 0x0
    RBB_MAIN_TO_RBB_MINI_KABOOM_CONTAINER = 0x0
    RBB_MAIN_TO_RBB_SEAMAN_GRUBLIN_CONTAINER = 0x0
    RBB_MAIN_TO_RBB_CHOMPA_CONTAINER = 0x0
    RBB_MAIN_TO_RBB_KITCHEN_PIPE = 0x0
    RBB_MAIN_TO_RBB_MINI_KABOOM_PIPE = 0x0
    RBB_MAIN_TO_RBB_ENGINE_ROOM_PIPE = 0x0
    RBB_MAIN_TO_RBB_ENGINE_ROOM_MAIN = 0x0
    RBB_MAIN_TO_RBB_CONTROL_ROOM_WINDOW = 0x0
    RBB_MAIN_TO_RBB_CAPTAINS_ROOM_WINDOW = 0x0
    RBB_MAIN_TO_RBB_CABIN_WINDOW = 0x0
    RBB_MAIN_TO_RBB_BOSS_KABOOM_BOSS = 0x0
    RBB_BIG_FISH_WAREHOUSE_BOTTOM_TO_RBB_MAIN = 0x0
    RBB_BOAT_ROOM_TO_RBB_MAIN = 0x0
    RBB_MINI_KABOOM_CONTAINER_TO_RBB_MAIN = 0x0
    RBB_SEAMAN_GRUBLIN_CONTAINER_TO_RBB_MAIN = 0x0
    RBB_CHOMPA_CONTAINER_TO_RBB_MAIN = 0x0
    RBB_KITCHEN_PIPE_TO_RBB_MAIN = 0x0
    RBB_MINI_KABOOM_PIPE_TO_RBB_MAIN = 0x0
    RBB_ENGINE_ROOM_PIPE_TO_RBB_MAIN = 0x0
    RBB_ENGINE_ROOM_MAIN_TO_RBB_MAIN = 0x0
    RBB_CONTROL_ROOM_WINDOW_TO_RBB_MAIN = 0x0
    RBB_CAPTAINS_ROOM_WINDOW_TO_RBB_MAIN = 0x0
    RBB_CABIN_WINDOW_TO_RBB_MAIN = 0x0
    RBB_BOSS_KABOOM_BOSS_TO_RBB_MAIN = 0x0

    CCW_MAIN_TO_GL_CCW_ENTRANCE = 0x0
    CCW_MAIN_TO_CCW_SPRING_MAIN = 0x0
    CCW_MAIN_TO_CCW_SUMMER_MAIN = 0x0
    CCW_MAIN_TO_CCW_AUTUMN_MAIN = 0x0
    CCW_MAIN_TO_CCW_WINTER_MAIN = 0x0
    CCW_SPRING_MAIN_TO_CCW_MAIN = 0x0
    CCW_SUMMER_MAIN_TO_CCW_MAIN = 0x0
    CCW_AUTUMN_MAIN_TO_CCW_MAIN = 0x0
    CCW_WINTER_MAIN_TO_CCW_MAIN = 0x0