from enum import Enum, unique
from Data_Files.Enums.Map_Enums import MAP_ENUMS

@unique
class WARP_ENUMS(Enum):

    @classmethod
    def get_debug_name(self, warp):
        return warp.name

    @classmethod
    def get_map_enum(self, warp):
        return warp.value[0]

    @classmethod
    def get_exit_enum(self, warp):
        return warp.value[1]
    
    @classmethod
    def get_all_warps_with_map_enum(self, warp, map_enum):
        warp_list = []
        for warp in WARP_ENUMS:
            if(WARP_ENUMS.get_map_enum(warp) == map_enum):
                warp_list.append(warp)
        return warp_list

    # SM MAIN
    SM_MAIN_TO_SM_BANJOS_HOUSE = MAP_ENUMS.SM_BANJOS_HOUSE, 0x01
    SM_MAIN_TO_GL_MM_ENTRANCE = MAP_ENUMS.GL_MM_ENTRANCE, 0x12
    # SM OTHER
    SM_BANJOS_HOUSE_TO_SM_MAIN = MAP_ENUMS.SM_MAIN, 0x12

    # GL MM ENTRANCE
    GL_MM_ENTRANCE_TO_SM_MAIN = MAP_ENUMS.SM_MAIN, 0x13
    GL_MM_ENTRANCE_TO_MM_MAIN = MAP_ENUMS.MM_MAIN, 0x05
    GL_MM_ENTRANCE_TO_GL_TTC_CC_PUZZLES = MAP_ENUMS.GL_TTC_CC_PUZZLES, 0x01
    # GL TTC CC PUZZLES
    GL_TTC_CC_PUZZLES_TO_GL_MM_ENTRANCE = MAP_ENUMS.GL_MM_ENTRANCE, 0x01
    GL_TTC_CC_PUZZLES_TO_GL_CCW_PUZZLE = MAP_ENUMS.GL_CCW_PUZZLE, 0x01
    # GL CCW PUZZLE
    GL_CCW_PUZZLE_TO_GL_TTC_CC_PUZZLES = MAP_ENUMS.GL_TTC_CC_PUZZLES, 0x02
    GL_CCW_PUZZLE_TO_GL_TTC_ENTRANCE = MAP_ENUMS.GL_TTC_ENTRANCE, 0x01
    GL_CCW_PUZZLE_TO_GL_PIPE_ROOM = MAP_ENUMS.GL_PIPE_ROOM, 0x01
    GL_CCW_PUZZLE_TO_GL_CC_ENTRANCE = MAP_ENUMS.GL_CC_ENTRANCE, 0x01
    GL_CCW_PUZZLE_TO_GL_GRUNTY_STATUE = MAP_ENUMS.GL_GRUNTY_STATUE, 0x02
    # GL PIPE ROOM
    GL_PIPE_ROOM_TO_GL_CCW_PUZZLE = MAP_ENUMS.GL_CCW_PUZZLE, 0x02
    # GL TTC ENTRANCE
    GL_TTC_ENTRANCE_TO_GL_CCW_PUZZLE = MAP_ENUMS.GL_CCW_PUZZLE, 0x03
    GL_TTC_ENTRANCE_TO_TTC_MAIN = MAP_ENUMS.TTC_MAIN, 0x04
    # GL CC ENTRANCE
    GL_CC_ENTRANCE_TO_GL_CCW_PUZZLE = MAP_ENUMS.GL_CCW_PUZZLE, 0x04
    GL_CC_ENTRANCE_TO_CC_MAIN = MAP_ENUMS.CC_MAIN, 0x05
    # GL GRUNTY STATUE
    GL_GRUNTY_STATUE_TO_GL_CCW_PUZZLE = MAP_ENUMS.GL_CCW_PUZZLE, 0x05
    GL_GRUNTY_STATUE_TO_GL_BGS_ENTRANCE = MAP_ENUMS.GL_BGS_ENTRANCE, 0x01
    GL_GRUNTY_STATUE_TO_GL_GV_ENTRANCE = MAP_ENUMS.GL_GV_ENTRANCE, 0x01
    # GL BGS ENTRANCE
    GL_BGS_ENTRANCE_TO_BGS_MAIN = MAP_ENUMS.BGS_MAIN, 0x02
    GL_BGS_ENTRANCE_TO_GL_GRUNTY_STATUE = MAP_ENUMS.GL_GRUNTY_STATUE, 0x03
    # GL GV ENTRANCE
    GL_GV_ENTRANCE_TO_GL_GRUNTY_STATUE_NOTE_DOOR = MAP_ENUMS.GL_GRUNTY_STATUE, 0x01
    GL_GV_ENTRANCE_TO_GL_GRUNTY_STATUE_WITCH_SWITCH = MAP_ENUMS.GL_GRUNTY_STATUE, 0x04
    GL_GV_ENTRANCE_TO_GL_FP_ENTRANCE = MAP_ENUMS.GL_FP_ENTRANCE, 0x01
    GL_GV_ENTRANCE_TO_GV_MAIN = MAP_ENUMS.GV_MAIN, 0x08
    # GL FP ENTRANCE
    GL_FP_ENTRANCE_TO_FP_MAIN = MAP_ENUMS.FP_MAIN, 0x01
    GL_FP_ENTRANCE_TO_GL_GV_ENTRANCE = MAP_ENUMS.GL_GV_ENTRANCE, 0x02
    GL_FP_ENTRANCE_TO_GL_GV_PUZZLE = MAP_ENUMS.GL_GV_PUZZLE, 0x02
    GL_FP_ENTRANCE_TO_GL_WATER_THREE_SWITCH = MAP_ENUMS.GL_WATER_THREE_SWITCH, 0x01
    # GL GV PUZZLE
    GL_GV_PUZZLE_TO_GL_FP_ENTRANCE = MAP_ENUMS.GL_FP_ENTRANCE, 0x05
    GL_GV_PUZZLE_TO_GL_MMM_ENTRANCE = MAP_ENUMS.GL_MMM_ENTRANCE, 0x01
    # GL MMM ENTRANCE
    GL_MMM_ENTRANCE_TO_GL_GV_PUZZLE = MAP_ENUMS.GL_GV_PUZZLE, 0x01
    GL_MMM_ENTRANCE_TO_GL_CRYPT = MAP_ENUMS.GL_CRYPT, 0x01
    GL_MMM_ENTRANCE_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x14
    # GL CRYPT
    GL_CRYPT_TO_GL_MMM_ENTRANCE = MAP_ENUMS.GL_MMM_ENTRANCE, 0x03
    # GL WATER THREE SWITCH
    GL_WATER_THREE_SWITCH_TO_GL_FP_ENTRANCE = MAP_ENUMS.GL_FP_ENTRANCE, 0x02
    GL_WATER_THREE_SWITCH_TO_GL_RBB_ENTRANCE = MAP_ENUMS.GL_RBB_ENTRANCE, 0x01
    GL_WATER_THREE_SWITCH_TO_GL_CCW_ENTRANCE_NOTE_DOOR = MAP_ENUMS.GL_CCW_ENTRANCE, 0x01
    GL_WATER_THREE_SWITCH_TO_GL_CCW_ENTRANCE_TOKEN = MAP_ENUMS.GL_CCW_ENTRANCE, 0x02
    # GL RBB ENTRANCE
    GL_RBB_ENTRANCE_TO_GL_WATER_THREE_SWITCH = MAP_ENUMS.GL_WATER_THREE_SWITCH, 0x04
    GL_RBB_ENTRANCE_TO_GL_MMM_PUZZLE = MAP_ENUMS.GL_MMM_RBB_PUZZLE, 0x01
    GL_RBB_ENTRANCE_TO_GL_RBB_PUZZLE = MAP_ENUMS.GL_MMM_RBB_PUZZLE, 0x02
    GL_RBB_ENTRANCE_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x10
    # GL MMM PUZZLE
    GL_MMM_PUZZLE_TO_GL_RBB_ENTRANCE = MAP_ENUMS.GL_RBB_ENTRANCE, 0x04
    GL_RBB_PUZZLE_TO_GL_RBB_ENTRANCE = MAP_ENUMS.GL_RBB_ENTRANCE, 0x03
    # GL CCW ENTRANCE
    GL_CCW_ENTRANCE_TO_GL_WATER_THREE_SWITCH_NOTE_DOOR = MAP_ENUMS.GL_WATER_THREE_SWITCH, 0x03
    GL_CCW_ENTRANCE_TO_GL_WATER_THREE_SWITCH_TOKEN = MAP_ENUMS.GL_WATER_THREE_SWITCH, 0x02
    GL_CCW_ENTRANCE_TO_GL_PATH_TO_FF = MAP_ENUMS.GL_PATH_TO_FF, 0x01
    GL_CCW_ENTRANCE_TO_CCW_MAIN = MAP_ENUMS.CCW_MAIN, 0x07
    # GL PATH TO FF
    GL_PATH_TO_FF_TO_GL_CCW_ENTRANCE = MAP_ENUMS.GL_CCW_ENTRANCE, 0x03
    # GL FF
    GL_FF_TO_GL_DOOR_OF_GRUNTY = MAP_ENUMS.GL_DOOR_OF_GRUNTY, 0x05
    # GL DOOR OF GRUNTY
    GL_DOOR_OF_GRUNTY_TO_GL_FF = MAP_ENUMS.GL_FF, 0x05
    GL_DOOR_OF_GRUNTY_TO_FINAL_BATTLE = MAP_ENUMS.FINAL_BATTLE, 0x01

    # MM MAIN
    MM_MAIN_TO_GL_MM_ENTRANCE = MAP_ENUMS.GL_MM_ENTRANCE, 0x02
    MM_MAIN_TO_MM_MUMBOS_SKULL = MAP_ENUMS.MM_MUMBOS_SKULL, 0x01
    MM_MAIN_TO_MM_LOWER_TICKERS = MAP_ENUMS.MM_TICKERS, 0x02
    MM_MAIN_TO_MM_UPPER_TICKERS = MAP_ENUMS.MM_TICKERS, 0x01
    # MM OTHER
    MM_MUMBOS_SKULL_TO_MM_MAIN = MAP_ENUMS.MM_MAIN, 0x01
    MM_LOWER_TICKERS_TO_MM_MAIN = MAP_ENUMS.MM_MAIN, 0x02
    MM_UPPER_TICKERS_TO_MM_MAIN = MAP_ENUMS.MM_MAIN, 0x03

    # TTC MAIN
    TTC_MAIN_TO_GL_TTC_ENTRANCE = MAP_ENUMS.GL_TTC_ENTRANCE, 0x04
    TTC_MAIN_TO_TTC_SANDCASTLE = MAP_ENUMS.TTC_SANDCASTLE, 0x01
    TTC_MAIN_TO_TTC_NIPPER = MAP_ENUMS.TTC_NIPPER, 0x01
    TTC_MAIN_TO_TTC_SALTY_HIPPO_SIDE = MAP_ENUMS.TTC_SALTY_HIPPO, 0x06
    TTC_MAIN_TO_TTC_SALTY_HIPPO_TOP = MAP_ENUMS.TTC_SALTY_HIPPO, 0x05
    TTC_ALCOVE_LOWER_TO_TTC_ALCOVE_UPPER = MAP_ENUMS.TTC_MAIN, 0x0E
    TTC_ALCOVE_UPPER_TO_TTC_ALCOVE_LOWER = MAP_ENUMS.TTC_MAIN, 0x0F
    TTC_LIGHTHOUSE_LOWER_TO_TTC_LIGHTHOUSE_UPPER = MAP_ENUMS.TTC_MAIN, 0x08
    TTC_LIGHTHOUSE_UPPER_TO_TTC_LIGHTHOUSE_LOWER = MAP_ENUMS.TTC_MAIN, 0x0C
    TTC_MAIN_TO_TTC_SHARKFOOD_ISLAND = MAP_ENUMS.TTC_SHARKFOOD_ISLAND, 0x01
    # TTC OTHER
    TTC_SANDCASTLE_TO_TTC_MAIN = MAP_ENUMS.TTC_MAIN, 0x03
    TTC_NIPPER_TO_TTC_MAIN = MAP_ENUMS.TTC_MAIN, 0x0A
    TTC_SALTY_HIPPO_SIDE_TO_TTC_MAIN = MAP_ENUMS.TTC_MAIN, 0x07
    TTC_SALTY_HIPPO_TOP_TO_TTC_MAIN = MAP_ENUMS.TTC_MAIN, 0x06
    TTC_SHARKFOOD_ISLAND_TO_TTC_MAIN = MAP_ENUMS.TTC_MAIN, 0x80

    # CC MAIN
    CC_MAIN_TO_GL_CC_ENTRANCE = MAP_ENUMS.GL_CC_ENTRANCE, 0x02
    CC_MAIN_TO_CC_CLANKER_BLOWHOLE = MAP_ENUMS.CC_CLANKER_BLOWHOLE, 0x01
    CC_MAIN_TO_CC_CLANKER_LEFT_TOOTH = MAP_ENUMS.CC_CLANKER_MOUTH_BELLY, 0x07
    CC_MAIN_TO_CC_CLANKER_RIGHT_TOOTH = MAP_ENUMS.CC_CLANKER_MOUTH_BELLY, 0x06
    CC_MAIN_TO_CC_CLANKER_LEFT_GILL = MAP_ENUMS.CC_CLANKER_MOUTH_BELLY, 0x05
    CC_MAIN_TO_CC_CLANKER_RIGHT_GILL = MAP_ENUMS.CC_CLANKER_MOUTH_BELLY, 0x04
    # CC OTHER
    CC_CLANKER_WONDERWING_TO_CC_CLANKER_BELLY = MAP_ENUMS.CC_CLANKER_MOUTH_BELLY, 0x03
    CC_CLANKER_BLOWHOLE_TO_CC_CLANKER_MOUTH = MAP_ENUMS.CC_CLANKER_MOUTH_BELLY, 0x02
    CC_CLANKER_BLOWHOLE_TO_CC_CLANKER_BELLY = MAP_ENUMS.CC_CLANKER_MOUTH_BELLY, 0x01
    CC_CLANKER_BELLY_TO_CC_CLANKER_WONDERWING = MAP_ENUMS.CC_CLANKER_WONDERWING, 0x01
    CC_CLANKER_LEFT_TOOTH_TO_CC_MAIN = MAP_ENUMS.CC_MAIN, 0x01
    CC_CLANKER_RIGHT_TOOTH_TO_CC_MAIN = MAP_ENUMS.CC_MAIN, 0x02
    CC_CLANKER_LEFT_GILL_TO_CC_MAIN = MAP_ENUMS.CC_MAIN, 0x03
    CC_CLANKER_RIGHT_GILL_TO_CC_MAIN = MAP_ENUMS.CC_MAIN, 0x04

    # BGS MAIN
    BGS_MAIN_TO_GL_BGS_ENTRANCE = MAP_ENUMS.GL_BGS_ENTRANCE, 0x02
    BGS_MAIN_TO_BGS_MUMBOS_SKULL = MAP_ENUMS.BGS_MUMBOS_SKULL, 0x01
    BGS_MAIN_TO_BGS_TANKTUP = MAP_ENUMS.BGS_TANKTUP, 0x01
    # BGS OTHER
    BGS_MUMBOS_SKULL_TO_BGS_MAIN = MAP_ENUMS.BGS_MAIN, 0x06
    BGS_TANKTUP_TO_BGS_MAIN = MAP_ENUMS.BGS_MAIN, 0x03
    # TRANSFORMATION ONLY
    BGS_MAIN_TO_BGS_VILE_LEFT = MAP_ENUMS.BGS_VILE, 0x04
    BGS_MAIN_TO_BGS_VILE_RIGHT = MAP_ENUMS.BGS_VILE, 0x03
    BGS_VILE_LEFT_TO_BGS_MAIN = MAP_ENUMS.BGS_MAIN, 0x05
    BGS_VILE_RIGHT_TO_BGS_MAIN = MAP_ENUMS.BGS_MAIN, 0x04

    # FP MAIN
    FP_MAIN_TO_GL_FP_ENTRANCE = MAP_ENUMS.GL_FP_ENTRANCE, 0x06
    FP_MAIN_TO_FP_IGLOO = MAP_ENUMS.FP_IGLOO, 0x01
    FP_MAIN_TO_FP_TREE = MAP_ENUMS.FP_TREE, 0x01
    FP_MAIN_TO_FP_MUMBOS_SKULL = MAP_ENUMS.FP_MUMBOS_SKULL, 0x01
    FP_MAIN_TO_FP_WOZZAS_CAVE = MAP_ENUMS.FP_WOZZAS_CAVE, 0x01
    # FP OTHER
    FP_IGLOO_TO_FP_MAIN = MAP_ENUMS.FP_MAIN, 0x08
    FP_TREE_TO_FP_MAIN = MAP_ENUMS.FP_MAIN, 0x09
    FP_MUMBOS_SKULL_TO_FP_MAIN = MAP_ENUMS.FP_MAIN, 0x07
    FP_WOZZAS_CAVE_TO_FP_MAIN = MAP_ENUMS.FP_MAIN, 0x06

    # GV MAIN
    GV_MAIN_TO_GL_GV_ENTRANCE = MAP_ENUMS.GL_GV_ENTRANCE, 0x03
    GV_MAIN_TO_GV_JINXY = MAP_ENUMS.GV_JINXY, 0x02
    GV_MAIN_TO_GV_RUBEE = MAP_ENUMS.GV_RUBEE, 0x07
    GV_MAIN_TO_GV_WATER_PYRAMID_UPPER = MAP_ENUMS.GV_WATER_PYRAMID, 0x02
    GV_MAIN_TO_GV_WATER_PYRAMID_LOWER = MAP_ENUMS.GV_WATER_PYRAMID, 0x06
    GV_MAIN_TO_GV_MATCHING_PYRAMID = MAP_ENUMS.GV_MATCHING_PYRAMID, 0x01
    GV_MAIN_TO_KING_SANDYBUTT = MAP_ENUMS.KING_SANDYBUTT, 0x01
    GV_MAIN_TO_GV_SNS_ROOM = MAP_ENUMS.GV_SNS_ROOM, 0x05
    # GV OTHER
    GV_JINXY_TO_GV_MAIN = MAP_ENUMS.GV_MAIN, 0x02
    GV_RUBEE_TO_GV_MAIN = MAP_ENUMS.GV_MAIN, 0x06
    GV_WATER_PYRAMID_LOWER_TO_GV_MAIN = MAP_ENUMS.GV_MAIN, 0x05
    GV_MATCHING_PYRAMID_TO_GV_MAIN = MAP_ENUMS.GV_MAIN, 0x03
    GV_KING_SANDYBUTT_FRONT_TO_GV_MAIN = MAP_ENUMS.GV_MAIN, 0x04
    GV_KING_SANDYBUTT_BACK_TO_GV_MAIN = MAP_ENUMS.GV_MAIN, 0x07
    GV_SNS_ROOM_TO_GV_MAIN = MAP_ENUMS.GV_MAIN, 0x0A

    # MMM MAIN
    MMM_MAIN_TO_GL_MMM_ENTRANCE = MAP_ENUMS.GL_MMM_ENTRANCE, 0x02
    MMM_MAIN_TO_MMM_NAPPER_FRONT = MAP_ENUMS.MMM_NAPPER, 0x01
    MMM_MAIN_TO_MMM_NAPPER_CHIMNEY = MAP_ENUMS.MMM_NAPPER, 0x02
    MMM_MAIN_TO_MMM_EGG_ROOM = MAP_ENUMS.MMM_EGG_ROOM, 0x01
    MMM_MAIN_TO_MMM_RED_FEATHER_ROOM = MAP_ENUMS.MMM_RED_FEATHER_ROOM, 0x01
    MMM_MAIN_TO_MMM_HONEYCOMB_ROOM = MAP_ENUMS.MMM_HONEYCOMB_ROOM, 0x01
    MMM_MAIN_TO_MMM_LOGGO_ROOM = MAP_ENUMS.MMM_LOGGO_ROOM, 0x01
    MMM_MAIN_TO_MMM_BEDROOM = MAP_ENUMS.MMM_BEDROOM, 0x01
    MMM_MAIN_TO_MMM_NOTE_ROOM = MAP_ENUMS.MMM_NOTE_ROOM, 0x01
    MMM_MAIN_TO_MMM_CHURCH = MAP_ENUMS.MMM_CHURCH, 0x01
    MMM_MAIN_TO_MMM_SECRET_ROOM = MAP_ENUMS.MMM_SECRET_ROOM, 0x01
    MMM_MAIN_TO_MMM_CELLAR = MAP_ENUMS.MMM_CELLAR, 0x01
    MMM_MAIN_TO_MMM_WELL_TOP = MAP_ENUMS.MMM_WELL, 0x01
    MMM_MAIN_TO_MMM_MUMBOS_SKULL = MAP_ENUMS.MMM_MUMBOS_SKULL, 0x01
    MMM_MAIN_TO_MMM_TUMBLAR = MAP_ENUMS.MMM_TUMBLAR, 0x01
    MMM_CHURCH_LOWER_TO_MMM_CHURCH_UPPER = MAP_ENUMS.MMM_MAIN, 0x10
    MMM_CHURCH_UPPER_TO_MMM_CHURCH_LOWER = MAP_ENUMS.MMM_MAIN, 0x11
    # MMM OTHER
    MMM_NAPPER_FRONT_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x01
    MMM_EGG_ROOM_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x0B
    MMM_RED_FEATHER_ROOM_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x0A
    MMM_HONEYCOMB_ROOM_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x0D
    MMM_LOGGO_ROOM_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x0C
    MMM_BEDROOM_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x0E
    MMM_NOTE_ROOM_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x0F
    MMM_CHURCH_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x05
    MMM_SECRET_ROOM_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x06
    MMM_CELLAR_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x09
    MMM_WELL_TOP_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x03
    MMM_MUMBOS_SKULL_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x12
    MMM_TUMBLAR_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x04
    # TRANSFORMATION ONLY
    MMM_MAIN_TO_MMM_GUTTER_TOP = MAP_ENUMS.MMM_GUTTER, 0x01
    MMM_MAIN_TO_MMM_GUTTER_BOTTOM = MAP_ENUMS.MMM_GUTTER, 0x02
    MMM_MAIN_TO_MMM_WELL_BOTTOM = MAP_ENUMS.MMM_WELL, 0x04
    MMM_LOGGO_ROOM_TO_MMM_INSIDE_LOGGO = MAP_ENUMS.MMM_INSIDE_LOGGO, 0x04
    MMM_GUTTER_BOTTOM_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x08
    MMM_WELL_BOTTOM_TO_MMM_MAIN = MAP_ENUMS.MMM_MAIN, 0x13
    MMM_INSIDE_LOGGO_TO_MMM_LOGGO_ROOM = MAP_ENUMS.MMM_LOGGO_ROOM, 0x04

    # RBB MAIN
    RBB_MAIN_TO_GL_RBB_ENTRANCE = MAP_ENUMS.GL_RBB_ENTRANCE, 0x02
    RBB_MAIN_TO_RBB_BIG_FISH_WAREHOUSE_TOP = MAP_ENUMS.RBB_BIG_FISH_WAREHOUSE, 0x02
    RBB_MAIN_TO_RBB_BIG_FISH_WAREHOUSE_BOTTOM = MAP_ENUMS.RBB_BIG_FISH_WAREHOUSE, 0x01
    RBB_MAIN_TO_RBB_BOAT_ROOM = MAP_ENUMS.RBB_BOAT_ROOM, 0x01
    RBB_MAIN_TO_RBB_MINI_KABOOM_CONTAINER = MAP_ENUMS.RBB_MINI_KABOOM_CONTAINER, 0x01
    RBB_MAIN_TO_RBB_SEAMAN_GRUBLIN_CONTAINER = MAP_ENUMS.RBB_SEAMAN_GRUBLIN_CONTAINER, 0x01
    RBB_MAIN_TO_RBB_CHOMPA_CONTAINER = MAP_ENUMS.RBB_CHOMPA_CONTAINER, 0x01
    RBB_MAIN_TO_RBB_KITCHEN_PIPE = MAP_ENUMS.RBB_KITCHEN_PIPE, 0x01
    RBB_MAIN_TO_RBB_MINI_KABOOM_PIPE = MAP_ENUMS.RBB_MINI_KABOOM_PIPE, 0x01
    RBB_MAIN_TO_RBB_ENGINE_ROOM_PIPE = MAP_ENUMS.RBB_ENGINE_ROOM, 0x04
    RBB_MAIN_TO_RBB_ENGINE_ROOM_MAIN = MAP_ENUMS.RBB_ENGINE_ROOM, 0x01
    RBB_MAIN_TO_RBB_CONTROL_ROOM_WINDOW = MAP_ENUMS.RBB_CONTROL_ROOM_WINDOW, 0x01
    RBB_MAIN_TO_RBB_CAPTAINS_ROOM_WINDOW = MAP_ENUMS.RBB_CAPTAINS_ROOM_WINDOW, 0x01
    RBB_MAIN_TO_RBB_CABIN_WINDOW = MAP_ENUMS.RBB_CABIN_WINDOW, 0x01
    RBB_MAIN_TO_RBB_BOSS_KABOOM_BOSS = MAP_ENUMS.RBB_BOSS_KABOOM_BOSS, 0x01
    RBB_MAIN_TO_RBB_ANCHOR = MAP_ENUMS.RBB_ANCHOR, 0x04
    # RBB OTHER
    RBB_BIG_FISH_WAREHOUSE_BOTTOM_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x0D
    RBB_BOAT_ROOM_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x08
    RBB_MINI_KABOOM_CONTAINER_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x0B
    RBB_SEAMAN_GRUBLIN_CONTAINER_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x0A
    RBB_CHOMPA_CONTAINER_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x09
    RBB_KITCHEN_PIPE_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x04
    RBB_MINI_KABOOM_PIPE_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x06
    RBB_ENGINE_ROOM_PIPE_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x03
    RBB_ENGINE_ROOM_MAIN_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x07
    RBB_CONTROL_ROOM_WINDOW_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x05
    RBB_CAPTAINS_ROOM_WINDOW_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x01
    RBB_CABIN_WINDOW_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x02
    RBB_BOSS_KABOOM_BOSS_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x0C
    RBB_ANCHOR_TO_RBB_MAIN = MAP_ENUMS.RBB_MAIN, 0x13

    # CCW MAIN
    CCW_MAIN_TO_GL_CCW_ENTRANCE = MAP_ENUMS.GL_CCW_ENTRANCE, 0x06
    CCW_MAIN_TO_CCW_SPRING_MAIN = MAP_ENUMS.CCW_SPRING_MAIN, 0x01
    CCW_MAIN_TO_CCW_SUMMER_MAIN = MAP_ENUMS.CCW_SUMMER_MAIN, 0x01
    CCW_MAIN_TO_CCW_AUTUMN_MAIN = MAP_ENUMS.CCW_AUTUMN_MAIN, 0x01
    CCW_MAIN_TO_CCW_WINTER_MAIN = MAP_ENUMS.CCW_WINTER_MAIN, 0x01

    # CCW SPRING MAIN
    CCW_SPRING_MAIN_TO_CCW_MAIN = MAP_ENUMS.CCW_MAIN, 0x02
    CCW_SPRING_MAIN_TO_CCW_SPRING_MUMBOS_SKULL = MAP_ENUMS.CCW_SPRING_MUMBOS_SKULL, 0x01
    CCW_SPRING_MAIN_TO_CCW_SPRING_NABNUT_DOOR = 0x5E, 0x01
    CCW_SPRING_MAIN_TO_CCW_SPRING_NABNUT_WINDOW = 0x5E, 0x02
    CCW_SPRING_MAIN_TO_CCW_SPRING_WHIPCRACKS = MAP_ENUMS.CCW_SPRING_WHIPCRACKS, 0x01
    # CCW SPRING OTHER
    CCW_SPRING_MUMBOS_SKULL_TO_CCW_SPRING_MAIN = MAP_ENUMS.CCW_SPRING_MAIN, 0x09
    CCW_SPRING_NABNUT_DOOR_TO_CCW_SPRING_MAIN = MAP_ENUMS.CCW_SPRING_MAIN, 0x07
    CCW_SPRING_NABNUT_WINDOW_TO_CCW_SPRING_MAIN = MAP_ENUMS.CCW_SPRING_MAIN, 0x04
    CCW_SPRING_WHIPCRACKS_TO_CCW_SPRING_MAIN = MAP_ENUMS.CCW_SPRING_MAIN, 0x08
    # TRANSFORMATION ONLY
    CCW_SPRING_MAIN_TO_CCW_SPRING_ZUBBA = MAP_ENUMS.CCW_SPRING_ZUBBA, 0x01
    CCW_SPRING_ZUBBA_TO_CCW_SPRING_MAIN = MAP_ENUMS.CCW_SPRING_MAIN, 0x06

    # CCW SUMMER MAIN
    CCW_SUMMER_MAIN_TO_CCW_MAIN = MAP_ENUMS.CCW_MAIN, 0x03
    CCW_SUMMER_MAIN_TO_CCW_SUMMER_MUMBOS_SKULL = MAP_ENUMS.CCW_SUMMER_MUMBOS_SKULL, 0x01
    CCW_SUMMER_MAIN_TO_CCW_SUMMER_ZUBBA = MAP_ENUMS.CCW_SUMMER_ZUBBA, 0x02
    CCW_SUMMER_MAIN_TO_CCW_SUMMER_NABNUT_DOOR = MAP_ENUMS.CCW_SUMMER_NABNUT, 0x01
    CCW_SUMMER_MAIN_TO_CCW_SUMMER_NABNUT_WINDOW = MAP_ENUMS.CCW_SUMMER_NABNUT, 0x02
    CCW_SUMMER_MAIN_TO_CCW_SUMMER_WHIPCRACKS = MAP_ENUMS.CCW_SUMMER_WHIPCRACKS, 0x01
    # CCW SUMMER OTHER
    CCW_SUMMER_MUMBOS_SKULL_TO_CCW_SUMMER_MAIN = MAP_ENUMS.CCW_SUMMER_MAIN, 0x09
    CCW_SUMMER_ZUBBA_TO_CCW_SUMMER_MAIN = MAP_ENUMS.CCW_SUMMER_MAIN, 0x06
    CCW_SUMMER_NABNUT_DOOR_TO_CCW_SUMMER_MAIN = MAP_ENUMS.CCW_SUMMER_MAIN, 0x07
    CCW_SUMMER_NABNUT_WINDOW_TO_CCW_SUMMER_MAIN = MAP_ENUMS.CCW_SUMMER_MAIN, 0x04
    CCW_SUMMER_WHIPCRACKS_TO_CCW_SUMMER_MAIN = MAP_ENUMS.CCW_SUMMER_MAIN, 0x08

    # CCW AUTUMN MAIN
    CCW_AUTUMN_MAIN_TO_CCW_MAIN = MAP_ENUMS.CCW_MAIN, 0x04
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_MUMBOS_SKULL = MAP_ENUMS.CCW_AUTUMN_MUMBOS_SKULL, 0x01
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_ZUBBA = MAP_ENUMS.CCW_AUTUMN_ZUBBA, 0x02
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_NABNUT_DOOR = MAP_ENUMS.CCW_AUTUMN_NABNUT, 0x01
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_NABNUT_WINDOW = MAP_ENUMS.CCW_AUTUMN_NABNUT, 0x02
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_FLOODED_ATTIC = MAP_ENUMS.CCW_AUTUMN_FLOODED_ATTIC, 0x01
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_WHIPCRACKS = MAP_ENUMS.CCW_AUTUMN_WHIPCRACKS, 0x01
    # CCW AUTUMN OTHER
    CCW_AUTUMN_MUMBOS_SKULL_TO_CCW_AUTUMN_MAIN = MAP_ENUMS.CCW_AUTUMN_MAIN, 0x09
    CCW_AUTUMN_ZUBBA_TO_CCW_AUTUMN_MAIN = MAP_ENUMS.CCW_AUTUMN_MAIN, 0x05
    CCW_AUTUMN_NABNUT_DOOR_TO_CCW_AUTUMN_MAIN = MAP_ENUMS.CCW_AUTUMN_MAIN, 0x07
    CCW_AUTUMN_NABNUT_WINDOW_TO_CCW_AUTUMN_MAIN = MAP_ENUMS.CCW_AUTUMN_MAIN, 0x04
    CCW_AUTUMN_FLOODED_ATTIC_TO_CCW_AUTUMN_MAIN = MAP_ENUMS.CCW_AUTUMN_MAIN, 0x06
    CCW_AUTUMN_WHIPCRACKS_TO_CCW_AUTUMN_MAIN = MAP_ENUMS.CCW_AUTUMN_MAIN, 0x08

    # CCW WINTER MAIN
    CCW_WINTER_MAIN_TO_CCW_MAIN = MAP_ENUMS.CCW_MAIN, 0x01
    CCW_WINTER_MAIN_TO_CCW_WINTER_MUMBOS_SKULL = MAP_ENUMS.CCW_WINTER_MUMBOS_SKULL, 0x01
    CCW_WINTER_MAIN_TO_CCW_WINTER_NABNUT_WINDOW = MAP_ENUMS.CCW_WINTER_NABNUT, 0x02
    CCW_WINTER_MAIN_TO_CCW_WINTER_ACORN_STORAGE = MAP_ENUMS.CCW_WINTER_ACORN_STORAGE, 0x01
    CCW_WINTER_MAIN_TO_CCW_WINTER_FLOODED_ATTIC = MAP_ENUMS.CCW_WINTER_FLOODED_ATTIC, 0x01
    CCW_WINTER_MAIN_TO_CCW_WINTER_WHIPCRACKS = MAP_ENUMS.CCW_WINTER_WHIPCRACKS, 0x01
    # CCW WINTER OTHER
    CCW_WINTER_MUMBOS_SKULL_TO_CCW_WINTER_MAIN = MAP_ENUMS.CCW_WINTER_MAIN, 0x09
    CCW_WINTER_NABNUT_WINDOW_TO_CCW_WINTER_MAIN = MAP_ENUMS.CCW_WINTER_MAIN, 0x04
    CCW_WINTER_ACORN_STORAGE_TO_CCW_WINTER_MAIN = MAP_ENUMS.CCW_WINTER_MAIN, 0x06
    CCW_WINTER_FLOODED_ATTIC_TO_CCW_WINTER_MAIN = MAP_ENUMS.CCW_WINTER_MAIN, 0x05
    CCW_WINTER_WHIPCRACKS_TO_CCW_WINTER_MAIN = MAP_ENUMS.CCW_WINTER_MAIN, 0x08

if __name__ == '__main__':
    for warp in WARP_ENUMS:
        print(WARP_ENUMS.get_debug_name(warp), WARP_ENUMS.get_map_enum(warp), WARP_ENUMS.get_exit_enum(warp))
    # warp_dict = {}
    # for warp in WARP_ENUMS:
    #     curr_map_name = (WARP_ENUMS.get_debug_name(warp)).split("_TO_")[1]
    #     curr_map_enum = WARP_ENUMS.get_map_enum(warp)
    #     warp_dict[curr_map_enum] = curr_map_name
    # for curr_map_enum in sorted(warp_dict):
    #     print(f"{warp_dict[curr_map_enum]} = {hex(curr_map_enum)}")