from enum import IntEnum

class WARP_ENUMS(IntEnum):
    # Crashes/Skipped
    # 0x3206, 0x5200, 0x5100, 0x5101, 0x4200,
    # 0x3201, 0x3202, 0x3203, 0x3204, 0x3205,
    # 0x3207, 0x3208, 0x3209, 0x320A, 0x320B,
    # 0x320C, 0x320D, 0x320E, 0x320F, 0x3210,
    # 0x3211, 0x3212, 0x3213, 0x3214, 0x3215,
    # 0x3216, 0x3217, 

    # SM_MAIN
    SM_MAIN_TO_SM_BANJOS_HOUSE = 0x0
    SM_MAIN_TO_GL_MM_ENTRANCE = 0x6912
    # SM_BANJOS_HOUSE
    SM_BANJOS_HOUSE_TO_SM_MAIN = 0x0112

    # GL_MM_ENTRANCE
    GL_MM_ENTRANCE_TO_SM_MAIN = 0x0113
    GL_MM_ENTRANCE_TO_MM_MAIN = 0x0205
    GL_MM_ENTRANCE_TO_GL_TTC_CC_PUZZLES = 0x0
    # GL_TTC_CC_PUZZLES
    GL_TTC_CC_PUZZLES_TO_GL_MM_ENTRANCE = 0x0
    GL_TTC_CC_PUZZLES_TO_GL_CCW_PUZZLE = 0x0
    # GL_CCW_PUZZLE
    GL_CCW_PUZZLE_TO_GL_TTC_CC_PUZZLES = 0x0
    GL_CCW_PUZZLE_TO_GL_TTC_ENTRANCE = 0x0
    GL_CCW_PUZZLE_TO_GL_PIPE_ROOM = 0x0
    GL_CCW_PUZZLE_TO_GL_CC_ENTRANCE = 0x0
    GL_CCW_PUZZLE_TO_GL_GRUNTY_STATUE = 0x0
    # GL_PIPE_ROOM
    GL_PIPE_ROOM_TO_GL_CCW_PUZZLE = 0x0
    # GL_TTC_ENTRANCE
    GL_TTC_ENTRANCE_TO_GL_CCW_PUZZLE = 0x0
    GL_TTC_ENTRANCE_TO_TTC_MAIN = 0x0704
    # GL_CC_ENTRANCE
    GL_CC_ENTRANCE_TO_GL_CCW_PUZZLE = 0x0
    GL_CC_ENTRANCE_TO_CC_MAIN = 0x0B05
    # GL_GRUNTY_STATUE
    GL_GRUNTY_STATUE_TO_GL_CCW_PUZZLE = 0x0
    GL_GRUNTY_STATUE_TO_GL_BGS_ENTRANCE = 0x0
    GL_GRUNTY_STATUE_TO_GL_GV_ENTRANCE = 0x0
    # GL_BGS_ENTRANCE
    GL_BGS_ENTRANCE_TO_BGS_MAIN = 0x0D02
    GL_BGS_ENTRANCE_TO_GL_GRUNTY_STATUE = 0x0
    # GL_GV_ENTRANCE
    GL_GV_ENTRANCE_TO_GL_GRUNTY_STATUE_NOTE_DOOR = 0x0
    GL_GV_ENTRANCE_TO_GL_GRUNTY_STATUE_WITCH_SWITCH = 0x0
    GL_GV_ENTRANCE_TO_GL_FP_ENTRANCE = 0x0
    GL_GV_ENTRANCE_TO_GV_MAIN = 0x1208
    # GL_FP_ENTRANCE
    GL_FP_ENTRANCE_TO_FP_MAIN = 0x0
    GL_FP_ENTRANCE_TO_GL_GV_ENTRANCE = 0x0
    GL_FP_ENTRANCE_TO_GL_GV_PUZZLE = 0x0
    GL_FP_ENTRANCE_TO_GL_WATER_THREE_SWITCH = 0x0
    # GL_GV_PUZZLE
    GL_GV_PUZZLE_TO_GL_FP_ENTRANCE = 0x0
    GL_GV_PUZZLE_TO_GL_MMM_ENTRANCE = 0x0
    # GL_MMM_ENTRANCE
    GL_MMM_ENTRANCE_TO_GL_GV_PUZZLE = 0x0
    GL_MMM_ENTRANCE_TO_GL_SHED = 0x0
    GL_MMM_ENTRANCE_TO_MMM_MAIN = 0x1B14
    # GL_SHED
    GL_SHED_TO_GL_MMM_ENTRANCE = 0x0
    # GL_WATER_THREE_SWITCH
    GL_WATER_THREE_SWITCH_TO_GL_FP_ENTRANCE = 0x0
    GL_WATER_THREE_SWITCH_TO_GL_RBB_ENTRANCE = 0x0
    GL_WATER_THREE_SWITCH_TO_GL_CCW_ENTRANCE_NOTE_DOOR = 0x0
    GL_WATER_THREE_SWITCH_TO_GL_CCW_ENTRANCE_TOKEN = 0x0
    # GL_RBB_ENTRANCE
    GL_RBB_ENTRANCE_TO_GL_WATER_THREE_SWITCH = 0x0
    GL_RBB_ENTRANCE_TO_GL_MMM_PUZZLE = 0x0
    GL_RBB_ENTRANCE_TO_GL_RBB_PUZZLE = 0x0
    GL_RBB_ENTRANCE_TO_RBB_MAIN = 0x3110
    # GL_MMM_PUZZLE
    GL_MMM_PUZZLE_TO_GL_RBB_ENTRANCE = 0x0
    # GL_RBB_PUZZLE
    GL_RBB_PUZZLE_TO_GL_RBB_ENTRANCE = 0x0
    # GL_CCW_ENTRANCE
    GL_CCW_ENTRANCE_TO_GL_WATER_THREE_SWITCH_NOTE_DOOR = 0x0
    GL_CCW_ENTRANCE_TO_GL_WATER_THREE_SWITCH_TOKEN = 0x0
    GL_CCW_ENTRANCE_TO_GL_PATH_TO_FF = 0x0
    GL_CCW_ENTRANCE_TO_CCW_MAIN = 0x0
    # GL_PATH_TO_FF
    GL_PATH_TO_FF_TO_GL_CCW_ENTRANCE = 0x0
    # GL_FF
    GL_FF_TO_GL_DOOR_OF_GRUNTY = 0x0
    # GL_DOOR_OF_GRUNTY
    GL_DOOR_OF_GRUNTY_TO_GL_FF = 0x0
    GL_DOOR_OF_GRUNTY_TO_FINAL_BATTLE = 0x0

    # MM_MAIN
    MM_MAIN_TO_GL_MM_ENTRANCE = 0x0
    MM_MAIN_TO_MM_MUMBOS_SKULL = 0x0E01
    MM_MAIN_TO_MM_LOWER_TICKERS = 0x0C02
    MM_MAIN_TO_MM_UPPER_TICKERS = 0x0C01
    MM_MUMBOS_SKULL_TO_MM_MAIN = 0x0201
    MM_LOWER_TICKERS_TO_MM_MAIN = 0x0202
    MM_UPPER_TICKERS_TO_MM_MAIN = 0x0203

    # TTC_MAIN
    TTC_MAIN_TO_GL_TTC_ENTRANCE = 0x0
    TTC_MAIN_TO_TTC_SANDCASTLE = 0x0A01
    TTC_MAIN_TO_TTC_NIPPER = 0x0601
    TTC_MAIN_TO_TTC_SALTY_HIPPO_SIDE = 0x0506
    TTC_MAIN_TO_TTC_SALTY_HIPPO_TOP = 0x0505
    TTC_MAIN_TO_TTC_SHARKFOOD_ISLAND = 0x0
    TTC_ALCOVE_LOWER_TO_TTC_ALCOVE_UPPER = 0x070E
    TTC_ALCOVE_UPPER_TO_TTC_ALCOVE_LOWER = 0x070F
    TTC_LIGHTHOUSE_LOWER_TO_TTC_LIGHTHOUSE_UPPER = 0x0708
    TTC_LIGHTHOUSE_UPPER_TO_TTC_LIGHTHOUSE_LOWER = 0x0
    TTC_SANDCASTLE_TO_TTC_MAIN = 0x0703
    TTC_NIPPER_TO_TTC_MAIN = 0x070A
    TTC_SALTY_HIPPO_SIDE_TO_TTC_MAIN = 0x0707
    TTC_SALTY_HIPPO_TOP_TO_TTC_MAIN = 0x0706
    TTC_SHARKFOOD_ISLAND_TO_TTC_MAIN = 0x0
    # 0x0705 & 0x0709 TTC Top Of Lighthouse, but not the entrance?

    # CC_MAIN
    CC_MAIN_TO_GL_CC_ENTRANCE = 0x0
    CC_MAIN_TO_CC_CLANKER_BLOWHOLE = 0x0
    CC_MAIN_TO_CC_CLANKER_LEFT_TOOTH = 0x0
    CC_MAIN_TO_CC_CLANKER_RIGHT_TOOTH = 0x0
    CC_MAIN_TO_CC_CLANKER_LEFT_GILL = 0x0
    CC_MAIN_TO_CC_CLANKER_RIGHT_GILL = 0x0
    CC_CLANKER_BLOWHOLE_TO_CC_CLANKER_MOUTH = 0x2202
    CC_CLANKER_BLOWHOLE_TO_CC_CLANKER_BELLY = 0x2201
    CC_CLANKER_BELLY_TO_CC_CLANKER_WONDERWING = 0x2301
    CC_CLANKER_LEFT_TOOTH_TO_CC_MAIN = 0x0
    CC_CLANKER_RIGHT_TOOTH_TO_CC_MAIN = 0x0
    CC_CLANKER_LEFT_GILL_TO_CC_MAIN = 0x0
    CC_CLANKER_RIGHT_GILL_TO_CC_MAIN = 0x0
    CC_CLANKER_WONDERWING_TO_CC_CLANKER_BELLY = 0x2203

    BGS_MAIN_TO_GL_BGS_ENTRANCE = 0x0
    BGS_MAIN_TO_BGS_MUMBOS_SKULL = 0x4701
    BGS_MAIN_TO_BGS_TANKTUP = 0x1101
    BGS_MUMBOS_SKULL_TO_BGS_MAIN = 0x0D06
    BGS_TANKTUP_TO_BGS_MAIN = 0x0D03
    BGS_MAIN_TO_BGS_VILE_LEFT = 0x1004
    BGS_MAIN_TO_BGS_VILE_RIGHT = 0x1003
    BGS_VILE_LEFT_TO_BGS_MAIN = 0x0D05
    BGS_VILE_RIGHT_TO_BGS_MAIN = 0x0D04

    FP_MAIN_TO_GL_FP_ENTRANCE = 0x0
    FP_MAIN_TO_FP_IGLOO = 0x0
    FP_MAIN_TO_FP_TREE = 0x0
    FP_MAIN_TO_FP_MUMBOS_SKULL = 0x0
    FP_MAIN_TO_FP_WOZZAS_CAVE = 0x0
    FP_IGLOO_TO_FP_MAIN = 0x0
    FP_TREE_TO_FP_MAIN = 0x0
    FP_MUMBOS_SKULL_TO_FP_MAIN = 0x0
    FP_WOZZAS_CAVE_TO_FP_MAIN = 0x0

    GV_MAIN_TO_GL_GV_ENTRANCE = 0x0
    GV_MAIN_TO_GV_JINXY = 0x1A02
    GV_MAIN_TO_GV_RUBEE = 0x1607
    GV_MAIN_TO_GV_WATER_PYRAMID_UPPER = 0x1502
    GV_MAIN_TO_GV_WATER_PYRAMID_LOWER = 0x1506
    GV_MAIN_TO_GV_MATCHING_PYRAMID = 0x1301
    GV_MAIN_TO_KING_SANDYBUTT = 0x1401
    GV_MAIN_TO_GV_SNS_ROOM = 0x0
    GV_JINXY_TO_GV_MAIN = 0x1202
    GV_RUBEE_TO_GV_MAIN = 0x1206
    GV_WATER_PYRAMID_LOWER_TO_GV_MAIN = 0x1205
    GV_MATCHING_PYRAMID_TO_GV_MAIN = 0x1203
    GV_KING_SANDYBUTT_FRONT_TO_GV_MAIN = 0x1204
    GV_KING_SANDYBUTT_BACK_TO_GV_MAIN = 0x1207
    GV_SNS_ROOM_TO_GV_MAIN = 0x0

    MMM_MAIN_TO_GL_MMM_ENTRANCE = 0x0
    MMM_MAIN_TO_MMM_NAPPER_FRONT = 0x2601
    MMM_MAIN_TO_MMM_NAPPER_CHIMNEY = 0x2602
    MMM_MAIN_TO_MMM_EGG_ROOM = 0x2801
    MMM_MAIN_TO_MMM_RED_FEATHER_ROOM = 0x2A01
    MMM_MAIN_TO_MMM_HONEYCOMB_ROOM = 0x2E01
    MMM_MAIN_TO_MMM_LOGGO_ROOM = 0x2C01
    MMM_MAIN_TO_MMM_BEDROOM = 0x2D01
    MMM_MAIN_TO_MMM_NOTE_ROOM = 0x2901
    MMM_MAIN_TO_MMM_CHURCH = 0x0
    MMM_MAIN_TO_MMM_SECRET_ROOM = 0x2B01
    MMM_MAIN_TO_MMM_CELLAR = 0x1D01
    MMM_MAIN_TO_MMM_WELL_TOP = 0x2501
    MMM_MAIN_TO_MMM_MUMBOS_SKULL = 0x3001
    MMM_MAIN_TO_MMM_TUMBLAR = 0x2401
    MMM_CHURCH_LOWER_TO_MMM_CHURCH_UPPER = 0x1B10
    MMM_CHURCH_UPPER_TO_MMM_CHURCH_LOWER = 0x1B11
    MMM_NAPPER_FRONT_TO_MMM_MAIN = 0x1B01
    MMM_EGG_ROOM_TO_MMM_MAIN = 0x1B0B
    MMM_RED_FEATHER_ROOM_TO_MMM_MAIN = 0x1B0A
    MMM_HONEYCOMB_ROOM_TO_MMM_MAIN = 0x1B0D
    MMM_LOGGO_ROOM_TO_MMM_MAIN = 0x1B0C
    MMM_BEDROOM_TO_MMM_MAIN = 0x1B0E
    MMM_NOTE_ROOM_TO_MMM_MAIN = 0x1B0F
    MMM_CHURCH_TO_MMM_MAIN = 0x1B05
    MMM_SECRET_ROOM_TO_MMM_MAIN = 0x1B06
    MMM_CELLAR_TO_MMM_MAIN = 0x1B09
    MMM_WELL_TOP_TO_MMM_MAIN = 0x1B03
    MMM_MUMBOS_SKULL_TO_MMM_MAIN = 0x1B12
    MMM_TUMBLAR_TO_MMM_MAIN = 0x1B04
    MMM_MAIN_TO_MMM_GUTTER_TOP = 0x0
    MMM_MAIN_TO_MMM_GUTTER_BOTTOM = 0x2F02
    MMM_MAIN_TO_MMM_WELL_BOTTOM = 0x0
    MMM_LOGGO_ROOM_TO_MMM_INSIDE_LOGGO = 0x0
    MMM_GUTTER_BOTTOM_TO_MMM_MAIN = 0x1B08
    MMM_WELL_BOTTOM_TO_MMM_MAIN = 0x0
    MMM_INSIDE_LOGGO_TO_MMM_LOGGO_ROOM = 0x0
    # 0x1B02 MMM_Main Near The Clock Switch
    # 0x1B07 MMM_Main Next To Chimney

    RBB_MAIN_TO_GL_RBB_ENTRANCE = 0x0
    RBB_MAIN_TO_RBB_BIG_FISH_WAREHOUSE_TOP = 0x3502
    RBB_MAIN_TO_RBB_BIG_FISH_WAREHOUSE_BOTTOM = 0x0
    RBB_MAIN_TO_RBB_BOAT_ROOM = 0x3601
    RBB_MAIN_TO_RBB_MINI_KABOOM_CONTAINER = 0x3801
    RBB_MAIN_TO_RBB_SEAMAN_GRUBLIN_CONTAINER = 0x3E01
    RBB_MAIN_TO_RBB_CHOMPA_CONTAINER = 0x3701
    RBB_MAIN_TO_RBB_KITCHEN_PIPE = 0x3C01
    RBB_MAIN_TO_RBB_MINI_KABOOM_PIPE = 0x3B01
    RBB_MAIN_TO_RBB_ENGINE_ROOM_PIPE = 0x3404
    RBB_MAIN_TO_RBB_ENGINE_ROOM_MAIN = 0x3401
    RBB_MAIN_TO_RBB_CONTROL_ROOM_WINDOW = 0x3D01
    RBB_MAIN_TO_RBB_CAPTAINS_ROOM_WINDOW = 0x3F01
    RBB_MAIN_TO_RBB_CABIN_WINDOW = 0x3901
    RBB_MAIN_TO_RBB_BOSS_KABOOM_BOSS = 0x0
    RBB_BIG_FISH_WAREHOUSE_BOTTOM_TO_RBB_MAIN = 0x0
    RBB_BOAT_ROOM_TO_RBB_MAIN = 0x3108
    RBB_MINI_KABOOM_CONTAINER_TO_RBB_MAIN = 0x310B
    RBB_SEAMAN_GRUBLIN_CONTAINER_TO_RBB_MAIN = 0x310A
    RBB_CHOMPA_CONTAINER_TO_RBB_MAIN = 0x3109
    RBB_KITCHEN_PIPE_TO_RBB_MAIN = 0x3104
    RBB_MINI_KABOOM_PIPE_TO_RBB_MAIN = 0x3106
    RBB_ENGINE_ROOM_PIPE_TO_RBB_MAIN = 0x3103
    RBB_ENGINE_ROOM_MAIN_TO_RBB_MAIN = 0x3107
    RBB_CONTROL_ROOM_WINDOW_TO_RBB_MAIN = 0x3105
    RBB_CAPTAINS_ROOM_WINDOW_TO_RBB_MAIN = 0x3101
    RBB_CABIN_WINDOW_TO_RBB_MAIN = 0x3102
    RBB_BOSS_KABOOM_BOSS_TO_RBB_MAIN = 0x310C
    RBB_ANCHOR_TO_RBB_MAIN = 0x0

    CCW_MAIN_TO_GL_CCW_ENTRANCE = 0x0
    CCW_MAIN_TO_CCW_SPRING_MAIN = 0x4301
    CCW_MAIN_TO_CCW_SUMMER_MAIN = 0x4401
    CCW_MAIN_TO_CCW_AUTUMN_MAIN = 0x4501
    CCW_MAIN_TO_CCW_WINTER_MAIN = 0x4601

    CCW_SPRING_MAIN_TO_CCW_MAIN = 0x4002
    CCW_SPRING_MAIN_TO_CCW_SPRING_MUMBOS_SKULL = 0x4A01
    CCW_SPRING_MAIN_TO_CCW_SPRING_ZUBBA = 0x0
    CCW_SPRING_MAIN_TO_CCW_SPRING_NABNUT_DOOR = 0x5E01
    CCW_SPRING_MAIN_TO_CCW_SPRING_NABNUT_WINDOW = 0x0
    CCW_SPRING_MAIN_TO_CCW_SPRING_WHIPCRACKS = 0x6501
    CCW_SPRING_MUMBOS_SKULL_TO_CCW_SPRING_MAIN = 0x4309
    CCW_SPRING_ZUBBA_TO_CCW_SPRING_MAIN = 0x0
    CCW_SPRING_NABNUT_DOOR_TO_CCW_SPRING_MAIN = 0x0
    CCW_SPRING_NABNUT_WINDOW_TO_CCW_SPRING_MAIN = 0x0
    CCW_SPRING_WHIPCRACKS_TO_CCW_SPRING_MAIN = 0x4308

    CCW_SUMMER_MAIN_TO_CCW_MAIN = 0x4003
    CCW_SUMMER_MAIN_TO_CCW_SUMMER_MUMBOS_SKULL = 0x4B01
    CCW_SUMMER_MAIN_TO_CCW_SUMMER_ZUBBA = 0x0
    CCW_SUMMER_MAIN_TO_CCW_SUMMER_NABNUT_DOOR = 0x5F01
    CCW_SUMMER_MAIN_TO_CCW_SUMMER_NABNUT_WINDOW = 0x0
    CCW_SUMMER_MAIN_TO_CCW_SUMMER_WHIPCRACKS = 0x6601
    CCW_SUMMER_MUMBOS_SKULL_TO_CCW_SUMMER_MAIN = 0x4409
    CCW_SUMMER_ZUBBA_TO_CCW_SUMMER_MAIN = 0x0
    CCW_SUMMER_NABNUT_DOOR_TO_CCW_SUMMER_MAIN = 0x0
    CCW_SUMMER_NABNUT_WINDOW_TO_CCW_SUMMER_MAIN = 0x0
    CCW_SUMMER_WHIPCRACKS_TO_CCW_SUMMER_MAIN = 0x4408

    CCW_AUTUMN_MAIN_TO_CCW_MAIN = 0x4004
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_MUMBOS_SKULL = 0x4C01
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_ZUBBA = 0x0
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_NABNUT_DOOR = 0x6001
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_NABNUT_WINDOW = 0x0
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_FLOODED_ATTIC = 0x0
    CCW_AUTUMN_MAIN_TO_CCW_AUTUMN_WHIPCRACKS = 0x6701
    CCW_AUTUMN_MUMBOS_SKULL_TO_CCW_AUTUMN_MAIN = 0x4509
    CCW_AUTUMN_ZUBBA_TO_CCW_AUTUMN_MAIN = 0x0
    CCW_AUTUMN_NABNUT_DOOR_TO_CCW_AUTUMN_MAIN = 0x0
    CCW_AUTUMN_NABNUT_WINDOW_TO_CCW_AUTUMN_MAIN = 0x0
    CCW_AUTUMN_FLOODED_ATTIC_TO_CCW_AUTUMN_MAIN = 0x0
    CCW_AUTUMN_WHIPCRACKS_TO_CCW_AUTUMN_MAIN = 0x4508

    CCW_WINTER_MAIN_TO_CCW_MAIN = 0x4001
    CCW_WINTER_MAIN_TO_CCW_WINTER_MUMBOS_SKULL = 0x4D01
    CCW_WINTER_MAIN_TO_CCW_WINTER_NABNUT_WINDOW = 0x0
    CCW_WINTER_MAIN_TO_CCW_WINTER_ACORN_STORAGE = 0x0
    CCW_WINTER_MAIN_TO_CCW_WINTER_FLOODED_ATTIC = 0x0
    CCW_WINTER_MAIN_TO_CCW_WINTER_WHIPCRACKS = 0x6801
    CCW_WINTER_MUMBOS_SKULL_TO_CCW_WINTER_MAIN = 0x4609
    CCW_WINTER_NABNUT_WINDOW_TO_CCW_WINTER_MAIN = 0x0
    CCW_WINTER_ACORN_STORAGE_TO_CCW_WINTER_MAIN = 0x0
    CCW_WINTER_FLOODED_ATTIC_TO_CCW_WINTER_MAIN = 0x0
    CCW_WINTER_WHIPCRACKS_TO_CCW_WINTER_MAIN = 0x4608

    CS_INTRO_CUTSCENE = 0x1E00