SPIRAL_MOUNTAIN = 0
MUMBOS_MOUNTAIN = 10
TREASURE_TROVE_COVE = 20
CLANKERS_CAVERN = 30
BUBBLEGLOOP_SWAMP = 40
FREEZEEZY_PEAK = 50
GOBIS_VALLEY = 60
MAD_MONSTER_MANSION = 70
RUSTY_BUCKET_BAY = 80
CLICK_CLOCK_WOOD = 90
GRUNTILDAS_LAIR = 100

CLICK_CLOCK_WOOD_SPRING = 91
CLICK_CLOCK_WOOD_SUMMER = 92
CLICK_CLOCK_WOOD_AUTUMN = 93
CLICK_CLOCK_WOOD_WINTER = 94